apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
  namespace: authelia
spec:
  interval: 2m
  timeout: 20m
  chart:
    spec:
      chart: authelia
      version: 29.27.19
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  valuesFrom:
    - kind: Secret
      name: authelia-secrets
      valuesKey: JWKS_KEY
  values:
    global:
      stopAll: false
    credentials:
      home-s3:
        name: home-s3
        type: s3
        url: ${S3_URL}
        bucket: authelia
        encrKey: ${BACKUP_ENCRYPTION_KEY}
        accessKey: ${S3_ACCESS_KEY}
        secretKey: ${S3_SECRET_KEY}
    ingress:
      main:
        enabled: true
        ingressClassName: external
        hosts:
          - host: auth.${DOMAIN_0}
        integrations:
          certManager:
            enabled: true
            certificateIssuer: le-prod
    cnpg:
      main:
        mode: recovery
        password: ${CNPG_PASSWORD}
        backups:
          enabled: true
          credentials: home-s3
          revision: "2"
        recovery:
          enabled: true
          method: object_store
          credentials: home-s3
          revision: "2"
        cluster:
          singleNode: true
          postgresql:
            wal_keep_size: 5GB
        monitoring:
          enablePodMonitor: true
    persistence:
      authelia-secrets:
        enabled: true
        type: secret
        objectName: authelia-secrets
        expandObjectName: false
        mountPath: /app/secrets/
    workload:
      main:
        replicas: 1
        podSpec:
          containers:
            main:
              env:
                AUTHELIA_SESSION_SECRET: ${AUTHELIA_SESSION_SECRET}
                AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET: ${AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET}
                AUTHELIA_STORAGE_ENCRYPTION_KEY: ${AUTHELIA_STORAGE_ENCRYPTION_KEY}
                AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET_FILE: "/app/secrets/OIDC_HMAC_SECRET"
    authelia:
      theme: auto
      log:
        level: info
        format: json
      totp:
        issuer: Authelia
      session:
        cookies:
          - domain: ${DOMAIN_0}
            authelia_url: https://auth.${DOMAIN_0}
            default_redirection_url: https://homepage.${DOMAIN_0}
            inactivity: 2w
      authentication_backend:
        ldap:
          address: ldap://lldap-ldap.lldap.svc.cluster.local:3890
          implementation: lldap
          tls:
            server_name: lldap.${DOMAIN_0}
          base_dn: ${LDAP_BASE_DN}
          additional_users_dn: ou=people
          users_filter: (&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=person))
          additional_groups_dn: ou=groups
          groups_filter: (&(member={dn})(objectClass=groupOfNames))
          user: uid=admin,ou=people,${LDAP_BASE_DN}
          password: ${LDAP_USER_PASS}
          attributes:
            username: uid
            display_name: cn
            mail: mail
            group_name: cn
      notifier:
        # disable_startup_check: true
        smtp:
          address: submissions://${SMTP_SERVER}:${SMTP_PORT}
          username: ${SERVICE_EMAIL}
          password: ${SERVICE_EMAIL_PASSWORD}
          sender: "Authelia <${SERVICE_EMAIL}>"
          identifier: auth.${DOMAIN_0}
          subject: "{title}"
          timeout: 15s
      access_control:
        default_policy: deny
        rules:
          - domain: "spoolman.${DOMAIN_0}"
            policy: bypass
            networks: "192.168.2.0/24"
          - domain: "print.${DOMAIN_0}"
            policy: bypass
            networks: "192.168.2.0/24"
          - domain: "*.${DOMAIN_0}"
            policy: one_factor
            subject:
              - group:users
      regulation:
        max_retries: 3
      password_policy:
        zxcvbn:
          enabled: true
          min_score: 3
      identity_providers:
        oidc:
          clients:
            - client_id: "fFevFHpxxEy0vcp4xCDWITAOllSwFfLYpLACIbrgxdEZdDB3eo4O4z68eXXvj2WBcBtNFv52"
              client_name: "Forgejo"
              client_secret: ${AUTHELIA_FORGEJO_CLIENT_SECRET_DIGEST}
              public: false
              authorization_policy: "one_factor"
              require_pkce: true
              pkce_challenge_method: "S256"
              redirect_uris:
                - "https://code.${DOMAIN_0}/user/oauth2/authelia/callback"
              scopes:
                - "openid"
                - "email"
                - "profile"
                - "groups"
              response_types:
                - "code"
              grant_types:
                - "authorization_code"
              access_token_signed_response_alg: "none"
              userinfo_signed_response_alg: "none"
              token_endpoint_auth_method: "client_secret_basic"
            - client_id: "HJ5PKeEu4kyBQkneNOld3wC5Nu2XHK73fqbYg2r3V4zIwRvuaGaSLT2KFCGJtSXC641ezfeH"
              client_name: "pgAdmin"
              client_secret: ${AUTHELIA_PGADMIN_CLIENT_SECRET_DIGEST}
              public: false
              authorization_policy: "one_factor"
              require_pkce: true
              pkce_challenge_method: "S256"
              redirect_uris:
                - "https://pgadmin.${DOMAIN_0}/oauth2/authorize"
              scopes:
                - "openid"
                - "profile"
                - "email"
              response_types:
                - "code"
              grant_types:
                - "authorization_code"
              access_token_signed_response_alg: "none"
              userinfo_signed_response_alg: "none"
              token_endpoint_auth_method: "client_secret_basic"
