apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - statech-industry/ks.yaml
  - jan/ks.yaml
  - jan-2/ks.yaml
  - ftb-skies-2/ks.yaml
  - monifactory/ks.yaml
  - nomifactory/ks.yaml
  - omnifactory/ks.yaml
