apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudflareddns/ks.yaml
  - github-release-monitor/ks.yaml
  - homepage/ks.yaml
  - kubernetes-dashboard/ks.yaml
  - nextcloud/ks.yaml
  - part-db/ks.yaml
  - pgadmin/ks.yaml
  - spoolman/ks.yaml
  - vaultwarden/ks.yaml
