apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - forgejo/ks.yaml
  - github-release-monitor/ks.yaml
  - homepage/ks.yaml
  - jdownloader2/ks.yaml
  - kubernetes-dashboard/ks.yaml
  # - matrix/ks.yaml
  - nextcloud/ks.yaml
  - orcaslicer/ks.yaml
  - part-db/ks.yaml
  - pgadmin/ks.yaml
  - qbittorrent/ks.yaml
  - remmina/ks.yaml
  - spoolman/ks.yaml
  - stirling-pdf/ks.yaml
  - thelounge/ks.yaml
  - vaultwarden/ks.yaml
