apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvidia-gpu-exporter
  namespace: nvidia-gpu-exporter
spec:
  interval: 15m
  chart:
    spec:
      chart: nvidia-gpu-exporter
      version: 5.13.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    # See https://discord.com/channels/830763548678291466/1371521205667889173/1371919253371883560 https://pastebin.com/9E17Pnu9
    global:
      stopAll: false
    # disable all persistence options as they don't work on talos.
    persistence:
      nviaictl:
        enabled: false
      nvidia0:
        enabled: false
      nvidiasmi:
        enabled: false
      libnvidiamlso:
        enabled: false
      libnvidiamlso1:
        enabled: false
    workload:
      main:
        podSpec:
          runtimeClassName: "nvidia"
    # .. instead assign the nvidia device to the pod as gpu slicing is active.
    resources:
      limits:
        nvidia.com/gpu: 1
    # metrics:
    #   main:
    #     endpoints:
    #       - port: main
    #         relabelings:
    #           - sourceLabels: [__meta_kubernetes_endpoint_node_name]
    #             targetLabel: instance
