apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rustdesk
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/infra/rustdesk/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
