apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: generic-device-plugin
  namespace: generic-device-plugin
spec:
  interval: 2m
  chart:
    spec:
      chart: generic-device-plugin
      version: 2.13.14
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  releaseName: generic-device-plugin
  values: {}
    # workload:
    #   main:
    #     podSpec:
    #       containers:
    #         main:
    #           args:
    #             - --domain
    #             - truecharts.org
    #             - --device
    #             - |
    #               name: tun
    #               groups:
    #                 - count: 1000
    #                   paths:
    #                     - path: /dev/net/tun
    #             - --device
    #             - |
    #               name: serial
    #               groups:
    #                 - paths:
    #                     - path: /dev/ttyUSB*
    #                 - paths:
    #                     - path: /dev/ttyACM*