apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nomifactory
  namespace: mc-nomifactory
spec:
  interval: 2m
  timeout: 10m
  chart:
    spec:
      chart: minecraft-java
      version: 33.8.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    global:
      stopAll: false
    credentials:
      home-s3:
        name: home-s3
        type: s3
        url: ${S3_URL}
        bucket: mc-nomifactory
        encrKey: ${BACKUP_ENCRYPTION_KEY}
        accessKey: ${S3_ACCESS_KEY}
        secretKey: ${S3_SECRET_KEY}
    service:
      main:
        enabled: true
        type: LoadBalancer
        annotations:
          mc-router.itzg.me/externalServerName: "nomifactory.${DOMAIN_0}"
      rcon:
        enabled: true
        type: LoadBalancer
    persistence:
      data:
        volsync:
          - credentials: home-s3
            name: home-s3
            type: restic
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: 30 6 * * *
      backups:
        type: nfs
        path: ${NFS_BULK_DATA}/Backups/Minecraft/nomifactory
        server: ${TRUENAS_IP}
    workload:
      main:
        podSpec:
          containers:
            main:
              imageSelector: j8Image
              env:
                OPS: Hydranoid620
                WHITELIST: Hydranoid620
                DIFFICULTY: peaceful
                VERSION: 1.12.2
                CURSEFORGE_FILES: |
                  ae2-fluid-crafting-rework
                  flux-networks
                  lazy-ae2
                  project-red-illumination
                  zbgt
                TYPE: AUTO_CURSEFORGE
                CF_API_KEY: ${CF_API_KEY}
                CF_SLUG: nomi-ceu
                MAX_PLAYERS: 10
                MOTD: Nomifactory!
                PVP: true
                MEMORY: "10G"
                # JVM_OPTS: "-Xms8G -Xmx8G -XX:+UseCompactObjectHeaders -XX:+UseZGC"
                MAX_TICK_TIME: 60000
                RCON_PASSWORD: ${MC_RCON_PASSWORD}
                SEED: "8881742655673709427"
                LEVEL_TYPE: "lostcities"
                GENERATOR_SETTINGS: "{'profile':'uncommoncities'}"
                FORCE_REDOWNLOAD: false
                VIEW_DISTANCE: 12
                SIMULATION_DISTANCE: 12
                USE_AIKAR_FLAGS: true
                USE_FLARE_FLAGS: false
                USE_MEOWICE_FLAGS: false
                USE_MEOWICE_GRAALVM_FLAGS: false
                USE_SIMD_FLAGS: false
                ALLOW_FLIGHT: true
                STOP_SERVER_ANNOUNCE_DELAY: 15
                STOP_DURATION: 40
            mcbackup:
              enabled: true
              env:
                BACKUP_INTERVAL: "4h"
                INITIAL_DELAY: "2m"
                LINK_LATEST: "false"
                PAUSE_IF_NO_PLAYERS: "true"
                PLAYERS_ONLINE_CHECK_INTERVAL: "1m"
                PRUNE_BACKUPS_DAYS: "4"
                TAR_COMPRESS_METHOD: "zstd"
    resources:
      requests:
        cpu: 100m
        memory: 6Gi
      limits:
        cpu: null
        memory: 12Gi
