apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nvidia-gpu-exporter
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/observability/nvidia-gpu-exporter/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
