apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:3BUOsxdZZAWZ2hIUwWEYfloKQ5dVJgcWc1uaROC4E3xiyikqg5JGyq5udoVzc2ASSCj4n5IZt972Wzo0lQpvuh4=,iv:nIQNzcxL0Q1pS+IQMGYMQXp2pv7EXxn9xEv32xaIF/c=,tag:ag0EkRjv+3QQnV7xOc0h/A==,type:comment]
    #ENC[AES256_GCM,data:FrWtV12IotVLrNFY+HYPBtZhcMHj/1wwTTsno0fN/PO9X0V+S3dbd0A7xwg=,iv:SJzmiGQHgXyv3pXUzjDyJlRNKSUzGO4wKLCAjXPhFdw=,tag:dt0PfsMyC+m/LNMkJBWHQQ==,type:comment]
    VIP: ENC[AES256_GCM,data:rSOy6noWvaCBoNd6,iv:qf3+qu3pvU8xClXpDv+BiCf+E7bYeNKeUIzE4IfdgZ4=,tag:a/ZpG253qnJ+rhrCZIB28g==,type:str]
    #ENC[AES256_GCM,data:EiFQeAvnHy8RTJFKQtY8mgUdqJL5mhzYhJgs,iv:/3IdfBdM/RoyzJXIsgOOu0oUgDWv6xF+oo7kd/YQEmo=,tag:UXZ9z1BSFU3JMSIA7fB/fw==,type:comment]
    #ENC[AES256_GCM,data:zHPWVOLPsM6wz2wljbHun8WajoGfteE8YsA02L6agTXgPCn9H5v7J/Xrc8upey+UP70ScPipuKBlqMnfhHTDjko/AovB63wreQEL4WN6qKOKEwKFLTQ3wlY=,iv:opZwUBlwXFiKZztYAh5UAk4ikssdewJECQxvVon9FYA=,tag:S6ViMNfJUfSHc+TJiCsJ9A==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:MoQQTW6FEmZ2n+Ws,iv:aY0dSxWYfcnAE6Au8Mf4FOk5Lv5Y3zIh30uqccMKhB8=,tag:G58gWwViaAPUwumGSg2B0A==,type:str]
    #ENC[AES256_GCM,data:Enf0hcnedOXVz4TJY6N4nKJljNaP29RJqz+xtufUmUC2Rw==,iv:zhMnv0HtbptoJLYxqTn2vYnz8MQ26+CB/yO8u4N978U=,tag:fXNRAtpCqZvzNvb6MyMJHQ==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:aQ4qvS28J0Ahc+8=,iv:Hkxh89M6z18+QcoLlXHiYJ0Js7b/4Gpcyb1xCvH8Hs8=,tag:mnbyRfUAU+b0+2ZbjCH5Lw==,type:str]
    #ENC[AES256_GCM,data:hnPdZhNHhNmf+3FqIfV6rkA2iZrhwepCvSuk6QxVDtmKLacF6Pn19tLjqmVR8Og=,iv:z+ZCBnmsYDbiQLLdP+LMkvRKn+RiNl2yeU3SlQaq2uc=,tag:2i34lImvet0uiQtdFZgTSg==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:cVAlfMapbEYEwZ//2tylv5d8/y3LbWbWmKpR,iv:ZTFPZRS5YwIb6vm3HbmPejqFZSYiA8gwdQ/iXag9daA=,tag:ot4hVrAw9sshM5jo+nOdbw==,type:str]
    #ENC[AES256_GCM,data:eLKtc5nMxI/+XovR,iv:rxvV8yenIX+oj6Nef+ZYA14WaYq6Y6wpU4998bujiK4=,tag:bz3h+phXgPa3VZA5U6xKrQ==,type:comment]
    PODNET: ENC[AES256_GCM,data:4K5RLqMfkFxvhLdWQg==,iv:Ln32Mf1Ir3ZJ1VAI/+LkRPAYYjtK2nGhW4eIr+jR6uU=,tag:XgHmd9UO9ELpXWdq5qfCUA==,type:str]
    SVCNET: ENC[AES256_GCM,data:NL2LL9DVyGseo4126A==,iv:3uZLzXRmoyMyrRmlTfPVk/uyWRZ5dy7ox8kSI9zzAIU=,tag:kxW/6/7EhqVe2CY0EzXKhA==,type:str]
    #ENC[AES256_GCM,data:+z9fInF+IQ==,iv:bEvqqwP71isrAgzCGW/qdOeesPaMRWod3Q1SO65FW3k=,tag:h5Cv+GXYKUeJ62fNY6YqCw==,type:comment]
    NGINX_INTERNAL_IP: ENC[AES256_GCM,data:uHgECxilkcmpxQukzg==,iv:OCu+fXNkpfrwsHqZJCUpA8c7l06n6BnWea1eng14G2M=,tag:Vh8ORJi8QgCVYoU8B0KY+A==,type:str]
    NGINX_EXTERNAL_IP: ENC[AES256_GCM,data:yqIph/S1CuMYM4Be7g==,iv:Kkb/2Ng+noddALBxDMTawIM64lk/90KkW45SUtnEJm0=,tag:xmR4wubUg4znhTJDmwnSkg==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:NlImILo+3BkRlxaUbA==,iv:Ydh39hE/AOp0cD4N6wHmIw2V68yXMXiIRsJxyP7Efo0=,tag:IOR4oaRGD09lDOctaucPrA==,type:str]
    DASHBOARD_IP: ENC[AES256_GCM,data:rcNr5f45Sc9Ax1qF+Q==,iv:55DRp7u+ctTOVmB0xGpQnPbOoutpuMdLQ30wgBJxpac=,tag:386/lz+13Q9aP3G8UtIwcw==,type:str]
    #
    #ENC[AES256_GCM,data:b9I+eDqk3w==,iv:I8ZoP3qBggAvrxYPDSxA1aEeqjNvTWO83HCaI28uzNk=,tag:iwWejiLY7Z6Q0qiLwpnp/w==,type:comment]
    DOMAIN_0: ENC[AES256_GCM,data:5Yb06hZZSVW0vuaSxIFlp18i,iv:QaIcwjg4hL+EGysUdpsuZyfV//LMUz7DCgEnXiGebHw=,tag:FeMgDWCFIxLFJ16owulMXg==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:5V4JNSk3jABQXOV38sv0uyMJ,iv:n6+sojzF1Zh0/u6YKB46LhxULn29EeKo0Bv25aBPumc=,tag:K6fXUgEsqEXLEI02yZUblw==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:8jKZJ7iXkoZJT3CoU7ufrVLUpi6sLue27qYF/Lt7cBbSscInnzT0nA==,iv:x3YUXuyEFZYvN5Tp0H5L9Ds3tCJwuPAMNNiZRvjX/5o=,tag:s8vkHvyHSPy2wC9qA9y7Gw==,type:str]
    DOMAIN_0_CLOUDFLARE_ZONE_ID: ENC[AES256_GCM,data:Zmi1kKIY/6lpgGpwxzft/MmmwWFykJ4AYaqMa/mAQV0=,iv:dvZBfkJcaBNaZGkKxB8G7wMyuOQYFjxn7G9bB/gHdec=,tag:8tynZMWr2ZMXdvfGty3oRg==,type:str]
    #ENC[AES256_GCM,data:caxOHC0ENIyJx2SZOkt/W9UhDZAD/90mu4KpwgEo6M5Sovo+4sKKGsYk7jfdVx6rnUw0sj1pPtY=,iv:LuWE27/MDMwrdIPfxMSdaqKrlMEwJN9rtbYs7/6V3YU=,tag:0LMgZLFTOY/c+Ke0+SITHg==,type:comment]
    #ENC[AES256_GCM,data:Pvss0WapOZB2dRvkbr0mb8RVN7iGn9NjfQ==,iv:bnylFE2w1OGCGVYOKzPbQLmycnfBctdp0T7weN103bw=,tag:J1o3uFj/FXd+J6ltkwMjAA==,type:comment]
    #ENC[AES256_GCM,data:yVwo+Bza0t2zQxCpUpyVHVgKxgRN9M4eaxSeftW1Omif/uCd4gV2ynD//3sFhfAsDF+hJUKzVCk8pX7aycp8L8ceMGtHb6wbGIv0AQU=,iv:MTKTUR0goRN/39JzSl0KGoDsqujfDGQ09V+wI01asYo=,tag:YyE6lTSuTmY+GxQX0ff74g==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:HheFPy3h4Gnsr5+NTMkZfj40Qi+aIxcXzBZckFUhlt4EBFNLqNp3,iv:mG5/JHYwXAkVR4OWrOUoq9w1Yll4Zp/j1MirkMSQ3eU=,tag:HnrHQdQVinvyzqknrbWTLw==,type:str]
    #ENC[AES256_GCM,data:Hc+afnzrbElkJv23qqY9hBRyBTLV1A8EagXaDUUljPNMtJOHVNwILRqLq/A2vTyKPP8If3OV26Di8TF+CGOM9XU6XMJjWSQ=,iv:RJg7Usvn/5XDpcIfY2Ws075CIyTU+kP9W/pX8DkUQT4=,tag:+5vuu9++4s7uzfcxXDhcpA==,type:comment]
    #ENC[AES256_GCM,data:D8ZjvOtIdukTpp/raUKIxXGgNHydwvoIzrvn/oPctHnIj0n98TMSaVbJd43l/5MW739L7c3v,iv:wHUvsH1iqTk3HqSaeeEeZTK9+ypoSK7BT4Vd+OUJpBQ=,tag:yuYZZ41eZSfh8Bve8VlrCw==,type:comment]
    DOCKERHUB_USER: ENC[AES256_GCM,data:XsJy9PrlJXowt6JB,iv:A4C9ec2ksH1kQ8U+r5LDKBQ3hnIyrjIgN28Us8BfgH0=,tag:nS/gzS6k5k4JkRSmS0emTg==,type:str]
    DOCKERHUB_PASSWORD: ENC[AES256_GCM,data:elFpVHSFuXzU28k8iGY=,iv:9N0zIfwXKeJPzimhxVpIRnAvpKjWlLBEOmeEtnJsPKs=,tag:ZKGbi9T8losVRqJlYKR7xw==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:xk9qNQ==,iv:EB+IVnOFBt2HEDT45ZWYiNcFH15nM2C9DtK1kFvfNTo=,tag:nvnpCOWwpXLgZTKF9hDcLg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMTjFzVXNVRmI3NzRIcitV
            dUlaUDFhTnlhTlZpMXN3SjQzTmNiREwyS0ZVClY1N3VId29oWS80T0xwQ1dvVEJh
            Y0RyVTMwaGNVUDI5NmRJYnp6RkIzeUEKLS0tIGVaazN4cC8xSzZEUmdYZ0xqbXNy
            MHNCdkR1TlBxWlVGUDd0WllyenJjVGsKVJyAjB3iPl3/fye+cD+QAfDNh/TYFFMJ
            yq7WMdXF5r1L1o9ICgH18CwWS7pPycdmKdGenKMNsygwYMW0tO+eeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T00:03:42Z"
    mac: ENC[AES256_GCM,data:UG62CSNyOOISr0OaTcQYsRqEpaYlG8PBKOoo8fCcy9a52k0P3s6gxFCB9ipN5J1Hm5MclRSG/m8MidNG4z675hlJuC1tiB+U+aXDLBy37j1OzVGHEg2P/wfIQhLD3Zzk+qi9HFx+iNK57giv0f/kbAQ1pz7qyTZXACbVGUWZmSc=,iv:rqU6+6LHz7XBVlAn6B3tPNasr9Epg4AXk1+dSb1Dgy0=,tag:0X3ZsFBysFAFOatuvOAxiw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
