apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:fOZlj+2mSyhnQj0NKugHuY6Vgqpr2Oqtk9GH6d6bA0KAeZ9qCFAH7bd5yDb1Va1DZfdb1rm2XHZ5rhaRsnFY6Rs=,iv:rlnkMAkEs/ZiAYfDMFZfEpIs+RaLA9nvUw8Y5VOd4nk=,tag:Up9fnNu1cvFNe5NtRBvzGQ==,type:comment]
    #ENC[AES256_GCM,data:g4OvmMoqqS3hHqW+hmtZKo61j7jeA+0+TcNVysPoalCZcuJJPBmu4ea4eTo=,iv:NSxy9+kzH9usqeRBQqnr5aWhuJhuhrUNwifLiVTqzrY=,tag:j5ydcPxwUFKfwfWvjkcXFw==,type:comment]
    VIP: ENC[AES256_GCM,data:8zgU2b0y11UvyT6F,iv:T6R7fmcM5E4VQNZmS9xqYcEP6jzcMhJKyeO3rIStxvw=,tag:1INPRnz5ofkrAWDBBC6qWg==,type:str]
    #ENC[AES256_GCM,data:pAKXm8yVSM14xA+ciwAyUOVQu69VefslNJ7G,iv:d32yuzCTn8JisF6aPxPG+xjoEffvBzze0Md/P/wjaRU=,tag:k08QY788oAPQCDVgVDukaQ==,type:comment]
    #ENC[AES256_GCM,data:/Y+OWr1WNR/CQEMOLx/fknTcJVZTdhWzVVqw2aXWWoaEwVn6lC0JbhSZDYCj3VnoPhgBbI6CgsUpiV6YYxjVIA/rIiVGEHr/Wz3vBV2PU5vuRuEjIR9y5lg=,iv:iIv18foXL1n8ZSvAdrvDEa03HwDIyXim7VEmw873W30=,tag:kpBW1eWlM06tXMiTJdtW2w==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:x3KAchytE1Z7pH62,iv:PvgcwCJ1F38gVTkZwU5GwuoAmQqEVQNoc0nxAhrLulQ=,tag:s4SVFMyBdfLEsx2Ao4MjTw==,type:str]
    #ENC[AES256_GCM,data:xWkDHE038rOy3Hqih7wa/OT4P/m05jKgUgOtryJ6K8/MMg==,iv:G6uVoxk+3jLbzc1zd6YiTutemowsyEq3ZSLV8oMkSro=,tag:eTRUZT1vookXFMVROQU8+Q==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:a67GvvNXgAcJIxU=,iv:7F8faQnDKklB1eURzuJfYRaItqxbnyMo/eGuGsYv2Gs=,tag:+WMVDpoHyP9ycD5r710t0g==,type:str]
    #ENC[AES256_GCM,data:oUKtJsgbIvves6OpA/6P/N6+Vk4OV2pkmKzgPp6BgA+lwBPcd6QJpXkCW44nT8A=,iv:2aDIEWGBgX7RNlVSk+n3xmOtt4tyJHuYlu9j4PuDZWw=,tag:TGVFNhDkICF2hMzMH3aG5Q==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:wTtyMJooGOX873b6vNwpt9vhLgHQ/4uJeMBm,iv:1C0emEr2u22Yo2rRlCv60/ZN9DDorQGxPYb0y8eqnmE=,tag:vaAArNcuRDcfJlUuvdRL9A==,type:str]
    #ENC[AES256_GCM,data:1CA2717joPTYpgB3,iv:eShOzP6ru3MdWdhgwBvAxGMZ0dAk6SgI7rSA7g2JS4o=,tag:aDD/iUlDMYON6zNKywwt2g==,type:comment]
    PODNET: ENC[AES256_GCM,data:WtuEQywRBNa+JhFaJA==,iv:HduyWQct6inRJCeRV25jR5hj0RZuL2wC1MyBm6CNlRM=,tag:X1CBSJZ1xqbH056VmB9wHg==,type:str]
    SVCNET: ENC[AES256_GCM,data:LRTMYqq+W0TRvpGB7Q==,iv:k8o52fmXAfpjkrwKrokfMviYBFEmei5WqvdtTL+INbY=,tag:pdZSpQRIOEd9gU4b7kbPpQ==,type:str]
    #ENC[AES256_GCM,data:/eGj0xdIxg==,iv:ELeo3d0sZARHzlnigPFPGX+gBkiPxjsnHNpG3PYDvqM=,tag:eXpxXLpWwXCyifkrN1+EeA==,type:comment]
    NGINX_INTERNAL_IP: ENC[AES256_GCM,data:2etXXPssiMihm/2aeA==,iv:T/rFDmW9mI8QPYddIuMUWm91QRJwrbeNaKLlsJUJsTw=,tag:GB9f1Vdb+401Le3Qbozykg==,type:str]
    NGINX_EXTERNAL_IP: ENC[AES256_GCM,data:nU+M1UWmcDHP9eO+CA==,iv:bKTWGEr7jpjcLD2yBnPivrs95EuzNVMDqzB3QMyn00s=,tag:F42btC1JNKTZsDkAHOK2dg==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:WibE+eWBRhxcr1aSRQ==,iv:ZxEbKTud7VqNTe9YQZyweRnGxjkUTfCKnoOAriWYUNA=,tag:ix5pWJ3ZgLexIh+p51e/aw==,type:str]
    DASHBOARD_IP: ENC[AES256_GCM,data:b3ibFDy+sUXpiepvoA==,iv:fHHapEggn2s/raH2w+NvAzRf3b0a08VRqheERdDNRA0=,tag:A5hHbhRSJz2MoCh0oBPUvA==,type:str]
    #
    #ENC[AES256_GCM,data:FhGKYk6V6g==,iv:EuhrU7pfN4ELcCzog6VQ+zDt5rBdKKpkotQgEtVnUdc=,tag:k4WTkL8hcaVauVHdzWmKVw==,type:comment]
    DOMAIN_0: ENC[AES256_GCM,data:u6Q//Ly1yMxJohpvSKrP11NH,iv:+Biy7HZyAgz2of3cMgBwW/h1aLF7FQLl0uQPtDF9PhA=,tag:u9vS84lhzL2tZbi2hoVwlA==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:ZxQ12dhVHDqhwZrhstqPWD7/,iv:TC3l5EXmtLfWE1fgKkAa4eqKp/y7/tqbnkHtfm/aEBI=,tag:VJ0C5BMHGX/m/FpSBvsnAA==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:FoZdf6BeR374w2hb3Gw36ZECjO4gKzs2QHYnc9PkW0dDehjCn7oYvw==,iv:O1a+v8XsD08dbo3j7LnABj7YwV0p2e7jkXCAaDKE5oQ=,tag:lPHFvhslNPi9Y5UxtztVIw==,type:str]
    DOMAIN_0_CLOUDFLARE_ZONE_ID: ENC[AES256_GCM,data:GMhrkSNzEys6ATKYvxN8cDWMtJ+TPb3QWiyGOiZNPjU=,iv:8Z6H10QQ2zd/K+YsDzLJUqaYZcXF2yIWeadktv0Ib3E=,tag:BIa44W8ag7MAXFOsqY8Qjw==,type:str]
    #ENC[AES256_GCM,data:iplJv1wOBOYAHGq+z9Jsd7C7Eso313zPX6o1lQ/ONDPTOSDFfvHPjNKIqhZWaUrzlkBZKdKgKmM=,iv:nqxsmGTZVZNo6Olsv6FiYj+Bju8mqY5oPAVfsJHTOcM=,tag:Q8GGYC7SrUj9PZbjVjxyvw==,type:comment]
    #ENC[AES256_GCM,data:mMhL+jyHxX7z0mgWWAaI8N7W5OKWPiHSRw==,iv:646y7WtCZN52Ad3/7DuTVvJjjGDV51XsCWXWWpRwyLk=,tag:X2A5v5D4M/MlI3JIu/ewhA==,type:comment]
    #ENC[AES256_GCM,data:xKkJdo0T4HV1Z8ojzVc4OD60FGLob4VwxsCZ8c7wcIOQbtRjNn3x+6vqE5rpwtzHXnxVxHtmTbwHVhqT+rmOaIKy6pNCWu5YXvR3UqQ=,iv:tm5rkDrSvG/+xnLyBdDiTlj6WRiqxQpVWK18dxzwfVg=,tag:FaHUyKFLK/k5YpD92eEWeA==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:ziipUGG82b+MqiloQM8CRb2HXtTjJ5UFOQPnePrymRUP1YTVemgv,iv:Uu8BcyYR5kDH3MLFbLp5wlyQhEwj9IHeQx2T3yeuZsM=,tag:dlohnHvadicvlK77zMNv7g==,type:str]
    #ENC[AES256_GCM,data:iR1+fexoIqJjSTvmhU3vwbSSSNRBH05Xgn4EwRqktqGrpKbWK13qwpfB+5RDmsLzh1zDUS+3XxDzdY+xiwBU8ReMxvsSkT0=,iv:lya7sw/ljUkZjN8OuNIbytbjuAEn9eAV3WYNOVjbVyc=,tag:n2cklmWVMgzDnMqXOs3kCQ==,type:comment]
    #ENC[AES256_GCM,data:QAHVPLsVpXsp9qu96xd53w773yjD2qoB5uPH2e92HzWOXvAzF6thhh86nN6Qs44bwFT1OSmJ,iv:LOCP3ItlRriGYiTk6hlt1Pc6y/lb8LYPj3zmrp3XZJs=,tag:LFl6VNGMwTdXeTCx/mJclA==,type:comment]
    DOCKERHUB_USER: ENC[AES256_GCM,data:OmXFgDtQBzSYl+Is,iv:Etbi8OW0UrwH9AreUpR6Ka/I9PPxZYluH89YWIB8f9A=,tag:W8+odjFNtm7oPNnue+ne7Q==,type:str]
    DOCKERHUB_PASSWORD: ENC[AES256_GCM,data:iGxVgxiJvuF0R1MJPIY=,iv:rSUFC56Psr1z5Zxk/bIrwZjCtXrbQo8MVtD7beYRBHE=,tag:oeOjM0dVSrwA8Q2mIC8FBg==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:O7NXzw==,iv:LvfkFjLjf+mvKe69AJhC3HTNR/MDPxwYHxHmqGDm8iM=,tag:k88YPQdSSP4LYv0mU7eCRw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArMXhsZUxWSFJjRXFwN0oy
            elRtNzJwNG9jZzlldTJBekcrZ3NJb244UUFnCnA4eFNEZWp2WWxQVFJMZFhrL2Rz
            Mnk5OC9HdTZicHdhRDJKTjVRUzZnbFkKLS0tIHpVU3RQYnUyeGY2dUVZZDhxMldQ
            eCtjcitua0xGVkQ5SjJHTHZBcXZiVDgKCpczXMH3bCu8YylQ3/jtph7x1xN4JjCc
            K18rGkf/0byIGzPhtrNnCfjiAkfRfCEs3zPaHqzucmDMrsr3L4/9vw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T01:02:59Z"
    mac: ENC[AES256_GCM,data:ivnYaGOzyPhebl01pO+Q+t91/v4suVb4XhTXb94bL4Un5ZxDBdKwa1Hs2L/f9CbD+BCeepObLTVvNBO1EzydPWGkQIkxk8yMob40GXtzKOvU2mkwws5RPhENS1hAp2pKspQlCBlmkSElIV4ppcTLbMpk562DMWzlEvMWdgDOkgQ=,iv:TjvOQy4cJUarw0mkrdpJ8I8Z7UyFbSSsJo4y7Mh5CQA=,tag:yhWlKdrXjI/sR7oE9IIciw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
