apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:d37lAABECuPrW9llwI5ekh4FnIYCycHtXXlqDJqbWhsMafJkG568K3Rr4mjHLaUrjg5lipQuWv8GnDA0UDhq7qc=,iv:3OqFZM4xjDvt4hYNoBaXWqmkoJ09TgzZ536gFCtEy40=,tag:qwH+OOnW5xK6VvllUBjLmA==,type:comment]
    #ENC[AES256_GCM,data:bQTRcRG3NRgV1No29YrnGzKNn0C+gh39ab8PLI5L8tOLRE4P9wDTIzmC9dQ=,iv:c98F5y41qhC1EYchSFyf/0LBvUSc0o5iOQZb0UEpEpA=,tag:t5mnxFz6m1ePjItK06OEmw==,type:comment]
    VIP: ENC[AES256_GCM,data:33XSNiDcPQ5c7lOg,iv:0OAfzBW8K6Z9zpQH8YeHUtnkJAvbKxlGONuKNLdxtGg=,tag:KPQeJeizpSG+/t9q8Z7Zsw==,type:str]
    #ENC[AES256_GCM,data:D/Je2eU7SCwYY2kyseZV4uhnOr5KLAZd5kqv,iv:MSuqP6MRYrrfW1QV5/8pjLeZvDzKaDasoPQvehE0Omo=,tag:azL6QU7CiNEYEJoc6CVoJA==,type:comment]
    #ENC[AES256_GCM,data:8jJwOnKD1SDqn9eEhp/RVP1RCaoVXyoqjs1f2Jf5H0/+5DCBHvavVrusg+5xc0wPCrZXhKlyQjBarwZaMCFuBo7DYjIOqru3OGD5/q4NaUc/qBURqnydRnA=,iv:SfVOFFf8sqzvsJFfhEEQsEFGOCqN1qSTVPGeog4dVcA=,tag:YZaS/CfVWK9BNOEI+L5GTA==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:eb3rHkGLXw3jTEWf,iv:Yty6WNcrKYw5V8AmyTYl6xZLoPQcSZjaStkWlpsxOD4=,tag:/tSx53dR7WFWz446r/Kg4A==,type:str]
    #ENC[AES256_GCM,data:epIAq5Bgi0H8hlqf49f+HeR0eBbkb35DGiK+d07i8PPVjw==,iv:d4e3n8G5/2We76PYq30HKYzuIcOxCm0bmouaBD3vMVo=,tag:J8iws/KUyRKk9E/EysyuHQ==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:M2m0ndEU6RF0hbU=,iv:txBF3onpxiHzPiIcWrYMsQt+bLN45M1rnf9d5XzyPVI=,tag:Wz+YjXyYyMvLJ93uW2dbwQ==,type:str]
    #ENC[AES256_GCM,data:RQg1Zd3TWofxYlRV3IzSBrzxC/JGg08HfpI/fWW+IEma6ife1xa/S0fXm+aR6ac=,iv:+44UYyK4KADK/nqGQa3HhnYvfIDfivxo2SutUwWYSOA=,tag:W3vMnI7wFGfdIAld0RINpg==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:NyTK5LlYDe0K3hZ5aqq3jMMMSGXOhDMfurCm,iv:pkVIpsWXBaRGc+gY4spdbp1LuvswoGsbpTK8ePjxJsI=,tag:UBeAMAkpHmIatlM+BRnzZQ==,type:str]
    #ENC[AES256_GCM,data:LykemNiWSwUFx0cP,iv:U7YaB6/lfC2QYG7KlWYng9L+bkKKGvb1WYJnp3aumAI=,tag:vYT0g4oLA2yuVLGT4d1zHg==,type:comment]
    PODNET: ENC[AES256_GCM,data:erTdM4C2aDstjT+sXg==,iv:SjQLk76w5RvC18T20bhVoo313exTePcjythD15x/uBc=,tag:zuF94rL+nhpzKenAzmDSDg==,type:str]
    SVCNET: ENC[AES256_GCM,data:LRjBWSl+FaYlx2eGTw==,iv:e3sUuS4Jq30P/aes2H78TNg2LItZIwNoSxEiQtud3lc=,tag:twVJGF/W+mjdVo8LIi22Uw==,type:str]
    #ENC[AES256_GCM,data:qIJwtDIgnA==,iv:1n/9S2XS1Samt7x+HscmTv5xDdaVLf5M5texgS8lNN0=,tag:Bl0TBfHaZizCOQnHfn8R1w==,type:comment]
    NGINX_INTERNAL_IP: ENC[AES256_GCM,data:U7mIQ9IQezAHvYKL1g==,iv:YUyYmesLZO18SvZUkGQuumiOCGfbtkskJHebNqAua0g=,tag:lSNeSOb3onagIkuWm0co4g==,type:str]
    NGINX_EXTERNAL_IP: ENC[AES256_GCM,data:P+CHD4yjiFfm+vmJTQ==,iv:ZKwVTFeLnFPsVYICyowYTUuxb3DSSMlXRXQRk1rJiSg=,tag:cmXqn069cdPMGw/KWgQaBg==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:zMg1MVkwTgGfJk3glg==,iv:EgIRGjc7TiQLTkEZ84ykIVlDRuaVQyvtRQaHJqx3ALI=,tag:wOpDMgi9Kc6xYQ5OUgp6dg==,type:str]
    DASHBOARD_IP: ENC[AES256_GCM,data:1WElKMK+2Lkt+3y5ag==,iv:I8tS+GBskayi45Lxv4HtsBbtNQdpPvdIq8PaGSworRI=,tag:i8zhuUB6HngnnZ93cWp6uw==,type:str]
    #
    #ENC[AES256_GCM,data:HNwJh3El7A==,iv:rIj5oCSv7YiuWNudtMp0xxTidu9DfcM+QVGd4GXHyw8=,tag:AKlHRGD+vZrT2ROWX0gBSg==,type:comment]
    DOMAIN_0: ENC[AES256_GCM,data:jONPmtA+a10B1QB8G+i13Yis,iv:SbKknWAs9PQPlEmjPElB+l1Vu2BQwk3WsUmIFu1X+g8=,tag:FMhQ/GtGEtfxMlKh3is58Q==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:NDqAef1CL4amomD1yrtvlaZ0,iv:x3O4nGV21iCOI7W96I8dQw8mhe05M5xw5Pkagg538bo=,tag:ujJhI0EtMNzl3qihmMKeFA==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:m7Rboh5qtQjoAkEAFd/O3Xrzy3zXAT8JVeip7Y97gD/VGs7AwOJgwg==,iv:ngoqgv6iOUBvDOD39iV+qe+4XitqjXcmReruafT5g/I=,tag:ccpGXpVZ1ytfRe5S8CHelA==,type:str]
    DOMAIN_0_CLOUDFLARE_ZONE_ID: ENC[AES256_GCM,data:iRAFNAFE5+l90XRS+dzLeeiu4hdvSC/OYCMTypQckpM=,iv:k7VvhnL4r3wdfNvzBlWAQBaRW4XKw90u4CZhmZ/ttQs=,tag:1SeQoK7b2r0t2Z/rqb+sag==,type:str]
    #ENC[AES256_GCM,data:IJyG3L2lpQYfRRCEc4Llp5aX9s66XNBR0RESCLufOqvtDXoCItvWsXm5WJWPEOZ86RJPKtbv1zI=,iv:+/pozR+zVQqYOqoM78hjBU2mCPPvwVFMBwevW3EPG5A=,tag:F18tr5yiSSBSObuvMtockA==,type:comment]
    #ENC[AES256_GCM,data:gb3eG65PWpM+790pwCPPCcHEq+S2CIjp9g==,iv:IHgyyM2wMU43dqtwdXoZJAbcWVJBiV+VPyvoVafP7ZU=,tag:cHppmiWH7ZN4SpyJ9UYGhA==,type:comment]
    #ENC[AES256_GCM,data:l6hyQprGE1JjglqSLTu8cc7lvuQ+jmjtzSHBnQ0I5mukir2eazsyQWldZATH4dRXbY0WlH8l6jALu9Djsjc2wVm7clG65jlGIZD0mqI=,iv:JOxN0UEJ+iZgRSfrmkwqb9yQZAhWAOE8Is+tHQE4Niw=,tag:gda95/JE/bsdiFI/IoRP7w==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:2Q0+fRgpSTZUH12t3OmfZux5eG33PAlUzosb4EeFaU0kKAOdRT7C,iv:6sqCiDUUyuvVSYIPY0NGkks+y1AOkSFlHPr1CgZ84RI=,tag:W5TYzXeROCt57hZ66EDaWg==,type:str]
    #ENC[AES256_GCM,data:bafkEZjWcxMxc6MzEP+C4mbCR03vz0SAqSjEEqkddSJ3Pce6MxD6gR+PHLvvb6816yhmjHE4OCPykiNgdWV3/d6NlKrogoQ=,iv:wBRegBKTTlY3Ab8bNNqEAoJj3bFA93Ka3uLt5ry+E0o=,tag:icqYSlKTy9YdwX+caCC+oQ==,type:comment]
    #ENC[AES256_GCM,data:eVTJcDNYxIXInPMEjzdR1Mt/U2yPy3/xVRAzcCgQhMDAVNWR6AN/Hr5nHsjfVv+8iLUrbDDV,iv:oRf2La+0p7LHD6U2araFzVp9dnoTwcGYEXMkE1XMGrg=,tag:tDuURJt6lNKT/84jRmVfxw==,type:comment]
    DOCKERHUB_USER: ENC[AES256_GCM,data:ARCr5OMC8KAHWFjy,iv:AqTE3vu34WyPPt/QrHI5/ystWjSAFxM649Svl1yCBlU=,tag:Xh+LY1o66udDNt9v6tAh3A==,type:str]
    DOCKERHUB_PASSWORD: ENC[AES256_GCM,data:B7F2CZuj/F0lTimD+Rg=,iv:VzafisrnUVcbzwY1j5IvoYjCLAFGZoYeRzQPZsTS7Wg=,tag:h3pajD2AiGw0QSz8JKErIw==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:vMOpvQ==,iv:vVQXKfhL0gmmOEb2Im6Ex3jMTQ0peRwLxkPkyf+i6vs=,tag:dalHah5J+BI7Cimosjs6hw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGcHlCTUYySHE4VFQxdTI0
            cGZzOFhlRyttRmZtVmV3VG9nL0hFenhHWGdJCk1heldUdGx3ZnJ1cjdDc0E5bStB
            bGxSemZtTTRqbTh1aFlDK2NBLzAveTQKLS0tIDV5STd5T0hQQUJ2Ui91RWZiWlZU
            N0cxZFBrQzE4Tm1ZK1VIRWxaTGFGUDAKbjTwXyayejMw472uLuDnSXrzxpHxEqtu
            J5+w9avlpCQ9+GdNta+oA6F+QML82YLrAKTaleVQ+8o8AmMwnnEdyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T00:03:34Z"
    mac: ENC[AES256_GCM,data:yC8l8W2Cq9KvbXNI0lNYBC5j7FGEm6ejoUzbrdVhT7mFGTvvneQdbs5rQZ6VheYFqy6qYUubMy+GrM8JYlVo6It7QkifTcisiA79FkDh02wQtRV45q8xdKK4ol97T8pc1xPkkJZ2R3BKAaeyHLCzf1Obd/1QXNhSLK97wm8HbiA=,iv:Fgv/X386H3uwABMtFK09qp7Mbkz2JHnOS8hEpuV04Ro=,tag:q7e4UKQayPou+OtcZ1iSJA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
