apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:Md2j097kqMphMMZx1NRH8HMIBh1iTaHDsTKJ1r0jla7pwe6QREXyAVVg8Mp3Nwe3EPEfwTQNZSDUa9AhyE1unO8=,iv:athGCVMfnBnlIkw9nbrRBgryCEgEBahFm98bxCp3Ht0=,tag:+BF4SeA8YfpKCYbc+Q7a7g==,type:comment]
    #ENC[AES256_GCM,data:cySc78QIuuiLixF6HD9W47MWhd4C0cOS2b1SP743doK+cY+GonX1F76zD7U=,iv:FJj+FIpTh22u2CUFKlcMWHuuXAHgGJGoydidVmRmiBg=,tag:PyHCTX1/eu3HSSqKPqJUQA==,type:comment]
    VIP: ENC[AES256_GCM,data:Uv4Aooxw5u8iLH3g,iv:0+GJOdyyja73mVH1sHlpS3dL+SDNhvgV59qi/nhHBeU=,tag:6hrEokDFPVhhGhECKwYdog==,type:str]
    #ENC[AES256_GCM,data:SB8xwN0hGztERPiYNVgvB7hweN03yJyeVH5N,iv:D3lAVsHh6bbJkZVSI/A3VhdRTjbOqoH+vGx4WaB5B8U=,tag:MLFqyzNBJJ/kxwkqfkax9g==,type:comment]
    #ENC[AES256_GCM,data:kLDtAMEN1bYY6es5urXC96NyR30SE3yHVdp+KDX+vZFeDhPBOG2uJ00Q7znZ97QN08i0YdMWpJqs8/eOs00KQXhspHHYMQ8sfWS+WUPb9BhKqEYi9wcKPBw=,iv:yJRoz9D1s2LbfOV1t9awqvq9qdtEX6emgPUQ6Jr0gXE=,tag:ORwSt36OvlCGiy8dfxerzg==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:1KlcpaDfRIwCggPq,iv:nsdpyNKzSgUp0D1Scl+OSCgWxJsCjxo2LXJ6nL6Dnk4=,tag:AEwhZkChdCj6w4NRLNK5tA==,type:str]
    #ENC[AES256_GCM,data:NQ/zgMPV/VyJJPm5zptBshG1bQykP1bbz8cIpxkD11W3eg==,iv:Ucfif3PhOYolOlt5quFZpWnDqQx9XEeK8JkAbTAD7q8=,tag:YiyU9hB6Ofv19XTCATQtGw==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:G2EzyTh0DcKvUFk=,iv:Z7fBqWOHkC8EWfxg+dO8gpvtO/XNeAWU+JuVFJEjipU=,tag:GpHwggGuDj33Rq67QOLG8A==,type:str]
    #ENC[AES256_GCM,data:sD8878HzJDctD07Zwn4dJJg/gQrd1ZEz1sph0LDRWGlsve1WT+q43tCV4amaW+8=,iv:2ePAJgdtC/JAIaFNW5jOjkbyoboS0fECFgHLjNs4tH0=,tag:D7EEgm3On+hDCodrCQ4mzA==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:X2T8iFIE9wVUkNarrRDZGeOdpfuCALs7ne64,iv:ZKn40hoa9KM1gv7DtdiAu18+4LmJe6XVcxvB7lOXrOI=,tag:SeLOicMQ6ORnAAIyR8Oi2Q==,type:str]
    #ENC[AES256_GCM,data:rtsvdibUN7flYVka,iv:xJODKYRSmug1kERzZq+V130M3XaPiXZ0FD7QTpYXnVI=,tag:VR+nLKgxZ5GsJHwW6ZISNg==,type:comment]
    PODNET: ENC[AES256_GCM,data:G6/iEVZgGPRnOK60/g==,iv:JQUpEykjdOXKtWh1FR8YEAFV8RdrvY+ihFbWYoT3bjk=,tag:AUwmTeZIc+U7NzOu7yFi3A==,type:str]
    SVCNET: ENC[AES256_GCM,data:VPRtdlP1YF0A8/dAUg==,iv:k+HkZcKbZ6I53FfsPfxTdh7sIbWUFGRp/i0YqTNiLFE=,tag:g+6iyMtcBrkve+1v0FH3ww==,type:str]
    #ENC[AES256_GCM,data:yd1OXaSLSQ==,iv:IsgsByq32hOFqPNECM9c6fitAkx6sRAGnYldfSH8VD0=,tag:yUa067wvIbqxuHFJHb3Qzg==,type:comment]
    NGINX_INTERNAL_IP: ENC[AES256_GCM,data:84UGYtjJJIdsz8udNA==,iv:w2vNuAH5OhksK6DODR3STPWvhkO7ZBlxMdIANkQ/I8w=,tag:XyPVKiFxuBTX9Dyxph5Cbw==,type:str]
    NGINX_EXTERNAL_IP: ENC[AES256_GCM,data:gnEXLCAHReetbspK7Q==,iv:/Gw4kgPM/UD805sB+guubZVmjfUVcXzpOgp/bE1tpc4=,tag:IbdqgqB40xBv1Dx1xDz7mA==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:mEVp52RJoHpDtCg96g==,iv:y78sLYBS3cNS6gJDx1h9cu4aPcUO5hwg95a3xnUgunM=,tag:Egw3+ht03Bas7w0TaR3+/A==,type:str]
    DASHBOARD_IP: ENC[AES256_GCM,data:mtLLgX7AFvqDRWfs4Q==,iv:01DTV0FpqOvLhce+fyDoyCqGaHPDiBRLY1YL4rpkMqc=,tag:TaVLfsyuvi0yc4DOxxACYA==,type:str]
    #
    #ENC[AES256_GCM,data:fkDJVsEBwg==,iv:FqKwH1ZYJpHnRm8Fb2ZMz6iIG0X4ZsMq3SpBcznLgIo=,tag:Yp4sv0zKlSAE1xoLR8oQ9Q==,type:comment]
    DOMAIN_0: ENC[AES256_GCM,data:DD/L5SEcvxcHPtcG8ObYMUm5,iv:oWrldeG9ff5Wg28lgEu+MlC0aPvo2LEhJ3AIXCyiCYk=,tag:4ZtV7IqJATfwA7gpT8kytA==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:BdYhWJa46qLsO6S5T5XcY4L9,iv:TFp8X/z1/50cv/k4rcN4tPvDdzBDmZdA0g3UGFt+yQ0=,tag:neHwQ15iQCuIvTroQZtXOw==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:DeYV6fYv7Kh4IKqMLd4J6ftmbjORKx9IBJS4JmXr8PJCrzxsbfI5mA==,iv:7s+IlO7SciaPzX6a7ws0B3DxrofMBZh3apPw256ngQk=,tag:hWxH65KHoAROPKiDl7SfJg==,type:str]
    DOMAIN_0_CLOUDFLARE_ZONE_ID: ENC[AES256_GCM,data:IO4LRzyhScbj6IiUMarRDPH+4ILxUPZNPWEcm4At5zk=,iv:PU24hPkRyKRfXQgwLLe690A68jJvun74bed3/5Mqk3Q=,tag:Mj/2XOQv3i9tnfDQcEOFig==,type:str]
    #ENC[AES256_GCM,data:l51MyKXL0UHaDst8ihQjRTiEaaxMJMUUcjYKZYLCkEP+CiLl8pTPB0XuVutnpFRhf5fjT+Zfw/Y=,iv:/zDHweMQiWffe7H6J6696kLfzyGTjNiA0US4ScDGmqw=,tag:G2Se36ByZZk/4ohYh7xWzQ==,type:comment]
    #ENC[AES256_GCM,data:mKU4R0wxIXol9buN+s2mHhJauTm6L2z4Zg==,iv:gvyEOFfT/TWP0YdZIy84G/g00ANqlC3fk+yzwFJBYy8=,tag:xrqOu3IQFZFOYDbId0vVAA==,type:comment]
    #ENC[AES256_GCM,data:cE/J2ZKqR9Y5DRfpFydDM6IYXaojxyzMaIiFvRb3FzfU8B6/Iy7xeSb4VPVSTB8TvyZyLim4UB532AHhw1OaRHnr4o9B6AqEbl14C2E=,iv:+aXJfdrFPd5+1EXznLbD2pCpnxfpuCnFOj6EeGV9dgU=,tag:EAqCaVDRZUlPGUpwJbnNDg==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:zdpaIDB8OtOCf6eYmM77dCgCkFQ1AKKWejyLzPSVKRR329E7z6rO,iv:LdhOPDwojEhArj67KxBUPSSFCb7Ir8TSaVZo+XLiIgI=,tag:vQUFLdIVi2S/H37mCehnVg==,type:str]
    #ENC[AES256_GCM,data:Obmpc/Wpr6gOA+Qg2pZK/tnq85ZKnnCPoS/2o1iEdbWpUyQ5npAa3e4jhBB+x7xDnB5wBKX493L+eoRzzS2ER2X4fHY9n9Q=,iv:f0sV5HIPLivYClBDDJpxECq063FDjwjAVGbXFULcAGI=,tag:NP/imraOW7bzSfMxHwcRWw==,type:comment]
    #ENC[AES256_GCM,data:F2DHmzmv8Brhvbg5B37sF1ZjOJ9otGkGC0uGnqje80sdAR02pNE8IY6RM5c8qWZUfQdOZwZ8,iv:K8ns2okkk7xL+c6gipO51C0iDyoj/Lx//IMxZQ9rSBc=,tag:+afOAyUKb+hwWi97zufh6A==,type:comment]
    DOCKERHUB_USER: ENC[AES256_GCM,data:ym/s14Y5qXUJo1qZ,iv:CoIvKtubldTaEa2ZafPb9oKGlKzqKuVVp0IerXOfrL8=,tag:bQ2kD+9AFRXA65DnAb06zw==,type:str]
    DOCKERHUB_PASSWORD: ENC[AES256_GCM,data:vaiG+nwPUB++sWC/JOw=,iv:A8qSqq9wIj62a9DCWbCcU4xOZnVytMMN6asdgud+m8o=,tag:upNhe1Usg3fCZxvHzjNDzQ==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:/MvJWA==,iv:Qk1uztBoUGI+J/a8dqbBNG57gS8dstblyJQVvgtEbBU=,tag:WtH/MuNHFMN2h4QZv9gxOQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFeDVpS1djK3h4b1dNb0sz
            YXQ4OUZBMldrKzZOSm9nU3FxVW9jbjJqaTA0CmNqTWRmdGRoK3luUS9mQi85YWR1
            ZVp1Tm5tNXZQdGs1Zk81Z1Q2UWd2a0kKLS0tIDl3b3B1RnhsTVhrS2tKSUY4cjFE
            OGdrbmhLNG5KbFV6MVc2bFJoMkdnOXcK645QTq6AdG/DOPFLrkspfRdatMSCeaPi
            4WuOgSKKwdGoht05Blgncfkktxrs21bgfTaqtvk+C2fv+BkNDLgE/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T01:57:41Z"
    mac: ENC[AES256_GCM,data:Q9tSQVSjfcVoRfcgRnRCS4as0V9+B78QQ4kCqqX0bWaxeqZdKou6cNnGOJZnRr3aiycZ7KqeQauE548Apn2AfREOzGiWRYt6UaNtFp6k4e+pMykYQ/85F8QvBcqI4+8fy3E/Oe0ALTXWe6wtXKGRA1PqA/8SQqvBIfD3KFjFDcM=,iv:r5UyMyeVlu94uARSXDzxh18yfMZIsyjjXaVjHn6Y0KY=,tag:fRNRP5OnXsStUIQQY0IRqA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
