apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:xUfHqBoFgCedfAAUT85T92ps+dlEcZeBLg1lQALMA85or08gT8nQ/GB3NhUvz27PBuDzPIctuIufgAbUjJin4qk=,iv:oiFtYyhGxa/6XBqCbFEe7t8FzmpEFNvz2yHIInjY/Xg=,tag:eQVKE64WFzOzO+B9oFFRvw==,type:comment]
    #ENC[AES256_GCM,data:+qgIfhixbV26XUFgPELjyGOrowHo2Yx4juhQrE8U7J8b8ZXcaeku5x/rJDY=,iv:ttv3ZnZ539PBhGiYut/+T7s6BQxXJRePItMj33hu6sY=,tag:nZTX9OBkVnI16OjKJFIR4Q==,type:comment]
    VIP: ENC[AES256_GCM,data:WS19DWFl5FmZYgxb,iv:uj8kBT8Z1rpu4VwKIWnJYOx062XWSPAmMjCXJtXPv34=,tag:qlzJgupHFRBsAmoklYf5UA==,type:str]
    #ENC[AES256_GCM,data:sa+weL0O6Zv+z7+eZ8V36xzw7iBR5QKGNAMt,iv:4Uj6rPWYNq4wyzwur6+80N2+GJaw/A29fbGwjvfxP2Q=,tag:j4/RiGbgukwH6GpxP1DNBw==,type:comment]
    #ENC[AES256_GCM,data:f7GMCaPoJbo9r77ATThXVPKUOrhntO9BSmkTBPViqLD1Xn4CiC0mJu1iQUJoRim4qkdnMoB9AlX0fBJnOU2ZLFK9T5mnH0MbL0VzstY/ec4+l7Hrxdb/J0w=,iv:2dkQB/gQCDUwZIJgYuGvc7IukfFojiZsPenQW0sZYIo=,tag:DN3sJwFTi4mquXxb3jbltg==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:4YmjuWiDIS/7b9c0,iv:LbrKuS12+mi6kPGjA88QJgh3vz+8rSEzT2HLrpm15mU=,tag:g9y1LC8D2cleDNMQaT6dTw==,type:str]
    #ENC[AES256_GCM,data:xJFn11JPI7s1t457tUko15/bfF+RLkMh3E1GrdO2y8wk3Q==,iv:rWZLIdyY4pePYFWSvI+GOp/42KYUwqc99rue5MOC4Vk=,tag:w7Pz8OcAc0AWBcC4Vl8joQ==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:gugZaxMbYU68lyw=,iv:6vHc+Kqc7GRfaK6naWDx+efMa9EyUVSK9+lOc6yiitk=,tag:0mA+MTPclHPhTbj+00z8Lg==,type:str]
    #ENC[AES256_GCM,data:COwvOUqurdiCfGFICyCHAQGswapnNG66XYU4/PxBgVd2Wl5JkyFb3K3rVkNvXY8=,iv:DblDJW1XoLEyOV5TdDsKkkeqw83O0i7QzBfupSFOmbA=,tag:hyAvfEWKao2HNIUFCkc0qA==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:j+GMoS0Lvb7/aLiUQcbjVJ88qDnwpWbL+BJH,iv:q2g+PEzKOLBWJu+R3d8dxEF9puvQHTEiBlJPUnHeiVU=,tag:0hhznQdWXcJ9n7kzg/Uhyw==,type:str]
    #ENC[AES256_GCM,data:ZS3SpN1he6zG82oM,iv:0sS26II5a2aM3NtZsf6hc4ZTUMSKJ1766xYc9Iw838c=,tag:ylZWMQjSc7lul1wHmzGl3g==,type:comment]
    PODNET: ENC[AES256_GCM,data:jwZGkOTFj3GCfFYJ9w==,iv:THVqVV+XrUZ9dJlXNhuGGHoWr44aNEueW0mFAsOxEpM=,tag:1PBv/N0CE56qP5bn3FkYGw==,type:str]
    SVCNET: ENC[AES256_GCM,data:zTHyF4oxJNTBZ2jKIA==,iv:OghPPEjaN4wzMQiM5gdmvfcSfZlYb6v5EWYvWskzpJ4=,tag:I6uUwocMcGg4ejKEWX3MrA==,type:str]
    #ENC[AES256_GCM,data:qAU2wjuj0A==,iv:aBmaH5uqmq95i2eRylymx6cEj+sSG78rJwtlly1v+4E=,tag:IPJ6D6YyslGyZO+s4f4NXw==,type:comment]
    NGINX_INTERNAL_IP: ENC[AES256_GCM,data:lIPR9w3wXYACXYOi9g==,iv:4fBTK86tSMSuBEbAIsHpoJRHnnNiarf7e9ld9CZUnh4=,tag:ox+EGH//kVh4dv436iYBbw==,type:str]
    NGINX_EXTERNAL_IP: ENC[AES256_GCM,data:/zVc/BbQMNfcBJR72g==,iv:vMFQ/7jgBGoLgTWe4NIvJM3lC94huK0AWfCN2P96Xrs=,tag:bUH0Im7+/HZYx0vldN8q2g==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:V+a2TjAocQrL3D8aKg==,iv:VH2zKasj2chY+EjvI6Knacn1gBFP7Ow5yMkUm1hHMkI=,tag:TavPDBPQIzdiq1qgf4yo2w==,type:str]
    DASHBOARD_IP: ENC[AES256_GCM,data:2KYrARspDa5nQasHqQ==,iv:FNWcLDQ2NU/dzHBa8dZrSoEkk3xyjvvQJWF1xVIcCSQ=,tag:IBYxIfA6JjXuBjqx3ncGQA==,type:str]
    #
    #ENC[AES256_GCM,data:5mFe5S4hmg==,iv:i4Ywb5HdzxgeHdLU4bRywlxGy3ETq5BbcL2H2nFwcTM=,tag:4qJhMVyxgJszaBBSfAvt2g==,type:comment]
    DOMAIN_0: ENC[AES256_GCM,data:KD5aymb0Yf7ASjkOWPGLYL8d,iv:6XwAcYOtKoQ9ZwdPDGdLv5eeqd5dfsMFCS7XN9FmkJk=,tag:05Xoph9yY5PJxYMEJcI7gg==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:ivoY7NYQr8KLsGwGA0soe0ER,iv:DTaUlar9d5yhA108uNM6JR4uCPcdyXlNvSxSh92WtZE=,tag:DmkghowrpPmnvUIY4jglNA==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:b4iZp7zW5kfzWQiQrciY9KKO4Ih1SQZAOAt2vl/6CrkL8jEcAWbDmA==,iv:d03RJsmg/gkKLihyglh7SkPszARIf1zrHSHfC9QQgWo=,tag:EY53F+LFYtwPNPdGOvKs7w==,type:str]
    DOMAIN_0_CLOUDFLARE_ZONE_ID: ENC[AES256_GCM,data:nvUGIfRP176Qv6CxvSWAAOzX0euMVibe5lUAYETKswA=,iv:E+JjZ8BUFV296sqx7PzWQZ5AqK9WcLlwsBe1L7fx0zI=,tag:d7lRX/9tnEQ+3mjg1SqWCA==,type:str]
    #ENC[AES256_GCM,data:bxLINxILSj/HZ0lM1cw35e3q01Pk5SY7iyu4jTLHJRGj77KxboiwBvZIHgevNXABf1sT2VSVj74=,iv:kpPcx8K3AzgOXoeFRtIGw59vVyqcPy7d76dzzoaOLco=,tag:L/w8EZbscr9Y/CsvgveVzQ==,type:comment]
    #ENC[AES256_GCM,data:PpvV1LajRpUjy71seHzThMsuDmu4a7n7kg==,iv:OFsPmuvOl7kmnFZAzOIm89Yb8W3WF/qnc0QRMIcWrbA=,tag:5uPVRdo3gumcdn6oE/cVkw==,type:comment]
    #ENC[AES256_GCM,data:Z0ShLjZM8wOhbL/1eJoXS7RP8K7S9kNCeVCmCWVM+gCuhUyRwmNcZCGZLg/2Ykk4Ls+GuP7QayGAjLr60tUnKv4iEZTq3N2x32IusRs=,iv:6SsbaEnqX0/r9nB+A6r1QaSLrxfi3W2O5NEYLc6As30=,tag:M0IPqMT7GJkVt5kdZctXsA==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:8qpGHrWUnKOmVlUWB7wR/4gxY1nqEQ2Lz1SCd8yK4t7zfO1xERh0,iv:EIm2wbfH9kZqk8HPCK+ykrb7YL6o5LwbJfVXWiltYQY=,tag:tfBzRXxiuhOc7fq+xukzvA==,type:str]
    #ENC[AES256_GCM,data:9EcdkHz8gVeeTPMDCzspHoN5aD0apoN5jNxdHL10jEBMFbqoz1JD47zE1bPCobsYyogBrSN0VupbZ8e23VDM9Sn3zK2BpjQ=,iv:T4vHHuJjd4msdrhIBQ3Ki+Y5TiOUbObc/Ydog9uA3YU=,tag:XQNibg7Ico4UjdpX7CLasA==,type:comment]
    #ENC[AES256_GCM,data:qvjk47o2UkIuT7wAnuC3RlFqOMZR5mL2GA+T5jwGvqvtHBefB9NfT+HJJrt2bc1Dehv3cBAv,iv:xvHHhVGqB8BNHEJF1K+1+WHZFEfPxOkcWwbgZVx5BcA=,tag:+iiuJVTRNu/TOktiYF6JmA==,type:comment]
    DOCKERHUB_USER: ENC[AES256_GCM,data:t7wu/unamZENxNgG,iv:JAQ3oDmYVY9YU3ssBjmnAv1b/caUA95THIHzFxXRWB4=,tag:URfpMlKx6gH61cTNyvBY+w==,type:str]
    DOCKERHUB_PASSWORD: ENC[AES256_GCM,data:tPHuq7FkYqIm7y9VyVQ=,iv:J4h0s7d3KqmAQrgnJkt88QQs/YLjw2vgqwgOYnPKqmk=,tag:RZV7pajA1ay5sKbi32Re4w==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:znIrew==,iv:JeiSL+me8gz9Ziy8kSTI3rEeiGsQROlLosS/hQTgMB8=,tag:tuuNn+rf0jX/Ja1vfMBbyQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvQ1orb29GV2k4VzRUazF5
            REhtUDkwYmhYaC9hR0JVSjVxOHp4ZGc2N3dnCm1LeklXNlRMMGFHNXNBOTVraVV2
            ek5ub3hNbWpocXg5b3g0dTlISmpMcTgKLS0tIDZ6RXVmOGwrRHBxVFV0MVVHYWd2
            aXUvS29SOW9qVkhsNFJ2N29HMVdZZzgK96lqFadLXkEU5cs4SQlWQeoRCb40wjqU
            +GUTGJ/XpBw3ua4U4VSiKtJgysJkXbybBB1+EKZ1DKW6vSruANEamg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T03:58:19Z"
    mac: ENC[AES256_GCM,data:hCgAK0WrMN/PW20hOydae9EvUkuUlyBC8ewX5YvNmdW4ygHw69V3zCAFTsOyyl/jPYJNeETqkiMRZN8xWQPssPfBbFAUjZrjk3Q5QxBogyiFvw6ZXljD2x4G+C2NV83urtes8HxmgZM2mhBn0usRHw09Uj0c/tBLB0ig0awiWkY=,iv:DtcxvedyQcqa4YIlF7EkkA/CMu6lDTG/pVpO16dlwW0=,tag:2FZ1PPx3O1bwzGAt8LkjpQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
