apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:WM58jLWpexHFa6cQL+R0ZC5KdjRPC5hAgGWm25NbLd4nPt/IBaIhr6at+83v5hxmOML2PXsQOML4IgGWZ50DuRY=,iv:ThVIbYDv4j3adX5E8iiFENea2cZk0Toh4pguqJaGnNE=,tag:ZEKlcF5UbgBA+Jowwb/vRw==,type:comment]
    #ENC[AES256_GCM,data:5Ofa6B0WrJikmJOpwHQt35q+VRwoTktpj+DuWUU0DjMVPK6QjrQrA8cwWe0=,iv:1Edyeen5QVhc9h2DxaxxrmuK9yU3XbSzQxz29YwGvvo=,tag:hJRczE8teQNTqooJgu2nKw==,type:comment]
    VIP: ENC[AES256_GCM,data:hpWFDB+Sf2kwpElj,iv:H3T6SEqR7S78BLGzgjBLz+fwjrghQFUxqoPzHdDDoT4=,tag:09sL/qGbYWj6nRQndTyatQ==,type:str]
    #ENC[AES256_GCM,data:AW9vpu9F4+zeYIZnFTOT7KE3FAkhUTgZimWk,iv:tDScQjRmlhvDqyJFX9/2BpqEzMnmOdIT/tjKiPQuU1c=,tag:Fd5si6rGcM0Da+Hanh3YNA==,type:comment]
    #ENC[AES256_GCM,data:I0Jb3P+ZEOedIgewff/kf6oHsAXfvfbfPixJIMpjwR30DwM78ZTkB0KqlRksmIGUE6qpiQrHbT4Iy5GIsd/HZYYkAgCjQmEWGGoJl2W6eStw1pjJlU/qxBE=,iv:Bb/WUSeJyPoPGfYBzcA5vOlHMdgrNE+MeZ0cl63kzCI=,tag:016BP4NEhwuLa/Pb/aZYKQ==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:eAk9msIdn2dUGou3,iv:bQK1vmmQnexcbnU4ojb7MeuHb5UwJylcu2ji5DsVqe8=,tag:N//lcpIzik6578fEyBpI4Q==,type:str]
    #ENC[AES256_GCM,data:z2f4Fmo2Lxt2CFYLPxvb21sW498+UiGvJMVQqMcL8OPtdw==,iv:9PRir6AY1OPHE8znT92f8rZkQA9l+w8daVOc4ZeR5bM=,tag:z3Xpy72V/kx8AlcH2aMUBA==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:9alrBkrIL+Eoq/w=,iv:GS1tEXCE2xj7zKcaUZ3/ywBX8k4wu9xSsnuB/69Ue7w=,tag:4tJfmhxknFlIaEh4P3iGaA==,type:str]
    #ENC[AES256_GCM,data:rvJPjCC3HwRUieijGdII9NewMn3f944amy3hHP9Zmg//mX/tWHOKQvZVIH1SsWY=,iv:EBaSfjj0nXxDR4do8ioLQRnaW793ixp3IppDa/TN9Gw=,tag:c/qh/oQ9aP3F542iYzNZQg==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:qMgK+Nwm+J9FE6mtXeFaEna/2MU+uh/ZSIQr,iv:rA2W6f+PBAAzsFsUJhqOcWnx0AyUjq/xtwTlG8+0Qmw=,tag:1r2gdoKH7XvaVdEU/wRvdw==,type:str]
    #ENC[AES256_GCM,data:dZFYV6Wqr6HK4Iz1,iv:ZnJYLl2534FdKAAh1DLSEdObRNOrYlAMgLketvGs8QI=,tag:pMi0U0eYi2jhC4Oy6C2WaQ==,type:comment]
    PODNET: ENC[AES256_GCM,data:pAmwPaAk7WhAWrE10A==,iv:f5hhAOV1fvgh4rYLcHawCVKfPLCrKBAljUDSo4XBO98=,tag:ALCSQNAbOn+8OQ9Lhaek5w==,type:str]
    SVCNET: ENC[AES256_GCM,data:J+DNQAsudcBMKAs1EA==,iv:Sm19Vi+nv3RPuuVWrbaNaYwCx/+muOVhdAmcz5yOC+Y=,tag:8VDXZYwbfrZyS/80G1m8Ag==,type:str]
    #ENC[AES256_GCM,data:aGTBipsLIQ==,iv:/V3f/KDK70e/3usPw3lXM7gsmCvAGcOuXbdj6GxyzuI=,tag:YzLsaRTPiY+oOrwHQkoqsg==,type:comment]
    NGINX_INTERNAL_IP: ENC[AES256_GCM,data:dy0Q8+ad0w5ZIv7k1Q==,iv:KVWmcY3VaO1yILIgDoG1pJdpBCLXS6eM3ZTTNsHXsDI=,tag:fXPzAsjy+dOmPcukJBJq8g==,type:str]
    NGINX_EXTERNAL_IP: ENC[AES256_GCM,data:UF1TQpggx+k3PVLicw==,iv:YdPdnuoWlsopZ8FtRGiPF7Da/f9PCki5LrybB8HI5PY=,tag:RliRxMNNGX4b29FcPrSgkg==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:Vf46IvtMwKzJifEDXQ==,iv:UYIneClO3fbFrupw2pU0ejFVzNmjRZaacHfHFP+SuSw=,tag:WpPye0+/7SH2JDanrQM79A==,type:str]
    DASHBOARD_IP: ENC[AES256_GCM,data:Qm8C9cVTkKGd1ufrOw==,iv:HyDvL6v86EgX7oZfiDLtU58u4QyukSXb3tzgMxhPW5Q=,tag:u4fkfRJniTCmCRP8vHDc1g==,type:str]
    #
    #ENC[AES256_GCM,data:gttcMiK9/g==,iv:mZYotMYGOvlL2apFG1GnkYmeFIx9fRePLCTJ8A9CoDo=,tag:UaszPfhFcOeF92dnfl88TA==,type:comment]
    DOMAIN_0: ENC[AES256_GCM,data:wcUWcSAlr1RcoLjol1XpIak0,iv:BWCehagXEStPsNArun6tXYqIxgDKkOHw0aArJsu5rLw=,tag:dQsVLMmOaPF/ZrxRYlsFIA==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:ykOaRkf6L65vtMfpyVBIEE6s,iv:cb16oqDBQqo8gYiJorMZ2nvLKAXecReO1jN+MXacJjk=,tag:L64BOxF1Zdp45Nc96qUMxQ==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:4RiCvUFltaQcOjCm8/XL5vQASLXixGGJb8OiSG5avtXtcW8+ZyIV2g==,iv:gR2WcEpZLFRPhUXSbv7kBeFb8giPGyM7dQlAnj9RRvE=,tag:ykXFxTgSYSrw1wXgw/1wFw==,type:str]
    DOMAIN_0_CLOUDFLARE_ZONE_ID: ENC[AES256_GCM,data:JQhvlKE6qw/6l1nB46qlEGKGoc+reINvRdujKmzNEgw=,iv:W3KDUNhfgeqqI73fFhBeGSNsb3TnoGUQAok6aJz9gDY=,tag:0M651dGLE79e1mBPA/iczQ==,type:str]
    #ENC[AES256_GCM,data:kvpX+iyujYdZRFL0q4plSg6Cfh1Pej5uQmoARnzIA4Hn/yEnfumljrdwMHYjgEhp2EObSNMZNcU=,iv:XdCiGRLbPuKDDLchLP4K/bvaakjE8wBcsUkG/11p0Uk=,tag:R6cL/QEeAlrTxA4veKMgNw==,type:comment]
    #ENC[AES256_GCM,data:yfkEhY8P6pkFIA3BQy443tFup9XpRXRjVw==,iv:nNpnTLn9VjKULI5v7f0Rnnt5km96APeX5uG7DcMl41Q=,tag:mSyb2BbCg7A9Fu1/L55piQ==,type:comment]
    #ENC[AES256_GCM,data:7Qgw7Hvc5LstUTR0NXuAGytcyptjKEfSKsKNNjNHwGqwx0ZvtOWttJ6SMM2GnJE0qX81ZDCZWy9rNJ5/9KedLawjWpwuEj+RhkZKKUA=,iv:PDON3OVlXmvgmzS7tD3/HT5+2nOavpa4akcxryPYzVI=,tag:ABQRCvAIu9p1hfSPa28D5A==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:qf6cvww31d3lAkJLPmI9ZemE92QgcUNtm4EHJVz1QxSbS4/oPR3R,iv:LnJfXGD85lSXcSlxj0eAyx//sV+gbXMTpPIrYRjfdl8=,tag:W0RjLOtgvoN179msX4QYGg==,type:str]
    #ENC[AES256_GCM,data:UhNX0Q4ivmOq/XYZxB81wtC3e7cTGYuS4eMpSAMyAV02+teblrxGS3Je5qfsYSy+ID9AC0OeqaEKGqR+0uvRfh8qR7Z6eVY=,iv:yt7h/bqVs/csXJDBoPOY+7dhON5RVhl+vTTRLAB+JNg=,tag:44gZLgd1Ss8++4JTcq+rYw==,type:comment]
    #ENC[AES256_GCM,data:tOvPXJ1D+Y8qXltVl1pFwu8eFthrGH/t+OJJ7Onyjby6IaQSXIW94IZ17QVJktCuL1o+/g7+,iv:1cPyTklbCkAJgntPMDu1zle9j9gbaooVSxPOXhdi1Uc=,tag:nn+fvTqDurO9Ok00113w4w==,type:comment]
    DOCKERHUB_USER: ENC[AES256_GCM,data:JGwkQo0zJ8Pfjq5M,iv:vgi8aEhC7UixCyc8/XUoPehHJkn+82NSHlUWEHWKH40=,tag:JaCKdjXWAD+0Fe9G5cpNQQ==,type:str]
    DOCKERHUB_PASSWORD: ENC[AES256_GCM,data:0zSDdrHr+IYrSxdSvlQ=,iv:gviYsajTzGTaMz67mWifhzoLqKPIq3mtcUwu64AGxds=,tag:KIjfoyiM4BoYniQJ9+lx5w==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:6H/uQA==,iv:Gd+kN4temEbnY9lnx8Gb/oyS/ALrgWxB3v6drGHVH+k=,tag:WhTvo/p3vGWv/T5mRMalWg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBROWxPYXRYOHBzYnB4S24x
            VUtiR0IzWXZrNVZUZm1hY2t6bm0rRnJiWGkwCjJyZWdjYmpTOStaK0E2YTFOK0Ix
            Ui8rZGRJSEpYRjhBRkU2Vit1WjlGMUkKLS0tIE9FclhaZUlGMW5YYzE4WmdGbSs4
            S3JldEtPcCtaNVRYL05TUTFGd1pTQWMKsE8tVD9InXaOC5Yqb2chXGMyzuNKHtVd
            cVDiVtUs2KloagnNfMUyTuSJAek9l8o6mdyaO+Q3YNm6jCQk53c1Mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T01:40:52Z"
    mac: ENC[AES256_GCM,data:Os3IqgTR3HTDImg1R2jSCC+QZcRgGh2wa397srWHTPcT+82BNM8U5F73520/WnVB/QN/TOhKB2tvOORn0ruu9m+49N4h6cmB9K7iqmIMvphDAsFtvR2AmiOOMuFEAHRduh9No4uRgN6LyOXO1xEkY31bbUhk+04YQbZBAXv5UIE=,iv:8IvYv0DP+zXslfhjNhCUdp3JdUAQqz+2WfpSQgH+/Qw=,tag:Ue9E92aE9tkbtPU1a9nu9w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
