apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:C343yeemgAY8m+P8vB2SvuWlQPkoD+nBuuPr5d9rXDox3+RfiEYoNckHT7ipY2u7cciakVpR0MiD1SQN2WuUBEo=,iv:cVpxr0j3n+G3wiL26Mm5Cs6buMXU8oF2nL8fC1dIoYs=,tag:O+c9EuMrXP9MwbNNEAQ+qw==,type:comment]
    #ENC[AES256_GCM,data:AakLl6BpBhWQ2zCx4bbl5+LhpXCIcKr1EPvH6lJ+JNndJO6LQ+ofbZR7qzs=,iv:29CPP7i+kxptvJEgcltWb5Xe9NwbxqkdOQ2cEE1PPbc=,tag:DHNby+yzxpQ0Bwt1d+VVIw==,type:comment]
    VIP: ENC[AES256_GCM,data:49Ok6taoAgiZbGA9,iv:a7GUs/HKCs8eLmkbPaBjzP5SLdQBXcdFJ3Zxv73yTag=,tag:Xo2SqtAlKSoMRdweNASUpg==,type:str]
    #ENC[AES256_GCM,data:cfcXIN30I4BFcSSsXVy3VNvSpkkeok/WA/D/,iv:qw6qcxfNyAZ5vijShM8xkONuSDG6iFq/y22ZaV9R4tg=,tag:jknSOx9oFH6AGPD/95Xtcw==,type:comment]
    #ENC[AES256_GCM,data:ZzvDc1veiXpWzXLwiBeIjT0bg+Qmwok4CKtD9OTF4xMN8jFyDNBEoVify0COepbCR6ZnXoCipJxilbEBeu/XgVo07oPOL62oR0f/KIyQ2Myc3zasU2MTXGg=,iv:HArXm2k+xPeiJOlYceY2Oop3Y7k6k9dcw8Gry6OXh64=,tag:5RohyraRx2lHH1ggKcadsQ==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:N0En6nz8AA1JnUYQ,iv:e3ZtmXg3ZKVrkEy3jo4NMpbF0n9/F4JSZssx9CH5z1s=,tag:1jG20nH6VwT14y1WJcUX6Q==,type:str]
    #ENC[AES256_GCM,data:LGOiEi46glb7tcvjzeJLIeAQVeOykBKOv8ra14lA8AgeJw==,iv:Rh/YazyQREO81jP9+8VVLmEv+FraUR0oii342dr8mJ4=,tag:iuQrWAL8Y1fmuQyqabSkuQ==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:UkWOIOezSXj5WRs=,iv:Lk+liXpIBW05OQuqH8Lb5lZy5TL84wFgB5DRh9GL9DI=,tag:MCxAp43nq/8AQrVZ8o6NHw==,type:str]
    #ENC[AES256_GCM,data:FOtjAVkybMqcRcbVq/tw5ypgPCqjbjxEHwPsI6BBJV1HP0YQ2SiqStdIcR8SqIY=,iv:kzY2ImmqA3boiEDEAfn3ZGhqTXY/sHdw4IIisgfjWDA=,tag:HBF15LflUlO8eQsADNi0Og==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:OvW7OFKPYP/ERCDdnVPow5rPF7yhNb0EffoJ,iv:c+XKVGedxHMjPXQHlSN9DTq5kvZZjhNxZdcV+kKl+PQ=,tag:gUJX70Pkh8YXGgfgfynhlg==,type:str]
    #ENC[AES256_GCM,data:o3yZXSI4rV9AOsvP,iv:HZIX9nNMfyoE7c6WhInBd6NZLnA8lSOfaVI3gHPVpjg=,tag:zpckOJk266IeApOEWsCcdg==,type:comment]
    PODNET: ENC[AES256_GCM,data:OYyjeHust9jYoIm4RA==,iv:KlsGo5rhqUnCYn7kyOccAgV+BylQdgb4bIIL5xyLPc0=,tag:8dKnwvbQjUoXwzTzPn5EkA==,type:str]
    SVCNET: ENC[AES256_GCM,data:zphRtMdOFpQCXAEYmQ==,iv:l4fdg9f1OR4QhGp7004OrLQTxPorrtWPHPkrHv83mIw=,tag:Wa/w4ZRNT8TUugYzMH9N6g==,type:str]
    #ENC[AES256_GCM,data:tkGDlK4ccw==,iv:vsfX7tV3KAQuWwVWKJ2fQcjLTPwqtX6NU/suNyBTpXs=,tag:bybBPVTB+3qVP0eWjm6Cow==,type:comment]
    NGINX_INTERNAL_IP: ENC[AES256_GCM,data:gZKdnXOCT3dyBWHqLw==,iv:JJWwyi4GUScqTv0H+DwdkVcs7pXn5ozRR07/nBf5z3E=,tag:7NBuqHikx7gmpk92KfbTSA==,type:str]
    NGINX_EXTERNAL_IP: ENC[AES256_GCM,data:gxLBmn2S5Dyln1X78g==,iv:FMMjIcsKYs7SNy9g9ystykG5DdevPGQqOItKtnkqrOc=,tag:h23O+Lp73drSdjp4+Zdgiw==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:Tbx7F15jAL8cSZk2Jw==,iv:+BVjXpNM/NwdFxM51h6YO76HCwWecYljKu76Ixkm6AU=,tag:zZ0s/HN2vb7kRuRbrgcyUA==,type:str]
    DASHBOARD_IP: ENC[AES256_GCM,data:Z+8wHIgqCwOPp/Hi2g==,iv:UT8+x2aN3GPwf8PxX6Ep0MatL8ukrkDQIL9JSohFJGU=,tag:8kUa/Yio/7+joeeG/tk1Ew==,type:str]
    #
    #ENC[AES256_GCM,data:PI9RZLBT7g==,iv:WVya7gL1NIdRwTL53nAqRoPPcZ5My/EDA/gVfjz+KwU=,tag:Q32bBQkCA0ythz0LRm4BaA==,type:comment]
    DOMAIN_0: ENC[AES256_GCM,data:qM9nDU8QbVvZpfOd2GpjFzfJ,iv:bRtAtsNtOhxJEenn/Q8+HaZQ1D5gfg5dzUjYn5M8QXM=,tag:nA8sBWuz8x8hu6/BdUBAJg==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:1gSd2hQ4yxJZrYbEVjV5fAIF,iv:0eqQYAXDsoi/3McVKMBLzi1kdjYI+j3UT98FoXuBHMA=,tag:xoTrYtpIaFY143FUIQUfGA==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:7BcTn8SuKuEqZ/4hUJIHzU2An4wI3OM3MWnFDLnbmuNWMNrFP2thWQ==,iv:DWWMJonZdHgMJ9pU4E0BHN7Pwg2SSgMNhNqHz2bR3ZY=,tag:7hIbrkqs0yIgmKxFiFvDlg==,type:str]
    DOMAIN_0_CLOUDFLARE_ZONE_ID: ENC[AES256_GCM,data:g9Z7iW+zZFPjcIxAlnq97NFNc+PMu4ntTwI2WRB3+qs=,iv:EjmtlMsdy9bsTrCOjXtAt+l6XETbKvuQOM8P0b3pUCs=,tag:94JFlyw8lErPniE9+AiCfg==,type:str]
    #ENC[AES256_GCM,data:whFadvEhO8yHwcJRXq+DbsHUrdvwD3j1bwgdOsRL/Nm3/AtSV3LIIwLAFCR54mxlACc/bBHoe5w=,iv:xI/X3hhhLVQLCWGb5bgPedETB/H6RwOqqGJx2iNaJnU=,tag:GVbi084oSThKLjOcLkPH6A==,type:comment]
    #ENC[AES256_GCM,data:VK3F8OGoZ1ZWOQejIVymMT2/lf/5400PUQ==,iv:nYOa1gTczqPPpgY4m4+045c/okOtE5yw1mAXeSr4c7c=,tag:8hK5jdo9/Wx1el8VDEKawQ==,type:comment]
    #ENC[AES256_GCM,data:ZNL/W4Wyc3V+CV4VoCLTPQw87Cx7phYUwNyxNHsCGh7cSHoku5bldAznk2TPFxMSTV8UMlb9fHpQOKNG00mhmtFpLzV6zKN5gXXT5tU=,iv:ty4/1FiJGdi0r2jXptfHEkepBwYxCvz3M7jy3iI2ZdQ=,tag:fJVLGxf1uJHlooZfuLchdg==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:IFA359Z0DUSvPk3hbsaQJv4CF31XMjk4roOQ5Hm02PZ2Z0hDIoOS,iv:PyC0K4gC1utQBvpxzD475zYJ1mTkiAyhdp+72WqGOVU=,tag:HQZX82fXDL/wCZRy686JKg==,type:str]
    #ENC[AES256_GCM,data:e5r04yXg7UYDVAOb2i//L+8KZviGjpiSWlDXocHHIdQpOmpx/k1npXQ0bTwqcv/to17JNph6BLlK+3V0cvIDeUTYUtdeoro=,iv:/tj2VtWa5ABqW7EcCliWrq6YP0lyPwp7oFzKr1LTWe0=,tag:oRJsdyLhJGSGu/jIvefvtg==,type:comment]
    #ENC[AES256_GCM,data:t2irmsw+0mbjBh9lRyQLF2KfIPnZ1FT85Q7cOTq7yUZrPCwCHojmu94EIiuDkH4coJt4w9zy,iv:iIOfUQAVHv/Ee/y8U6geKUwcxWZ/BO97Y0MwXN7h0Ug=,tag:BTqruMIObJyHjaIwCq4fbw==,type:comment]
    DOCKERHUB_USER: ENC[AES256_GCM,data:l7+QZCIguEx0xMKU,iv:PE3MO+w9Gz9RrYiLnNCefs6IdG7OGMRMdDqwSWvGrZc=,tag:qzbEcpXAkmzUOZxvKo9OCg==,type:str]
    DOCKERHUB_PASSWORD: ENC[AES256_GCM,data:PgTshgYuCV6VifBZSXg=,iv:Q3HnzCJUfV7zd/SM6wXpOupd3SVr/eGL0wD3vSGx1dU=,tag:J0079A9+/mtkI8PWIGkd8Q==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:1N324A==,iv:gbQ3Rs/PHIu8FMzmmtCOQKJWI/uEFA/n8Ga36Rt/e+0=,tag:F26dsSc9SO+sF2rNKRtbkA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2STZXVkpNSmxmNDVySGJB
            NlRsK0N2dDdRV3p5M1pOZDkyeE5UTlhFajNRCktVbzQyWVpaUzhUVEJjVUY4MFhL
            M1hSUlc2V0xWTnhxS3J3UnZPT2RoeGcKLS0tIFFCY3hnZVhpUEJWRkNNLzBGUlZW
            b3RSN09nV3FtdVE3aldMZFhQQ0h4T1kKpZrcE/MkOKigDe+DOr+PUiGtBjHKld/0
            UlZ4EPe+BVOg/I1EnUd/Py8JE7HtF7eED4t8OeFqrqii1p1jQhnaDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-26T22:32:32Z"
    mac: ENC[AES256_GCM,data:KBR05+W//GzEkgYBQz19qgTeT8My8enNlvXXZwhHI3mpE/wMPNiuA1+1EyoviLsqpr8YUfojL3hC/HJMR/jr0Lzv1ORNWXVK4rW0wDWzZPehJa1i9jqjstwQOmuyBvz751iJgIRS6r0eAB3WwEhitEH8fkJiojl1o+5LdWma5gw=,iv:2cicLDwYHhuGSs8xEfHl0GXgVVrEoeijgh+DcZtoVoY=,tag:c9e9BHRZBjxc+9mNENUSgA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
