apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:Qanbxaz93EusZTKDTUnNEyX8bQZyymum1J+DkZdjQwDo0QsGLBca3TPSe8B/KKpPtKFo2KwXdnU9CDA0hlF3if8=,iv:+9onePwl/QEGZC2k4M5+6WV31/eJs3Sf416Za/Jyo/o=,tag:4srfDfLJxXLOorVDLaP8bQ==,type:comment]
    #ENC[AES256_GCM,data:H7f42G9lAJMa9QlvEDxD+cXv+5jfcTUJBalPGd5wK3RQ7jrZuJLsF6WxgNA=,iv:JdfhrsqmRoz8+T/LB0JLefNeMboWfvNybJGsFflSvZg=,tag:yh5aSipyI5BE+vpx8hAZpw==,type:comment]
    VIP: ENC[AES256_GCM,data:VwwBOjwf5L1uBuIe,iv:txtw6bfZlv8a3U93TeMznLZE6ZuShDdSM8/S9Unw+3U=,tag:icLrN7zej2/jadXnq2AUWQ==,type:str]
    #ENC[AES256_GCM,data:ENK+sQkOMFyBBlzzgQPihIu/09+GIKEC3/kE,iv:hBM6Jllh6xNA/UImCbz1aeyEPwb6r6noyvj/yxJM+PI=,tag:vED/WRJo5+vZhrOlaLUzKQ==,type:comment]
    #ENC[AES256_GCM,data:eRV80DENHl4peIhB9rt0Yewn8wg1POLI5NqHJ/dLT7ZghqZZ1SB/SfYUEdGLxWldHalz+KlMDXr9P4/7uluP/QA0CWz8wJRghA98ay6kXzkX5gt3l7qgwME=,iv:y+0AcUlPJMjfsB8Hn0E6dux6mKp5kKFvFUu3rRonDZQ=,tag:WW4SxWjtdsCMjV6AOlIMuw==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:mMaPOirQ+ejmZpKX,iv:Ge3T8VMP23ammACkmi6hOlNV0V6ekzgZFqcFv4p492c=,tag:zhd8rIN+c9pHIDMNBjZ+Cw==,type:str]
    #ENC[AES256_GCM,data:6geQSSgdL5sTG9S5NIU9+iL7qAA6iG60R9orvBfJzqduHw==,iv:EiMH4e2W5GslHWzTUio3g+ZUl8HY4NSmyNvdc4neaRs=,tag:Pxh0eAyaJVDS8rKg6vU+dg==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:1iV0gDkU2lvdBIA=,iv:ixnThLk0Qvzn+ci7EAfiW7pNBcW7RJuSMMpLW+4QPR4=,tag:X21gA/zFv5AhBRNd7zyndA==,type:str]
    #ENC[AES256_GCM,data:3c0T7E4LcCZM6yLJmiaxNpzpmORQEjDdz/5Ta9lKGc/gOcO8QFw1i8qwY/ft91k=,iv:1HfahCtKV+APq+A31fOGBgGDIIVsS2AKI5d0ImvNSYk=,tag:sUJLNB/HA0rbHjEDz2SqfA==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:yVE7oC3ciB82Bcmgm0KAQlcLm5yMGWsUluGT,iv:hQErIMhBhCeVzIkUpyL1B2dmoaU0ZEKEQBPiPR1a71k=,tag:sCmnunGAJ1PjIcVeNzcJTA==,type:str]
    #ENC[AES256_GCM,data:Z8ZYrjK+cuN+o+Ti,iv:SwvZgNRQKspZU+SVZUolCSSTKivkduOfZnUuzlUCKdo=,tag:gXVIgZOn/7Pt9dJgEDLUxQ==,type:comment]
    PODNET: ENC[AES256_GCM,data:QJs6h+dOVCMZuTlVYA==,iv:Xnh0kMeMO2SpLEyHvNtgkBf0XoufORdEvSk+QquSENE=,tag:NZPDL9fW1AwC2EjrFQWHdg==,type:str]
    SVCNET: ENC[AES256_GCM,data:ytywTV16wYSp3v20AA==,iv:r4VNbn4/Ksk1wuCZr+y8F22wm/hG6er1Y1PFB8hJkDU=,tag:I292+6QOmO5hpMTMftEL5A==,type:str]
    #ENC[AES256_GCM,data:TXNo/uoI5w==,iv:lrtExsuSjs48WmBa8wrEgWf3M5/ShHv3lz7bwVTkJWc=,tag:SfOIj92McltWHizBvU3BqA==,type:comment]
    NGINX_INTERNAL_IP: ENC[AES256_GCM,data:g0WuhDtORvUxYnrXig==,iv:ziL9MzrJvXvaVjDrPKVNOermgOJ6BIotmyv6C7JF6Cs=,tag:IVyg06HZE0OCCNQ8kh10Yw==,type:str]
    NGINX_EXTERNAL_IP: ENC[AES256_GCM,data:vzoLQiSz4Mwd8IOicA==,iv:kUb7I5BYsmqFAH7w+/KsUpA3tx++serpuTbaWx66PLE=,tag:CAmI4kklkov0rmDdFvr1tA==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:O4I/xd8yBh+w/D+V3A==,iv:1tpt7wlZ1Kb1xzdgcOInaIdn6nRxeoKEyHN6N+0jQ8M=,tag:7TxEL9qTa3uQRe1yaEBrhg==,type:str]
    DASHBOARD_IP: ENC[AES256_GCM,data:Ftu7aeakS1GWXxllhA==,iv:DZ1cwzmXSVl2sxnDb9aFuFR0tQU4ocIjQBv2lY7Mzhg=,tag:HgbExAkIzMyvSRzygPRIRQ==,type:str]
    #
    #ENC[AES256_GCM,data:HJNpwARApQ==,iv:EonRWXXgP2eioPGQNNiFZqmMwIIAq4o8rzaIE60r9Zw=,tag:7itTHQroPuXk9wPJf12OAw==,type:comment]
    DOMAIN_0: ENC[AES256_GCM,data:tUVMbynvBs3zvR5UH1rfSCj0,iv:JNjMsC2CzuqsqbXT4Ybvdav8wxY07umZU/GF2qe8t7I=,tag:rNJmQKCV0iQ3PaTjfwINlQ==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:p+6KHt19SEZPLth2X5j7T2dx,iv:DL8nC6d8iYl9GawJ1Yt6IOJ7KKGWjizM/uZ0xgi8BbM=,tag:SqrULbMnUOIsqcNd1F5yCw==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:LARauN2J/WCHH6k5Pp6RjncWux2491JtUF0kg1g6tlvZmuSvZ9TS2Q==,iv:faOHGxJA2qMk81DHsyxBSjXMhFnEjaxjIH2nor9wyqo=,tag:Bx0/j7fmXTxDl4e26lHQfA==,type:str]
    DOMAIN_0_CLOUDFLARE_ZONE_ID: ENC[AES256_GCM,data:V3mmKx8AUgSBxU8YRcgvQJAIEdXDy/XlslUwU6t15yE=,iv:9xUxXkEJDSQrAFyHxeyTDsbElDSoxg+VpgevOSRJNR0=,tag:lygyQq93C5eick0kBQDcOg==,type:str]
    #ENC[AES256_GCM,data:dU0jYoNMs4UP5Az+YeaVks7kX9hlCDe2c3nO5eadxaQzOQywW+lEOkaP1zvZRGm6qQpnWO997po=,iv:cJK66sicrIE+neqk7j7206KcMZfFak4VRIYWHW9i9IY=,tag:azkxto4BXm+uoz2zy/9jVQ==,type:comment]
    #ENC[AES256_GCM,data:8n2tcQEg5/6Jkku9LZCgy6TAjtRWjVv3NA==,iv:CeBvnP+erh4JAj+eq7R0y7rlbfq96PDZsLtmv9Los4k=,tag:8+HdtlZpIAsvB2G464qoLw==,type:comment]
    #ENC[AES256_GCM,data:2fqcVqHImjfV3VFBy2ASGfHbjkDVbFjuJLvpFdvJ1HYeM2Z0cE8WrhRqMGY2xn4m0sExU5ItIG+6HujKtqZPxhtIz7XblQmD0O4/w4A=,iv:oSsY9oCAZoRBcPNneOLcUVpMuc3dKLbI2TLcVDmvXyI=,tag:L1iNqwHOr+7GsM1MHPs13g==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:5NZQ9l52fSRtrGs4/0EBl6swNSsklWNOiMbhMAV+TrWwXFykhkwt,iv:QeZLWAGBkRlrjrvA7CkcT+SH7+B+dPKf35em+A5lwSw=,tag:eik3xGTyai6eA7XOLwx/Ig==,type:str]
    #ENC[AES256_GCM,data:+6axU4O3pWU9FrquSC1cxDheUDWbo5UHRlm4PeAPWkJ+frK+tCWIpKdEGTjt6SEiMJTBrmMMpXoUsnoMvD519HJ93DOT9zg=,iv:hXPw6bmoYWfeQmyP1qxCRhGIOwUPNh7MbT5UC5KUgZg=,tag:SDvUaMvO4IkL8AqA3kfWpw==,type:comment]
    #ENC[AES256_GCM,data:C8xQVnI8QQ2ttRyjQuIW6s1octwCzC9QwUVleDj5ZfOa6EY24s5KrZyJMBUPEsego16DmYG5,iv:KPCQgiFaH8bb6HF2X+AB+AhQzDsdLQ80EiaK9p5P/lU=,tag:2QqY+8J9IvBmIxBz3xbk7A==,type:comment]
    DOCKERHUB_USER: ENC[AES256_GCM,data:VuF8lILrOFtd9/pA,iv:f1JhoGGVHFICkQAOR9SDKCZrMNetnCBrBPXylvaPn80=,tag:oZxw4rS4O0lKDguyYtwqpQ==,type:str]
    DOCKERHUB_PASSWORD: ENC[AES256_GCM,data:S6E9n692Sc2SjZ4FFKA=,iv:BSm8MTJ0tSex0HBj5dYkTZL4FR85wFlWY1uAXSvMqas=,tag:BXWIJyCXBMr5EYkohc/N7w==,type:str]
    #
    #
    #
    #ENC[AES256_GCM,data:CFAPWFgcIu81QDlsjf8=,iv:Ab3awabTXLY7Ta2r3J0+CxSArp+UNQJraYigEaW9FNY=,tag:UTptgQFYYDj2+XojOA9rIA==,type:comment]
    RENOVATE_LICENSE_KEY: ENC[AES256_GCM,data:RxzxikfT3337WPmwKgDgE0Hc8hSJps6hAxaeToALe5kE2/4WLBOkb6rmj4eaX88WhQRUhoYFpoy/jwVYY2wQgbzqfNBT1Zo8FExQxJDz0TTrtbNNZe6gjRoOM/OJHG50bvcS7kjiLvsQ/25JU6bUaDmc7lcVRhflzDDb+nv9qYns/JhYAQ6FVIIoTea12TjhiaiCJzgnl3Pndsn8hupsQJB3RIoKuQ1wq35VBm7ssVBX8hZTEJLUMGhj7HWnW/hy1qCHSbAa3607pE0PW+5ZgbzmNUj3uHzVm9WMo+0=,iv:1GsVjBJ6vBbmcB7H6v3ga2toohoLtjzkSxripZ2CA7w=,tag:jsLp9BJ8eWqlOfnovF7wrw==,type:str]
    RENOVATE_APP_ID: ENC[AES256_GCM,data:H2kdcgjbxA==,iv:BdR5U7ZShWIr+BobvL21mb6qkNV9Q685Vk/fG9pcHuE=,tag:wQwrLphHjgNn1+QWTUsE9Q==,type:str]
    RENOVATE_WEBHOOK_SECRET: ENC[AES256_GCM,data:Qnz2Bwz1vUUGosJqvb6XYuXANU6mQAaTJ3sHUtBiiJI=,iv:9WB1g7iHprfk5s9zcPsgnSdJQs7lhpB+BJxMKofYONo=,tag:oePOOwipRN1+d81ZlDN4wQ==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:JW5qQA==,iv:kY6lrSvy1HA/UkADUWO5sWR1XKuudn1rrwTC5sgkM3Y=,tag:64b8SJpXTmGZNlb7NGZUmQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOMmtyYnpCRENpMkdqWHZI
            NFBSZGlxNWY5K2NsM2FqOUZjY291dFhiRzF3CjRkS2d0YUxobjhTOWVyU0l3YjFR
            eDd6REdHa1hFZHVDN2hUY3M2UVJPbHcKLS0tIGFZZzBQMTNRejB1R3I5SE9MdVJN
            M2RpaDZaQ0FrcGJteC9SV0VGSXVSSWsKW7S9RFYsXrW+GYHbn4GtNxxvGRZ553RI
            /O9xkfWDep8yuO9Qy2Q2+moamq/bmxJ/hb3cjRu0GMsfwjqBmmnjxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T04:15:48Z"
    mac: ENC[AES256_GCM,data:+ApjIeEtMsnh/pWAkGay2f1SalNc1QjAbHuuZvSDqUJ8MO4WXkH64b0kHvUPuRYEUq4Re+6Yyle8cMO3s0MO+brFGRfZgzr/cqozgg14yVctEnpVrHGLuwemkfbQA3shPaWYWj6TKrn6YRUzhDkYX8XnEtX+v7JYYvDSup8OUBw=,iv:3MHKO3mkBkBYLsZNt5kmMHw1kolmEo2HLCx8UOFl+hs=,tag:XB1b2FlXoWYL++ZxAL+zyw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
