apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:V7Ad3fJnAK0cxgGxwRI/Fh/0DRCNVO0Jte9kE2XcMGdZLpq0Wn9XfhoVUOcoUfP6yjvfPitNnwBb8cMwttGKlzU=,iv:FIiva19tXXsSkdefTguz5+L9XhF7Z1Lqd2jI0o4k4nk=,tag:fgztkiTDf6y0YFmMAle0cw==,type:comment]
    #ENC[AES256_GCM,data:SOwO/sW5JG67XRHV+SezgnqbUvffHygHtYsTJtHkLekJ40W9kS8A7Q0IWTs=,iv:nBtT+hAXs2rL8cTdJ5+M91291Gyw36txKdoM7nsTI2Y=,tag:RFUn3S3unUZonouEy+oVMQ==,type:comment]
    VIP: ENC[AES256_GCM,data:O5PMuv9VjKbQElTk,iv:QMJsZbZ2sTrR0f6oSRHScuWzsMb9Dl1SEj/g1FHV9dQ=,tag:jEY9evNauew2T9XmCfOJlQ==,type:str]
    #ENC[AES256_GCM,data:LW1sEMdQrGUK9Needyi3fESUxfMrf5RgU9jR,iv:LWbzWz3s+3Fm3HIDOdi1aYXTwnwIr/AEy+Oy42y71fo=,tag:qOM+cAAgepD/WgaCFksYKQ==,type:comment]
    #ENC[AES256_GCM,data:apqoAdsZ240yyCi8qIef22kf+/akzjsG+FisJlH7sbI2RiIdrMvOdWYKrUY135tz1zTT3AGIp3WrPO+gHUHq3sV082Iw9hoLpllSLpugt62Xf8rp7/jmmG8=,iv:Szs65e3EXt+gz7yyR5MCJkmNub0OlVEEsZAcSONZMKA=,tag:ZVgfBlsBSEj2ljNfFwyENA==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:JCKkGDKzXlf+7P9y,iv:izOsek/ZIEe0hv/tpbF0/itUmmqUvdBJxhNgTs7YddQ=,tag:RF9Q8n0iPahnwrX4VbbYbA==,type:str]
    #ENC[AES256_GCM,data:ue69ZA/gp0TGeIaxzLC/CSbXZnrCp36h7T2Zp/O4SbMu7g==,iv:g/JuflvsZAYjEfaqzfKrtU2xwsg1d6nhEls9Sxndsk4=,tag:tI7lgYkE7w2DK9gZk28zAw==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:6ka5KBv7qF32aXk=,iv:egip4an2OwwE8t64SmdEBST9yIGCwfN4P8wUMB3EsB8=,tag:Oqar8wSLTU2WqmF3tpfdKQ==,type:str]
    #ENC[AES256_GCM,data:r1zu38LIeYcLgD6uGCsIZW6kDxeTqL0S3voXkxZKXRb4kUoNMcLd/Pxj3IsLZ7Q=,iv:zhY46Lx0xBg6Fnp6vyx/vb08VvGaS9gNO3y2WyPE3qo=,tag:4ChD3RQ99j/0E7zQZ5O97w==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:wZAJKk3661lO3uiHt0nQ4Cg4jsPn5Chx0b1W,iv:XrOL8y5YgRxzhYoJRWjF5eEXexgma7a4RrLfB7t5iDM=,tag:C8EEvI5WkU0F4Tdwrk1rmg==,type:str]
    #ENC[AES256_GCM,data:lLRVehpsO074CeRA,iv:cJc5Ow3f0FQy3ASFdvFfbL0xqaX3EWKcjDDhYGYpGps=,tag:por3lk+JXaPOnzx+XrRw6Q==,type:comment]
    PODNET: ENC[AES256_GCM,data:n9tgrb8bTVx+zp0S7w==,iv:x/AsvKUxEhlsYnpYcNhHLgc+p2g+XkdrHPfkAJrrZ68=,tag:UcfDdOzcLEvuP+NSIug58A==,type:str]
    SVCNET: ENC[AES256_GCM,data:dY+WGZwmAV038lsfTg==,iv:WEyu8AFQbai9jwwmLrCgAmB9HnyPLc4hB+38OSH0f8o=,tag:ZitOj017wr1Junz7Vf/Lqw==,type:str]
    #ENC[AES256_GCM,data:5+idkgt4Qw==,iv:9DoDzTKueejMDxTAe0dZ2dXc6oDHsrvAHwvO5GTTl/M=,tag:Oa9nx3NWb98W/1g4IjlmAg==,type:comment]
    NGINX_INTERNAL_IP: ENC[AES256_GCM,data:98wYgaE2nomZQEeK6Q==,iv:5McOEr/TytKvnHi40J6cc1pTLxSJLrhpFzbbdYTsRiA=,tag:Wo3A4uDn2yMp9csoYKcVBg==,type:str]
    NGINX_EXTERNAL_IP: ENC[AES256_GCM,data:Nlg+8LPoWKf6JhfL9w==,iv:SW0KMwlIAcrxw8Mpqxk9kSBdGgUyf6kq/rdBM563fgQ=,tag:+E7h1hH/DnpnAfSUU5bs3g==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:FyxjeV4LPoqfng80gg==,iv:qHsXByER1vLWBpI0TlDvFtndoxiSoK8sq3eBbgNdiEA=,tag:shlTnV7ygJhpSNfjfG8FzA==,type:str]
    DASHBOARD_IP: ENC[AES256_GCM,data:wTgVCkwAtYd0gqw/Qg==,iv:yLVVmVSa661cFOZNjMeCy6fSWudu31XBiMQ2PvZM3aE=,tag:URiLgWpkBtpDGbavgm3L0A==,type:str]
    #
    #ENC[AES256_GCM,data:/wCmHsKazA==,iv:o2AuI8njS8jmgq0liwjuRdC2xCfPyFe6Rfh3Kc3DDVI=,tag:b6t7EKmHBcJt1oL5VtlCwg==,type:comment]
    DOMAIN_0: ENC[AES256_GCM,data:6Xu7Zk5EpbkYLH1g/FE4+jxO,iv:giG2435T0EzjlmGvqelMNN8s9hnox5QVMt/bk4eixf4=,tag:DvENYM+Rk6H8R7/ZT/7muw==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:J0YJWlk+MZixC+3q7ERMcZS/,iv:7JsUUaRDB4toAvop11qP+vKVeI1miGrP+NAIIs6V/iU=,tag:GE2L4GeNOagR2aN62btFoA==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:YkRByM6Axci+6W0xhjy7HHrxgGT3112PtGfA0DO/bfoGhzRDrUQXvA==,iv:Q0+XcamWlEWx0ez2xZ4Ho4XpbqotfjT/8AlmCeYpbuY=,tag:xs8h3z8rAqRD2h79ZGEnyQ==,type:str]
    DOMAIN_0_CLOUDFLARE_ZONE_ID: ENC[AES256_GCM,data:/DVYKiDqlZJSUQlwkd2GVJmtXu75DXjsM+0+6/iynbo=,iv:E6eBjxEIGhqq7xWaWTDwFlx3a2AdH2eORNga/XYy+pI=,tag:dwUxD/ieEC/tPvkerohJNQ==,type:str]
    #ENC[AES256_GCM,data:WBmX6TFUFapa0KbwCIadVxy5wfrBCpsZ1THHuKQK/e5D25k/BV27G3yZJY5NJD1N8io2dlv06uw=,iv:ni3+41aIKOM1lkP8k1e2YCNVa5Sv6wgBwNpWo0GLvKY=,tag:u4GH94h92xOvaL1yJ5M/5A==,type:comment]
    #ENC[AES256_GCM,data:KZHlqXSQB6/7Wa4PMswVymxk/R/0cYmrSQ==,iv:DiPdYrcZuLnH17JLcG4kemb/OTvrJQ+WQPBEl1h39V8=,tag:rsONb/NdWkhW/GPk4qVe1w==,type:comment]
    #ENC[AES256_GCM,data:gO8o6mlnUi6zRVrO1b/RM+V21tNwbR97qgmRmaFSH+ye6YXWmTcdRLJF4rYjW+06bR8zzbAV53+O1VYAgrz5c/XI4erEW9BxBB7Y9+Y=,iv:a+4WU63aZdw5PpIlSYud0VE/8bzf/HKF1VJEPb04cKo=,tag:eIAB9csOasOAZ2NX3LVYvA==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:mUTwJW0HFsg3Yt1aMiG5DfXmgulJc3KtVW6jneZ4ooDQaZTkAeY9,iv:fw8PZ9IL1GCDCqtsynaZvA0d6mgtGr9BQy2XPG7P4dA=,tag:gquhjYkfXe0tfQmeHmPbAg==,type:str]
    #ENC[AES256_GCM,data:m23u8v53kqJBtGAurHRp1SSwhA1Yegy2/UREVoYEyfrPeWn0RaEBX3KntU+3VLOdHmv286peGURihq9dxa+OEYKtELyt+lU=,iv:M6u4/Xke8eggXSTLBBtE/QGU3QeMHG+Ez7fv6zL5MeE=,tag:czjqVsmwm2auu6S81sF3fw==,type:comment]
    #ENC[AES256_GCM,data:4+TyF5dTp0BEPxmV7Rzj0sIt2lK6mve8HI4SRZl2tyv8kWMMgFp0vu8fm4xfrrKyCZ4qFARP,iv:Iqv8sYpcFnIpXb4QHGa74ToFM0WoKLsPVUF6rb+E9qY=,tag:CJqfqlThwjFLr5+fxoufmA==,type:comment]
    DOCKERHUB_USER: ENC[AES256_GCM,data:11GZH+/6cY2BD+bh,iv:hPzOvoR0i83MasQnFvt2ApdEUJbe9ISo9FE63kzmMTk=,tag:iE89BGkOuwBIwAFxAP9s4w==,type:str]
    DOCKERHUB_PASSWORD: ENC[AES256_GCM,data:99jl3TMnXp5C+mXhT6o=,iv:Pi9PDExyIgnSDOzSPS1GJhGY6dhM0+pl+UupJJwhI8k=,tag:BHEAGAyrdcUB5S/pkyV3hQ==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:lxoygw==,iv:jowoGwuY62uZbUtQ45hJfnOJq7O+oGY9JFztpj2kyNo=,tag:ws5lnzh4UoM+EiykWfNlMw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkckhlWGcwNEQyb0pBbW1a
            WndkYThDT04zSktzOGNZdGNVK2QrNnVJYkMwCkJtSnNNS2IzRnMrdncwMllLS080
            cFNaWTRXOUltN013Y2E3djc0UXpXY2sKLS0tIEYzdlYrYllYOTk1TVM0bDRVQmpF
            bTN4SEVEb2U3Q3MwbDhuYWxYWVRrT0EKfuj+k2EUrO/80EhVLXDFzujWFD0qBgcQ
            uSOQNZMPVYC6aMkFMaer56wfzvAUxM5lRY0TKoIWWAnTRp0ASky8wQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T01:50:07Z"
    mac: ENC[AES256_GCM,data:xWmrmq9wrwl0xkR118kzVQS6+KgJC/hekbWgw4l6bjZHkvyinTldOLhw5d7jj8yZVhGyi2FD54++hvUHrb+5/+hqnXLurHvfREaNhg51imumsf6MCmhcYx/8H9rd63ND57LFq6c8d+jo49TvmN1wXlWmqYvYEsJdBJuZCKfma9w=,iv:EFY2pgCmEPgGm8IWjQGey94iaQdYYtv0Qc7YXkMpNz8=,tag:hwTQtj//XbzCREhR0kRBuA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
