apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:CZrW5WrSeOYCdy2pnZa3h/2V7K+63GCpvEJudkwUF8POWauNst27wH97Qsb/vjk5TCP+NuKRe5smRzmAQ8UK7TE=,iv:NpLlaFH/UjUhi7Lei36NpZEZboi/Gh0oSMADKF8ljfc=,tag:fEVUJ5foKTb0y91SbZVmyw==,type:comment]
    #ENC[AES256_GCM,data:e0nnnfJeYmKLXiCN5YD9TAPoTmCvXDGotV+neTct0RW+Tgneall1snn2UJ4=,iv:FejUS1EE5Atd5Ti9Rat9hiRDh6m3ZDFQLa2kafkB42c=,tag:hzow2UNd97ZJdR6ImQeyiw==,type:comment]
    VIP: ENC[AES256_GCM,data:ymgql98NH98aTJR+,iv:QdeZEM/A34gu9ABlU+dN/+yEoPhMxCmXGrHbmKswoTo=,tag:jEVWKt9IxWaW3UH/CzGeUQ==,type:str]
    #ENC[AES256_GCM,data:pJifbQuLHrjkG56PYTpsCF5eTysQbGa8lcC4,iv:kZW6q5Z7mPdaGSRTjDtIZFL0bsntxuxcJLTvwZ19YY4=,tag:4mLYGSDY4XDexTeQI7+tgg==,type:comment]
    #ENC[AES256_GCM,data:Kli3lJ4nWodkXOSXPuCeK/fUmjH1x+JuScQe69PLkcHctRWqdJ28uAlF1UnS5rUwDcd/KkRXJxAq+V3JoZl0gpj5y2JtexPvfuDq7RIZJoK/fBJ+Pdupl3Y=,iv:tufcb0tDJ7XW+8w02OZ1O1Qk6c5yKwvk75r9M6usiJ4=,tag:LTz/s9s2XfTbnrNJTiqzQg==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:QXCl+RC8vbGZbidD,iv:H1ekXFsDXJ2vpqALDmhXQuKo0P5QuVbHrTZ9Xojugbc=,tag:DQGxRbHd/YuyeFMfeVE2jw==,type:str]
    #ENC[AES256_GCM,data:W0LEqaX+/ztx/OEtzuPliNBxAExYN7EhrQN1WM5ehVtDOw==,iv:QIxc7OTwIdN5Agf2R3AxzaqyoOQWAcvWa2WV7r1YO2s=,tag:8Jm05k7NgVvGlKZYdoO4iw==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:azBjctJQVyk4Y/w=,iv:vOmaXgCBPmnZuCTtWqEwcfsvjweGH2eRc6tHfq3N8I0=,tag:mwQZmtFt6/Mip9cOTSZidA==,type:str]
    #ENC[AES256_GCM,data:5k+2kiOewTWjojMRAluQmfVS3htN5/Cn5c44B17+bh8NeoY4Q/PprKqJ37hbseg=,iv:PHQG7pbzskHRms/yYVM6Es62QpW+uDC7H2CGvCoz+m4=,tag:EKcvfuYhfhhcRSB5dXoOdA==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:9CxC9MSnPgPl6/SZM0fORzMYoTBkVPmKA+bS,iv:u+CZstRgGGM0Ss+RRDXiRSfQFQvQEO8gL7SW433GC8o=,tag:aJkR2JU36HA8k4CCoAC6zg==,type:str]
    #ENC[AES256_GCM,data:OSmuTrugrHoLh/81,iv:KJuzZSKMHzvqzC6aSd7EKK+UmVRAcpz+Ds95lJJ5JZg=,tag:ezDyZOqraY9YN0mP8lYHLg==,type:comment]
    PODNET: ENC[AES256_GCM,data:IrSRIyjKC1rClNEw7w==,iv:JdSOC7sBVqTn2c7j13Jr9+Pis4IlNs3Wj8F7LSaA1fs=,tag:jw/ydNsRbvGEN01Sr4YPhA==,type:str]
    SVCNET: ENC[AES256_GCM,data:4CPGHMnvw/uRS3lZug==,iv:pIZVrwewnqypyQB018rHig2Hy25s2bVYkV0l+HgYxxE=,tag:Kex485jU/SUX59SvtAe+fQ==,type:str]
    #ENC[AES256_GCM,data:4DJNIhotbg==,iv:tfDuD0ry6z7QTQ8zk4+/+jCDdsMH12Oog7C3OvCDh28=,tag:VFpGQrig4LcOD4wfxUCN7A==,type:comment]
    NGINX_INTERNAL_IP: ENC[AES256_GCM,data:mYQXgEbOidFUF7TF2g==,iv:BuqSAY5XlwE4w0bRZuy1IpZdQiQarRsi4R5oWQs3wSU=,tag:QO+aTIQZKOdP5ntyfQxIFA==,type:str]
    NGINX_EXTERNAL_IP: ENC[AES256_GCM,data:gYup0T+uFE0eL1ChzA==,iv:cHN5GA/k9oEp/PZ1JKtqK5ZwA+1lQTa9HA2qPa5HR/8=,tag:mPErHAK0vKbR53jTExkU4Q==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:nS9dRQXDaqYnGMcSSg==,iv:wZS32A7PEpofjToL9te3YFEFua33/VKC0CDUSMIxdJc=,tag:KpQArO2fJvhzQHk1E4TZqg==,type:str]
    DASHBOARD_IP: ENC[AES256_GCM,data:sn20aWJmtUJf5+2Trg==,iv:WcGHJ/kUXfgXb/vpZLSMbqDuOPZt7hHLFPhyxI+CsSM=,tag:9YLSu5XIqx/rMH3m62z7Qw==,type:str]
    #
    #ENC[AES256_GCM,data:bvxt8rpydw==,iv:jTiuNKj/5OlF9ZadpP7687D++Uk1Dg3ohtwD2TUt4u4=,tag:C2ArcENXsYd2R/hCrWezUA==,type:comment]
    DOMAIN_0: ENC[AES256_GCM,data:HgD80472Dl6eIlz9nC61u9t5,iv:AyjQzTQDO3c6k3nB0JqtTi2t3W3FcWH6pB47HeLTlaY=,tag:Wfpwj1olutdNdqN7WXR1PQ==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:ZsCd83HwBPi0TWu68FI6rd2U,iv:sWH5wW6i04wq91OWNf+OjsTtTKq7LJkd+yLNf6xQ8rY=,tag:0cIjrHfFrFzBS2FhDVsrTg==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:7cYQiEww5QOTkdzM+1Zdshw7oLhCWnOXi3ny6efjLXshgWQ15vKoDQ==,iv:hL0tgWtsQu5MHyVNWIjHjAbJ87Ve8HRabDMVywdvyrM=,tag:pUv5h/SVU0qqFwKBLeeXpA==,type:str]
    DOMAIN_0_CLOUDFLARE_ZONE_ID: ENC[AES256_GCM,data:3fM3Q1wL9w4bb1hppu45XgrKGvm3898UNbPm/H6dQiI=,iv:ub7jsbjaEutYvIwPQmAmQbaKBqNDiUKLsCL8Qtj1QWE=,tag:L6J/Mf4dZrwF5GsAqPpTBg==,type:str]
    #ENC[AES256_GCM,data:i5VOdwaPfmqHpfJkJtYPoQeB0hxJOKCucR94x9W85tajLzyHkydhFSIdN4dIXoLvgutM1rlwYxQ=,iv:II11Ou8ZyxZ85PEoIWxpVAc9m2YtVVvLabzH8VngEvc=,tag:VcicxdcgunK28IDGIt4XBA==,type:comment]
    #ENC[AES256_GCM,data:kvxGQzwdYJtBl90E0bJpKywm8vSw9AKqmg==,iv:vro0azBaY6G3dpMnRqVkg2lMR1abqh9jOllfGxqcCFw=,tag:Lb41pvsWdjfhjDXAr3Lf0A==,type:comment]
    #ENC[AES256_GCM,data:U9dGZDdcdrdtN0Saazfe1PPiz9Xswu6KG9DQr83AIzQdKCeizqvbqhqihI7+/xXX8zCJo1HVT9HRzTcQQ2n/KJWQUraMRDzn9GmMrUY=,iv:ZbF8OcpmSQ9NIcN6jTnoCo9uca63Q6gUSSZ2vpRbR8g=,tag:5Ah76eWRwUTwxI9kc0dOxA==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:fj8uYFfdekwDemCx8mgF/W3W/Tatnvy7vy6feKG0B7IQErFrelz4,iv:LN9vN/m7/R/6nsGadhJ40iVwhJ93xL85A0j/Llz/K2A=,tag:c+1VkySzM7JbfT55LDS/Pw==,type:str]
    #ENC[AES256_GCM,data:yupgY6M+USeGm7QCCvvDCMt8yACRS+HOUWhmQDlK9V4beqha90OLWb7Xg9/1X2W/iShLJxatfcqJ9WovRBe+A/63SoVWgo0=,iv:v+JJpcg6gtTc9YWHx/sa8XNk/cLR+as4rBMLm0jI8As=,tag:Ks5g0R+kVDF5P/5m01IdGw==,type:comment]
    #ENC[AES256_GCM,data:+GRP1Xo/PGbN4vSHrYKi0lJS0e8ZUs3xWIGszD+kDwuVQ33Yc1tJAFTAIv3sRXlF055s8nPL,iv:7goTQI862dWxfm08Fw1MNIzMzdAiZBnEJObKFuwlQn4=,tag:lJPT/dZx54k4LVLc8lnVdw==,type:comment]
    DOCKERHUB_USER: ENC[AES256_GCM,data:2pS6DEoKDzAQ4Aex,iv:d/DyefBQQJgRnwu+yXiVT2kB7gHoInHTxR0nFIZAzP0=,tag:oRHabTN3fAj7g9kKZ1fn8Q==,type:str]
    DOCKERHUB_PASSWORD: ENC[AES256_GCM,data:qb7D6pWOgh6JsSvrF1c=,iv:BCQv063R5VITBwLoQIsEKs4OjSNyjhdr4a+heDaY/+s=,tag:zZZQ5orM7BIwcjaRBofuTQ==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:7hd+3Q==,iv:F4mol0jAlSFZm9QN8Ofdz9wcX3BS6mrJGblU+iXpY7Y=,tag:IOLP3UiP6CR/Qa0qnHppcQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQMHdVb0JmNGNybU14TDVy
            RGF4c1Fwam5abHNJRzQwWnBTMU1DczVUYUZFClBhMzlhKzh4YUZDczJ1a3NWbjNF
            VUNCQVNLUHVIQnpRSW1jUmQzL0NadzQKLS0tIHRuYjZGN2VLOWEvSXFrUmJpd0Fx
            cEVWMmFjdUg0eHFaNFBQZ3NZRnJ5dU0KQeQn8ASte1znodP9uQeutnfcsa0xrZsa
            2En6stLYbu7fKQPoNVmdvm3m7Cz3f61jISgpZVYt/1iiqr4pLLgGiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T01:33:09Z"
    mac: ENC[AES256_GCM,data:vGcmtFM4P/vncgcCuY68Cn/ezmPAAriit7ISuF70rvZNDuD8sRFi6ASil0D1pDtysLSOmG0vBuXaqQiiJv0xxLdN1RIUocWNvOabY1TltsjJSQGYql/7WVdkiCjooh/UigVNHaCMsPFSofLb958sDdN0DNzrU6D1d1nR2tisf0A=,iv:ULzO8LwXjfEl07sg0NBK9bRCtsjP/OYxnU/3VGqKqlY=,tag:Tid2ooagB42Z6LrQu6RWbw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
