apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:uDM/K7qBC9BumqQKrebXxGnXExq/cHAcO0mCTaQXQUszu6IBOLOtsuKnSigStXTstGCA9v72GNUTNPoRdgB2Ntc5Mz47kHp9rOxQyhauWowIbRn+EawCozdkcho/N6/geCE6MepjgH3Hww5QoSIObBmsoJSGMJ5kQu3zy3pGQbeuAPNfIi99JUXvWIUMBaU2rbAAqp6WcFaZqFeIyVsE7ZrkpoMiINwMqZB3MIR6xFkeoxRhI0U0+2lf3LouFhTKY3l5Pc/G1CFIi1Yk4oMMLCSJurdTD6t1plVkVVF8Fw0CYvB/ePMLMBTsgZNIGHWLj4WEJZ8BvCLY7G7AtRP5MhojxvdystksIu9X0cuzKv3YlJIeNLA3b+y7xblIAqDz,iv:fDF5pUoZvGEFr52lBcLphbUmqXp8R2LLtRq8aYr5FZc=,tag:TLB4Yz4zUyoSMVfwizTpVw==,type:str]
    identity.pub: ENC[AES256_GCM,data:ZnZDfweRO4eAvQ5/Qvjqe0juHxbbWZCS8Sv3XsTOZk3MXBXybNvKeL12sVeUiwTh2h2IpZB7E7muEbTObRtCpRN7V3CW3Xge3ydC7bU0u/0X56AQjccOYVsqhYrMNn7z8Gghnoqzwu7q0jHGiar74MuuXwxvhlI3Vi4TS4FJoIWRSdnpdoBFSt++Y81EJAkXjH/r0m2mWxG4kSCwwP10j2ncYIiOFCc63ju8BBbCDNnhqq0pKJlWz7UVZCGUlBA/Sfkw38qyhRdHzaBoJA==,iv:LgzY8/7xI8lh/tomi8PBSaRlVQEVtxQn9n8VJkuO8oU=,tag:IxBYHM7DlwXDUtw18tySCg==,type:str]
    known_hosts: ENC[AES256_GCM,data:23DWeM9xRgdIzP58nPclEcGK9HQ/w2fubjEyzEqssaJbuIfGSN5bgQRr7vkSyPHp5u7XM1jknhEidSvb+bwnpJ7rxXWUegFDv0TAedK2y2mw09jfkPPGqpYOhnqit63+bMY6gT0icMTqRVGbhIX2Utitd7h0LOPlza+T4+vTVmCEHnrEpb3/WK5nEn5/XybujF7Bg0V3aD/TdBY59mDSLlGfyKGi/pj/i31q,iv:xO7BFX6KDOvm8/oKE6wV/oYDucDyzbqL2bOQ8S451C4=,tag:Y/06DOeAkis1ZAIg2xthmg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6cnM0d0pGWGYzSmxYL0po
            bmdLZ2IvbmpIcHhMd0FzOGlCbms2MnFodFJ3Clpqb1dORVlXVWxCQlJqVnBvR2J0
            SHRvRWNycTVydzkxMnZBUmt5b2l4bm8KLS0tIGpFT1pzV2FzWWtUcGR0d0grZ2pi
            OThpL3lscVd4TjFUZ1RjUWhZWFIxUTgKHczFM5k4J3Je2vBOup5lQG7wY59faUdb
            4bABpE3Jl148e/pXVGJljQRzdw+gfDrNBRig55CNjEL8tou6xmdFDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T03:45:56Z"
    mac: ENC[AES256_GCM,data:kt+1bndUUaTxqzs+WworbeUfEzF+1QC198cPp50big7lll9oRUlVLGXfwSHKdPVkw2P7Z8//cQ6oYy9UFXOCM42/oyju8eNuBhSN6usSvBYwGd2Tnc2g/slL7TZ3jde37J3aBfqmHT3ypW+MtZaZdiMR8Q1Ci45MYnoEi3wwi1A=,iv:C2QRRXkcRd89mAuCpOPkg16SoOYM+yv+s79i2n31348=,tag:BQL7XQPA2oDxtnifFd2izQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
