apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:JcMXHw3+5U/LoZ5USCM888ROr/AwI+eMgNnhWGShsISYU1h+usRfPl4aAR8HfeskO5bRQCy/n3yCsrwLION4ck5wkYGqawr/2SCYp33qu/9llIW9S0G+/Ed9uaJqoF2wkz5fdIDpjAgvG7ec5GJ0TnfZZ43llMKhTnAbUdgVrP5xDFzB7nr5Y4RNmMUGoLQiOBbYurQmwfZ5yl3BGM4zNg4yzeuYYpiC8ky0fgVw1ekp42+0mi063Ag38oFCi9u+WveXxScLu2GSzDAo71TJlgOb3usHfsZaw/29iPxzukBwGWHxfN5rfLQFn6NgfA6R1M9WS1vTOmOF9Dx9LpVd+D7HYZZlH3dzf/bInm3hQ7AFQhoh/p78sufZJu+fFSuB,iv:at7ienCsdDwzwquKJLqYOCnVSA7IvCeAjtV9qpX84gk=,tag:AsUprr93yfh3o3lJ9IE1iQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:pnBebAKCXZz09I5TCAqnji2QTKVTYiiUxZSk8js7RDGDZrp9roNR/8SM6oTdS9v32EQ9joUxSGr5Anc8h43Xe1P1LLBUYkfbp61VvkHY5TRt4iMfPnBJ26vCrSVokcD8l9E/jbqSSzRuAfjDQsLL3HcXJ36UXcUBZsatO/6RZNnA/c3RBK46yFGrp/1ETDwSI/sC/XKr3ZvPkq8N9wJVNv78sYLGsY671o60f+44mlqwihk8DJ82O8I7XhnHxrLR9jlO9abPT/v0wNywFA==,iv:dspLHykw05F0oETfMbeLix5UHwyoClp4ftIWoUE78Iw=,tag:4M/EoNHFfh6r6unQdsqI/w==,type:str]
    known_hosts: ENC[AES256_GCM,data:ISsHy8b3wVaU4yvQdzgwak140Ou4Am8dQjAwrxMpjaLdMb+St8UHBpZgHbsX3YjV4r71KuUPsQhWckeoYNq9ApmliT6UK5SU5qg3IoRhUOpmVNcG6GxL7Dn+RPUt2aG6oHo0Ka4xVwDeop2QJFcmgWk8kjLNJM7G8/p83j+iTW8il8sCLI0IbRuWIPkLcy6GR2PRFHdzbNF7v8MUDiOnNBVFv16IKKvSNvZA,iv:CTOWH4tu8RHymxFMP0HxNPeF5ULV+ORh0EaiU+E/6Lk=,tag:n2kGfMjiq3DTLfQAk98Mig==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjR2RIdU1CY3NLRG1sNUc1
            MGxPTytCTzZ6aFQ1cnVJTVA3NVZ6dlR5ODN3CmRBRkZlTU5ydGJHb1IraTU3cEVL
            RzJOV3A2OXRxUllzbkxoVlNJRzR2OU0KLS0tIFR2NzhMTzA5STdBOGhROE0wOVdz
            dDd1akJUZ3p4MC9FV3V6SSs1SGJrRXMKN2sie36ni9sLHL6Bps3cIF2yD7VY4wDm
            veiUCzP7FZ7P1sTcoCgrQcDGIxMjNxj6qV9dAzoPvU3YbA+0W2yRnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T18:32:52Z"
    mac: ENC[AES256_GCM,data:OLk7at8Npb8m5AA3jG/KyxW9qQqK6lPhWdPaUsz2Xo1osi5R7M9k+4i7j9HlH3Vwp2bNjtzAaR0nOoaMTeoUWnqJtYBD54d+8TNTfYETbwdIe+XX6l0oAH8rcD9omndO2+j9V+FmqjUfyCGc5vimDftNOuDBdyi7CcPt1JlN8s0=,iv:lwSnQBSvxu0WqbVMT8h+Iy3A+/LnPfFRzPnA0jGF380=,tag:9uRFlPRh6B+XNcMSEGXAig==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
