apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:7R0YjBwfjcLj8V4IxLg7SfCIXAWwChkwzuEb37Q/sdc+cDsRZGpho8gxT2A68qltdEZrOVhj3EaPCwVh3TKlQpcAo35aMsM8xq4lAp8k2TnUDOQQ7c1TL+aKPO8BHiG9wabpG7S32tjARlFkLMqdnoT0/c0u5a+l2d1qIzzmUB/2CuFUB7utiq79lAiiKlbYNgandgjhzmrTc/m2FzugKXoK+EgoD3nUffJc3iVL2JdToO/XGc2Ki7PaZlYkh3nMwVZLa17HB615taS7N7TVpuebm7WHlqqYk/4OIw0CQBxvaUrBJS8Pn5n2Za6Z/4WUTM1c60n33Xi0qB9HUwLu1aUbRE7KH8ji+o1X7cpHd+GxumJi8brlX0pIvX+hG51F,iv:fzQKCW6/wdRic97MOpP1MKnCFwwOUquf5oSgEVP4dYc=,tag:IHs7UghCSS1gzqWkDikjYQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:uzsAq7xnnNSKbWVLFgh3FS1mLH6mmXHFvN8mJTkzvepGArBBmSn4y3oK1SrIJ8DkGyBdIGcYzJMK88tIeXnrmMaANVSZX3vS8l5lbT4ySO3f7S7o/UIFlJOXeHJCbUDGvUmaXPF6iQT6ya70NiE9W6ot+MRnkuh/789V/plhzc0pTyPQxZATJbuBQWqoRPG8neEfxv0e6bJQwOSxl7ihVDLw4+/Mvn8ptDD74mRFx7lKc87AieHoZhHA25/obCPKHjpjb9miyh0sx/m/CQ==,iv:KwxC05gqp1HrwAHqwYTIvJCXS/E256bU+LUwvXA+cpk=,tag:3OdyjBqkSk/z5hjnuQdraw==,type:str]
    known_hosts: ENC[AES256_GCM,data:ezWRa6bSGBPZRB588cJMW1ZSZ1GyOxmYxht9Db/M6mndDEDIpmXOXzUq1GhH5rI1WN36wVvdvew/RiEI4T4WJEOmGtNYLjxi9XY06t3aBsv8KLlmP3AJweMQ9vU+h6B3P1fg+PMi53fgmFH5DC/QS1LqgjfuJnASgZezMMUYiBf0RJ2hqCFKmdt8KwHvYaIJJ6U59dEeujIiARcHq0CtDuNY/eXRwCcNLh4l,iv:+EQ8CJfh3Ypnk6kWVW+bIMACldCLJFwDWekCMHrMIKw=,tag:AUJiCXFR0CZD4bH/w2mGQQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkZHRFMzlFZjQvMmxnY1hP
            TW1yMzdpeWRJOGdwQUpFcm91a3ptU0owMlI0Ck8veXNobnhncHJTdTU3a0FoTnVL
            WDdTQ3lyNmRUbkw4b1V2QU1zeGNxdlEKLS0tIDVSaGNDWnFHNm11cEVMZWJBeGVP
            TFRGWWdnVWdUVjVIQjRBM0FSMWlhYWcKDA6cquaEVwvuTxspbC9QNd/AHHnBeyI7
            fn9/do6QDK6PWeiSzUBvZQnrAIMc+rAFuvy/Lk3K8amCYuuI3Z/Teg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-02T20:23:16Z"
    mac: ENC[AES256_GCM,data:WJynJ6wd1/WFMg8EJlqzzFRlnRwDZAOpsVEt8vUDiDf7CalLGEJEd7+r3ADztuP6pN9EQgulXAR8PMpwvK2j5E3z8k1Z4L/dz43Oy8PUSY3+tVJhaJdpUCiURBahz0dwiqb7Cjh2iu37frfrXPwdbTztDzinjqVga3Xag/Oa+uY=,iv:q2F8Y+RNytPBStbfJnPmIeUDgX5fTymVGjbzbpkohHY=,tag:gtJjRk2OQiuf/QyGRY/TWw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
