apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Ic7nRiF4G9p6clYaazbSw91fNwiwOg11TqvXkK77Dh1h9L8bc4F4b4qr8adUNpkOBMuHMKvBYqkBIymiyR+ASlja63uNXRoSMMO++xNrM6deL9NE7RRd1g0fGobWyOkiNsQC8aagLh5AT+R9R306V2B4btPTVGtsvBh+21ZgRTvfDT61MSFqhm9SRp3jayWuNhPtugRi2sebm2hVjDDYc0MeCMFP+e2+pvm1fC8vTW+sAb182Y36BHK/deW2HWHZFAdYzL7aetWzKwz/uBRQ0mH/BeH0Rp7BS4G4Xb4Cp2Avz7o2cQjVNSXmD0xdfICDohpziZdYN2vp4U6GiYRtAO4/D+jhOfpcz2Wt95P5APH58vfICW4obou4krlSroz0,iv:A23Kur9+wTV49mIEY4sBQvfCzjglky1DbIx07jljWX4=,tag:T+owJyWhlMUgG7tXpnT2iw==,type:str]
    identity.pub: ENC[AES256_GCM,data:0uQP0HqNlPxc+DSB4IsY5WxM5JQEXZeZZkfLywsk9KMPa7S1dZuSzvRLRHRDb1z7+2tNsrae32dFzGnzxDuGfxFcR2x1zFqaIkO2mezSc9JyHPNfB+C66IkJMTC+OZXYLKpNz1tz/L9+NPovc6fZxMME/nKEMpJetuaBLSVYFLp7LTn4J8lOkXpQ0MGzWnD3vkzhNmBd/edxD1Tn5NkmbaDl9W/3AxH9HrCZ1El9O6/UdXBltTdldjBmtB5Tl2FKxB/h2yNOEJim6JlPVA==,iv:+U9E0Gx3F6Ur1JS4bUDmKOg03oPxlRntbor5lQgPT48=,tag:pZyzt2PGf4460ZauclCGRw==,type:str]
    known_hosts: ENC[AES256_GCM,data:YhBGCVjnR9qsdqTmrlanZ5Cj+D3arcTrhlTm9o9jrfXnSIynXNrFunl22QxAHHzB69Fbv2LqLFC04OBdtM4tEw+Om/rCv0Cq6p2sRcojNKwoMOTQIuVymv000dtyX5241/+gIdhM7TCncvyMh/K3njp88R/CAKQlAHbB/1SD7FBnxR6mbDO+TKNRxo59Ep4FGlkO8uSbQ+g6Hyy4gTy7WdK00MDkabQE+lJy,iv:7QX8A9vBzmh6gW1Bl19U5uaiE13b/GyDglMOcKvNWGs=,tag:SvfrsueLmLvt1poJjkN/Jw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBialFqSm92b3RRRndLNWU5
            emthTU4yUHd4VU5CKytwelFXWDJPZVFXWnpnCkFzRzROYmNxZ1BJWG1EbmxuNFVR
            WXN2NFlaa3FldTZnVXNHRXBpcFlJOXMKLS0tIHZkejZxTEF0UzBiZFMreG9CcS81
            WkV5M1dNeTZDczBJZXNPNHdobisrNk0Kiv0EAMaw57LHZMl6SLvozAPxMUHuBZtH
            Ri3YD5PwAsymfHqd9plOj2MhaQ+jGDijLFGiDUIUnSvtXJ/CRalUeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T17:08:20Z"
    mac: ENC[AES256_GCM,data:Xl1S6ADfRBcvoIY7f2qyKNgOJWfNVMN6cWfQTcZFztYPnbm26YKBNwVMBYKMGd82kQ+XIXUiN0P+gQrSYCjyq0xUq1MfSTcIt1L1/DERjdgpaK5uZct6N7yJdQWwyvLocDZaqq1ziWNesyVyQVukSbIcap2zqCRUGIRAOMdPnwc=,iv:BySPgP64qhhIUA6MU9xMdU/JXhKTpKfShJSuthcv3tI=,tag:3OImTnx21lMKJY6okEayKQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
