apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:rplLLNXqNRKyzvtSgn34ot2E5I1havP01Crnlc47bxtCdOZR04bGUm0KjhW7cMMZ6Ob0iSecAqQa/UBeo3ueqmxrxCLWOV6GdKDSGrx0Tv3uiKjFCszMEpbv7P51F67LRHDg9DvBHIMlt84c7DZ9WzstePthejJF9qg3EC1ViSkVKLS4cFUDBqv5Oi2Ws4ZlMShfP5LfRXRjAClSFC1mgWfqhgxXRz9eQQ6STjZ00VVxo3P2EbZpq65ieii5onUBTmINQvhQrqNx+L/JejgQ+GLTgHO28VUTrEc64JA5pwNttWXpo/9yQ201EBcwv+Bmp3dakzGsfwWxPHXvc5ytEIV0738Eu42zx3e5yvE25LGnOt+n/9Wd8Naj98Br1UrI,iv:qfKkmhpK15PomD3/QSme9u9b4lj6ZHOGpShwFG123ao=,tag:0Q08Z/rktj3M9IQBGCKuiQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:qn0p/0dw38E6WeZTdYzk9l+zK0zSzf8F36e1GmEnoZKvPrBOiby7gWBLSbeDM5UZqs3CKv/4mb+ltxoOwevYnVaB0yawHAOCUFjD4LQ5ImBmyIu5vIX9JbnbCKcayVpSmehwc/5GaXhi73DRQ4pI3geN9lnJ7yynAahOQ/rOEiOVmkB/PNZBHEFujeJ9CSyrRTNbuzYpRGnQdjwpGOAPXXgoDr37Us2itKEloNsnPYLdWGlZ3AIYc3scwkJ5fBF4aRM774HoEPzsdi8Zuw==,iv:5V3qLvKJZShljxv0WmMZDZ1zUoPM1qkysIv9fjenipc=,tag:NqllkZ4BayAUDMnzuSMtkw==,type:str]
    known_hosts: ENC[AES256_GCM,data:YjNYUxz3C16dmXkAnwIhbYULatuHHQGPrJ50lWtzht7tLHU8Qr563XbtZVccHMAUWKTmA0bYDrZZUifQPOtMC5uXpOnGXpslVr0iaEgNUnVGZKbgEVeEPsuKSSbiUl8Vl9LrhhrQMz5qGmksEYf9d6rnnJeh0OuQ7t0ZGi0eiSAGVfxOCCv7RJ05WMrpZ0KPVq6MCpe3Mka1bwZEjCMTSC2RKbJRee1tW3Pa,iv:YFoP01JMZwtuJ6nzjIum/BjlHufAwN0yaTKXBMhVXL4=,tag:kQUihIJd06qd2EsyHzNV1g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZGJ0VFRMNWNkbThLWlg5
            dG9LQkRXZ0Q3ZmE4OXdvT0NOYUNPSWd3bzBBCkJoVEJ4S1lkQXJzblY4VWIxSmRX
            QW92RzBsUWk5Njc4UjdoQ0V4MTRwSTAKLS0tIGVTVlJXenVPMmRVcE1vV2RXYmpY
            dFJxWTlib2tyZEN6SzZLTWpsQ1VHZmcKEeWEU9xY8UgxblnaRPQlNtB5EeCjPPFR
            O6ZVH4QYBNzvf5upBvyvHiC5B0zGW5/MDLQR3BtXXn9lkBwIGZ9PxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T04:15:48Z"
    mac: ENC[AES256_GCM,data:gbncXfrAp9ijNHfKP4ysxWQIHa0cOIC8DlCZWRzvzMqeAaIis0J5nqD3qbL0Aze8UjFmmSchqzWFndpT7Qg94Aw+nj2ozRotlbWtuTzVzGlLso0AzL54Rh4mHb0+jwcin2ypm8biqilhe71YVy0N6ejAOKhzsAwB+oYPjhgfhYw=,iv:MxsKn4EKXjs+gfa835dZY7uCU6VjHGrkkHFFFN3CzWQ=,tag:8yrC2amWVnq/0VPfpjM1ww==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
