apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:QFO2mJ7PrBEOP169xvwQpxjCCPduJqtxYCEAhDRqBKh7bY7K6/LJxchaDU7Ruwj18q7p2jp4Cx/nSeHmoQfXH6woRsVLUtJGzPTFuxNkvQhIZTRAPSpWHv/6l2JJKaE6u1wh4Un48Zpfc5no5SuekCS5ihVtDZWqTG9gZAaPSOsgpzclzkVe76lYr6+CvffjDhUqzlDPq3bEHVxPz2GT0XvfKBdO0b9nQ9RORHZI1dS6Is8H4tdHDgF5/hRiWML5KUJGKrzriJdnHkBBiTqlZqMUaCziOqzHqAeQWQ4REeQ5MtPlaud5ZSwrsAiwDVaz6EvvB8aohRlYLU2ZsgANe3FNYX7wD+pARqB+IOq3rFSK7KsSKXYgT8Vs3ueesg1t,iv:nIL+P4+ArTmBGNDn6p0CyGbx+rvNDaSwArYTANVmpuk=,tag:WvHECVxheH0jGmPpROfyQQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:DYq6emio0LfRWjLI+EjbY6cHeodcul6oLoG9F9tLx1xYZjko/aO2BIZSWpOiRYJ2KIK4AYLdmwBduIajWnQfvLrCD4p56+OrPMxHMtQ3QyzUGvUJlqPrZbm+Eo2pJ6PWb+rGQExbRekDGAZg8ijXLcKX5NpFFRHE45bgYUm05xLufJ+QCDF3/iMl4MSBGS6u5VgGAAbkBS7V3jtmSR3MQZzH70YawxV05jZ9yGu6Prw47IRTbo/EsymX6sCgcpGB/N/OX7dJLZkJXRNzYQ==,iv:B3M10VKhPMoo+F74Jxkd/QRv5RzQCD10lAmy85lt0Xg=,tag:SS40ct85Q0pKzeHaXDmHIg==,type:str]
    known_hosts: ENC[AES256_GCM,data:ckSWXoRsyAAoMdmq9BPzjbxqETyaATYkkfT0YOhgVsoTqb6Ine1xs42etBWMpy3wRLM0qBTprWVEKWaC+sWfSS7FYGqrCQoeSg0mU3PMIgBepOXciBUMFwpLRcpuoh/stbpGexEtDpK+8IjyrNKJjZKU43MfBpqVEgHANFRmAkxDiAFCnoXkuthVdwyFDMNB+DFzlFT/GoLBnmMxKS8IQc3QlqnHR+oOTLse,iv:VV9l4GPukAHFmmgi2n4N2qZ1VeWsZ5CgMX/AWn2xAz8=,tag:dXHY3ifeDvn1kmbKVgOKeQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYR3R3R3ozaHBOcHV1dmZC
            TzBIb0pwbnlYT3ZUNGxKaXRPZVVkeVh4ZkRnCm1IRUNiWjlEUmd4Y0tXQ2VkeWI5
            Q3NnMU1OaVJRRi9nKzhuTDBwN1RHUWMKLS0tIDZhRUwrMFFHK3lUZldYSUVzZHJz
            MlBtaDVvNDZVWjRLRmNMNnBSK1llcmMK3w23dkIdqF0JbRJ8KTV2gm9hvflbOj1g
            gjVe673MHxhHgPVc47W7AYMEp61fqtRlidJT83iiS4Xs081uoK9PFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-02T17:12:36Z"
    mac: ENC[AES256_GCM,data:bOAsmjR08uwI0Scfr7JO0j7rCmocVCWlo+DVDEdbnz3VpYuZ2scmrsLMXL3pxhsr60XbFxJy2JmTUixH1PA8v0aUYqs8CCUQIRo8TJkkUKbDDcDkxwrGItWx0BQt0rYEtq4PDHUXEeg5teRV9oZnw17/tRsuzBfXV0n3bnFoPWE=,iv:4NGFNwC8T8epxKOSDeMBf3UHXlsA8nHYc3t5LZYB0Eo=,tag:OlFiRlNTSZT0xXm1NhrEew==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
