apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ye25Ezukq6FLwnLi1PEux69IUw5a1BI5g7t8Y9w4Ng/MGFBy+mirohEbqpLAYswpol1isqivW4TmU+L6FJGb9/qb6vUDW+GRA9cZTEZPNFm3hzK9Zw8/qSsSEWsh+MN/xLsmtEuM6wNNVGnCGwMpjzNnvc+QFIvqrVvVTtsXP2WQMnSzGpra2vRiJ10Q11uqvFGbF97zUBK7PFCkeHqLCvFfPImbQIuPnli7p46Ibqgmzbgt+MjkbBatTkdAzmSCNMcWooDiR0YpE0PFS/PWXBeNAWK2Wof4C3LsA5fxDhKODbWeosfOQq/lp6m3agVgyfxYVjdhxC993mh2hjO96v+lD5aCRD2FcyHz/Ed1MyckuUrb84jyw3VqjhKdMloP,iv:jClF0Srqp+TQiMqt2IZ4G2lJ438SM9o3SAmEBNcGrjc=,tag:aoo1/ebZlABKT+hadboiIg==,type:str]
    identity.pub: ENC[AES256_GCM,data:p5aUllyztMSZJV0FsL+zpzUPDeqrmtw5urkQXol14nzv4hQW83/O5Shq5ry+9ze9xjhukRsqQPPw2yDaNr0c5uXOLS0roTGm1GrX4yxnLCwQtPEKo6ujb4JsnryYA4gSqReo/Khdct7s1+VsSfBL/CBHI8qBpomCtUudTqEH+/6rgRuiLCjn7rERvestteIGCL9y1iEcyePfeeQoDJ0Tr+g3Uemf8XsqM4ehMM0ZxAIEs53cNktiKzJ+zghRfA80Ye3Ym/zQxqJpbS2dWg==,iv:S5xE9pUstcxwTmO5sQ36BcZUMgaOAAbh3YxplDKQvx0=,tag:vkplh8tSZGprZbCQw0mfjQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:w1ky+xFQZNhFDs8fB6fd0cFKTT1O/ZSQCPQlhFGPOMZ/PVcAKXOzNZEQlf+7vajqx0OfFAHqcz1fFzCcHeEJkmeT5UpLkoGDFKDUf7zvQjCJ3zUxq9wk8WpNeeL11YzAYvyg7R6AouTyEtSLGZoRkCrfdmT250KQbfsLLxdJYORIjWn+N/e3QeEmiUvecMkuECrjXI7/xorSmhGh3+m5uvHCeMuAiHyd1DI9,iv:9Ha6O4h0FhOEofgSGtwU9YGiodhg81RP029GFnB7oKA=,tag:oDIsfez7tpBZZhdakUKLFA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZVRaTllBd0tZck1XcVBa
            WG9jaEJXQWdtTVZsNXdmcGY0SVVRdWpHZmdFCmNIMjJRM3hLUUY2ekMwVWpBaEcz
            VXBNSDVxU0V4cFI2aVY5cTlWb3F3MEEKLS0tIEhhOGhHdmpaM1Q1YzhVeTFwM3or
            YXYya3NIN0Jic0grRjRaMDdhbER6aEkKEkKYmv5vcP3GKBjPv5TcdPVocmg0z1lN
            x1VDjLQ8Bb39dKtgsqLIZmLcXX19YrLntkLJPn6fZCegk+Efkv7ptA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-02T17:43:21Z"
    mac: ENC[AES256_GCM,data:GHseEE+zhvLrmUdc+GngwM4FmkugVlVM2UDiaJUsKamwhu6EYy5qm3weRZ0k8hSMzpzkpOKJzyuBDN1lAkEtLR+5H5+qU3xlEb2SHubYfM9kjksVPOmRKjAlKvwMjHDIr+z0TkyY6ZkJiYqkkb4AKbsQtFtA2sF4v21SEFG0NWY=,iv:t7TAGlABj9NhE+GXPtt5BYJEpzdL6r7rjUNcXuL1Np4=,tag:ebmF7RApjYZyrx66Zs6/Cw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
