apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:+PWeEcxPwotCS7oYa3Isqm68o6N2SUYXvprMJGB1MML0gWVuNSMjjVsl3SA+bkAOKymH0CBKdVpFFCWf2rPwle02oS7QEACsNK/CMYyoWngNKW5TdZNHEQea9C1jwFTxsBx6hHs9jQ5vLCLZEWiXz+t9oA23TgCq2KzgqS/agyGVFNdp2LI7o1+iaptUclu5nMomtDOPHrn9KEFRicssaRj8ntpd3dqh7WUXlET/8+maiGMfDmyxAzNHNjd6E1jO8FJy6fKjl13Cff3mX6SocoxdCZjzBCtugNQ6vhb6p17z/ZHsrJd09urbidFJALEd91YhUTy5cwo0XYjILyvfkuEz9jPgPY25f+d0yuvNR39zWtKvTBTvSYr6rFn7Xdaf,iv:hKPvpQr3SSd1BR9yGillqArJJTp5Zj2/FAasz2C5wJI=,tag:XT7+zHp4sPPmrhn2zsnyCg==,type:str]
    identity.pub: ENC[AES256_GCM,data:R0aDJQFrS+KFgLf9LQValCUAwy1DwX6qy/d7NvCxb1Cix/57XVhkLmMXKyXestoKwMgIyKkUVsaBanxFxoFNDL6m7LnLwv+0Y9wO7Hjko4idH2h5mIYSwLxqxs31KUdPq+BuEfeNVIx2kdjGz401cGPRrLhC0Qi7qfZbs3bG4EZIiVleTZkDazdJIokxyJz4CX60IaUQEap689TsYAo2jnsfT2dCGOYH+zDPTBadW4cYinIGFxsALPzkcYf3ESGeHAKtpeTMVLcnTN/o+Q==,iv:BDHBVuPEm9kbg23c5eKu+qfmalN0nZefkKbFxpmxoBk=,tag:sCEQ5o/Nm0Je5ktaIfL+0w==,type:str]
    known_hosts: ENC[AES256_GCM,data:wa5sSIs36i8NK3ZuGlmu4kPgl84G9qNo8XRSUTnw2SMD55UwJtGesuE73JsAcCU0EitjkhvtFW+7ZRp0vRbs7tHj/VWEz+le5fKgWnoseU9yYJ/LoX81InXWmYC9HtNSNEaWSfKVYys8VRYcroJ3F17qVNmRF2FTi+FMY3bhrnxUVx3RfaLKJ8fsyaMY3Wwj/fw/FCvY3J/O5/uld0U0sqV5LOtR2QVv1siD,iv:Cee4PO6ZBIAQoe26aII7ZwIfmHZfZov4q+ZlrtozvC8=,tag:1E7aEW/F/nb31C5pvEM7+A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAybDlFVTF2L1JUMzMveWNP
            Rm10YmNTaUM5S0RtSWtFbDFxSXVlVythaWkwCktxQ0UxRHNsVlpXK2dDajlGVDNs
            SHRTalViczhpMGZRWW1ocytSUGtnc2sKLS0tIEc4cm80NGpzZlcwcnhaWGpMc1lC
            TnNyL2pHN1Bla0plYzAxMXI5eklmb0UKCj8UfTMRpmD1F6E16wCB2YIYirXRnyma
            kSV5/E2n3JMC+EIHzedbln0JF4OOVzZWxoeQd8dRA8cwVq9pde6Aig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T03:38:05Z"
    mac: ENC[AES256_GCM,data:li/COWs08lphsAvWHCWHAABTPPydYIWVKLq8tuk8c1GSjixSkflhU1IRL9Y86FgG29RWpnlmfpxQHn0vguYEaDDmsR2Z4dUM2tYbbOLl1TCJ9wyQOAUy3vsc9L6weAAC83vjMMv+gjeH5sMMEftZ9now0o1Wl6FmetTHWtEvlKQ=,iv:a9JKBkbbOAYabL4wp09gs47U7lMTTwECbVRPWbBnga8=,tag:5IRSLBlkCSKVS8Gw4EVVdw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
