apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:PJ3SWLxLsNmCXBO6UDYeqSoL/oS7sRPGHc9URpmbn6kEuiCJ0PqkeW8QgzJlOKhfrNMurF4odcKpaF9TpfF7aGotRTRuNhsG/x5J65wgdAq8xIooEOM5Z49SaZSQeGrBTxlf2M7AHNHf/sRTGym1qM15KZB/IbW7LueZ/O1I2gSbqU5nTAu3a9dS98DYij8H4UGqdFSzRIW0qnhNvKD+BxAKCeKVOwtAE/+uWLFkVuOCpA93qjGfC0MIARrmASYrYGKk0gVoAaowz1i+wzZFIVhMm6g36gbOWINCRCxL8TBtFq0iGvbKuMZvIhxKkdUxOZ1By09/luF3Io1FCDhSHO3rg8deaqRrXvqRp/VcVnVuK5OgozRr7lBhZ+otCJGr,iv:c/+vFQlig25fkVCIz3m1OkwJwVe7MkYRO+eWbVkBpzg=,tag:m2NM6utS85cls3ZaLIxWxg==,type:str]
    identity.pub: ENC[AES256_GCM,data:a9dkSNRHkISr6kQgTchBUR/9XqPq+bcS5SIE8FCaflz4+PmA7iY8t8SxBwlRn2UpjDKBKLNV7rNjdExHCsRqvwHfSK729PVK2tfR5FY0sFRjsp8wI9Ga7RzqKsZfo/rPPi+bRn4fKywvqJQV8etSrwALnrByZ10fp0wQmgp5uWyietWg/HOZM4u9aQM/lMIIy2qQkG6WOp4OCKBr5Mg1xjo7lP6I8KmlV0v0xeOSTCI4dx8x59LmuwPO1RGCd76aQ8P/DcOH+8dYIZmrXg==,iv:xdNXCChFPWSLlcscQqs+AkyDqH4GmPVvAWO0T5omD8U=,tag:qDJUlZRwUn76esI/6fGnBA==,type:str]
    known_hosts: ENC[AES256_GCM,data:4VLUxD7SuDBHhocqUuwIBcC1P3K1/MJusoR4Dkx20aLfnH7Dr0HNEKndna878DN7kmKqLsGtFIGoeVNaCgEQ89IBJNuRwb4vxPnC1Dim4iJRZkS6m4BW2Sv3duEMzpSZoBCF/V7NkZoM6C3sLfQvtkMAgdclp4nrYjPX0YXcrYxhVnRe2lwipjmMF1GGUCyErwKAyvzf0j7laf4fbYM2VokhLsymRqvfxPzV,iv:hI5scnBLIu0mRexZzpuVO7yv9kOXOLirE47ABu0v4tg=,tag:UkNvEg+rc83ax/EzudZ6EA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZW9xcDdkUEw4U2YwRUlM
            ZHpLK1lhbzdMQnAzRExTZlkvMWhVWVFtbUJJCnJuNHU4dEpWT0sxR3JsWlp0TDhW
            ZnFyVmpOUFozbWZLOE5kSWYrQVpWSDgKLS0tIHBTcEZoTnlaRndJTytYb1B2ZVQr
            T240QXBUeWZVUCtxNnJ6THVCVElqQ00KdwgTKTcbS9DcLHrHkKRRpq9CQOdbilOw
            W1E38rsuLYLrrvxCh6V/cLa8X7L26lcWRPQMmN4JfQFvO2NhYPZSNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T02:22:06Z"
    mac: ENC[AES256_GCM,data:rEI2Xcwo+TnwjIeB0Qlu8IT+yAjs+EVAAXFJyNcu35CVnUthDgzzWJdHO++JkUrzXOPi7ldLE7FMNgmiptwzzvG2mf6fqnKpRDJVW0jOPFOPNAXhtIJIRDfXUPtfZ1OYyMzxA+a9KZ8piddj1nZzdRVpmh+UQeX3b5RRglJ0HO4=,iv:cizxmwHsvpFk9G6ck9QQJNgG+kx06+01m+MuNKuEokc=,tag:4ybukG8gICLukCceTTYH3w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
