apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:OF35u2cxbc73hF+ZrAmsppIc9hIpf8SrR9EcgUvWVLJlYcAv7KMUgmXVQUXSlP91ggdfOr0oxmagnDK1fvUjstfIi0G6uPy07UDNQK8vQ4DwfUWbLdtotWp6H7JDn6/cHTSfKrtq1vO+8U4rxy4sHEyxRrDZMcTodPeNMjpF81uL1s2SeHNgBpgAE5UmgCMbhog06lZJY5TfndVZIRiB5+Tsaja8dFYjk1CKc9JFHbvrhPlykDKIq6V+QP/ss/acnuGGOL9eMif0iZbkdSuGxXK8crRFtqe9IGEVu3vI8iAABgmjUb1ZYjzkLkXwnKqWVueAnjdfGVtgQb+hY22oE5P/rV0JefMQYwK9wLnL/zqkUeMykeSim1KZ/hWlG/NT,iv:sm72Qfbx3VOEl1uwKkkZviCufAhopeuDyvT9iF3jmFM=,tag:S16qM8RhJNJiQ7U28l5BEg==,type:str]
    identity.pub: ENC[AES256_GCM,data:le4xvcEgc95zXiMgUkaqmS9E9GNcBrqlP2XcOpoIdEyuHSMoTeDygm81xNwigKtJfPd9d+CpFwcyg5fUe3bgeP8d4G0PJRIgTOlzarOvZAXQhkbpKi9jiZmfNSHCfgLbU8i1l9p/SZmpm6kwsk6WJmsO1F7I7piNOodk8/1kiaQEslk/pAp6N5N3w/5cn7c2+ghln2c7x6z4/cwQT6BGBRoOQMAdmypyWT4H9ZJKdHbagzGxgGDD7/NDPqMkowZlF9Ijq+ksQqTU0PZxmg==,iv:XRtUouaKOWxyJHMLEWXEVRrvTUCwLI2j/UlZEF5b6TA=,tag:g7zMrz5KOHcbvil/fTIAmA==,type:str]
    known_hosts: ENC[AES256_GCM,data:S+24YS3BwZmDFhTUj1fv26BDThhiPFEqrb3v3WaF1ZOEfYFNW3ZZgyJYzOqDW51GRudo1bcx8am94zf8Efs9wR+Yh2GCqpZtzmdTcAp+SnkL8axt27u2j4ziUBsBIQkzaDhsnvQg2eJDZvMhr2WXIReMn3cLjs8Oei01zHBSUIiC2QTRwx2t88pFs9kkNMQ4hnEu1ecPuT981WfTsbOpp41bP31c6y7SJcam,iv:9l+gPYSdghaziEqYsn+iy6cy8MdqdlvhIuXz0dY8SYQ=,tag:3N8YRcs0+iMTUjf/AUuKEQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNOWZkZHZGRXIyOTk3MGla
            L0RCemFvOGNCNTJuOW0xcTJlVldDT1F4Ym5rCmo2WVRManFLTy9HYUxiek5OajFj
            ekFpMnpLOHUyTUZjOW1ZaFNWWXZXR1EKLS0tIHV1ZzJTMWhqbHhNeVNPZmZNNXlQ
            V3RCUDQxMWM2M1NYa2VoZkljUHdUM0EK+u0FqBtkJPiOfZpTntgA21IXYReBnp3c
            uOnEe+vTDNmoYztG/8eKg27q2CR+2eMlP7yyraOQkSLOGza2+7zX0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T01:40:52Z"
    mac: ENC[AES256_GCM,data:iOV9jKKsjJXO875giKyZj3PkmzlBikyViEMJ3GagyfAlWOOqjhlfEAo2fMHh7NI6WyS6M8aeIlfXlYoveb9NCar34N+uY33OvC74Fqk2petBChjpfyS/NUgEpGSi0mxJS50MIBLbimYqUTtLDPzUIknJVFCBqx8OS5WI7Hnt+vQ=,iv:sBV1L4b/dt/96Vd3wCPCz7X5lwE6aPKeuwLgHzFL8hU=,tag:Jxm38lul8v5edKQorwPlFw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
