apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:TVL4yZ+Bk16UuDo5UyIlgwa5PnorSflqnPN9BT1ydmz+tCQG/a8OjnkvS8X1sftBwnOtt9okQILovVOX3lb5neZgvi2pztGdAR75aq1PxjwBXekJwbl5ixl+Y1SUd1afSkYXwGuDWmM2j+TLYBMEkXJz9k4ZBuU6VElGmWUX7+PJMia7SNbUyqJYZr0Vso779Ce3trq0lGmjloIqft4oCpeviCjc9NM6LR+6SaUebVZDwcxouBnKbXq+YyGqfvz9Izu3zp5PbZ0ltBnXjrB4v/fQzLqVTbNXwCTcP/6TFOJPhLdfNOiLTRqzIf14ohQD7hudYi8nYkJ6uFVHTlW+q0W6IO5505GXN6bD0hcoraCraP5VeNJKqD2ekHx6uYeb,iv:rUC+LSRyVusZ/jYi/m3ZkSMKjpuzrUCOv0ZVr1lYlNY=,tag:V+nofxM+HYTHk1ctyxl7Ow==,type:str]
    identity.pub: ENC[AES256_GCM,data:VzJJvrmFPt4McFW6MvqbqwpR89lIU6LIX2XVwhJ0NbVBfeZVz7IP3YHB1vt7NDypPh/o9pxeKOUoFZ38Hu0sHh6OueaJDgWr007OXzEtyFMlz+PX+l3q3/813UkoU9L843uRk6HbWztagz/kh96BYIJ+F1pKoSmogMsIuP9vnETIaeASkjwAiZWqG5WDtTP+g9DUdMCfhoBS3nfp0uw58AcejOwZK5fZ63ThFX4+wjjNvLUq9pOaC1WopZDqaZMfuHPWHRIDv1XCHmyNbg==,iv:8eP+ac9GaCPQZZT7MtkShSdex9Tdpmpc8c46InSNXZc=,tag:dZ5pkjYng9pqAfV+ZndoSA==,type:str]
    known_hosts: ENC[AES256_GCM,data:S2Fy5aq0XCQwC6/go0tr1rko35XRjDbBd3KbmKz3iQyRzW2fmiT2GhU1xMnq0bGUTxBV+u1l5TPKB6ka+4jU9P54o9hVtc2p1p44C4CUs5Hitv8jBF2VW/TL2ZRxuIP8+J5z7j/R7yWp051wjqb/dY5aR0gD1hjh/RcSSw7ZBFK/jKov834f0I/p4iZDkjEwhr+92tz8l4l+xhZRtY3jOr8R8awHVxmZr2w0,iv:4H1rTa6iGdXrbWdztg8nekMbuG0nPAJasclDLtOicwg=,tag:IcFstUDuQZunFjc3hpCvtA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cXMyZUJCQWNabythd0lM
            VzV0VHhxWUptbFNWNlR2UXNHdkFBcEN1TmljCjhFNSs5MENQcGxuT2tweU1XTnUw
            YURHWWxaKy9nSnRrUGI0NEpsR0djM3MKLS0tIE1HckVVclR5K0kyV3M4ZWhXTHZR
            VEhNbFh6SW40S20wbWQ5VTlrUW5XWkUKlzZiTH1HbsJcWkdxw8m0NJ9VAz+adZZU
            aBg4xgy7/2BcXB+azLP4NIWRb4iG7rtE+1G/QgUaOC/Skl7c+bIWnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T05:23:53Z"
    mac: ENC[AES256_GCM,data:GMEhV3A/MEfimbPRoSsLQtGYCPBP5r2WUAFdtSvnnqjSipbpKppkAVvr9aAeSvd0zMZns63eTQRUEgiH4eoSOXaJyGxcmZVHemR3y4jwKSYd4bXoP3M1aSdVskpFgQcW1UDAYtLUGc3N4OtvKaGyJ3xRVKfVkx5/ot65GcG3pto=,iv:/uPfAmI/8c6ag6F7LG5cpUJcwrH8Yw9EbwbMxsX1Y9U=,tag:B6eV32QHJ8d2SCAlZNDNfw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
