apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:5HGp7o9xh0aCBGe8pqcokoqPnPqRITPPNY9ecEtLP1mNcQJasLTt1uXnffNRvhviBLlRdkRBx2+hxAkYiutD5hLXXx9OTkfZd1GaTDt2PHQ4+Yyh2kvDvCX4ZMeflMx6JDVl9yLPcnS/habINZe61iuaOgQrK6My8mDiJrsevMwT9L94DLmob8akkUVoDOHvQITGpu/ARdd6mSMb7ZthkYeuhzdxNP74mneerUv2C+I+PrMJkdqFAQYGuAt/RgPdGOpmpqfxWQvk/qL3qKzbgXYABYsjAcMKP2pgjiz5NxwNBDzojqP5R1By2y0oZ64O9+BcH75yvFARibT/QAfXYQRfy5cx4Ty5QJeOD0l16d1bblSh/LC4uzHcpCbkl6Yo,iv:o6ZrXS4fGzwqZUxUV0i7+Sip/Mh7RsOhZhiMeOGfK70=,tag:9FSuxG6TjA4bu8CaiToeRg==,type:str]
    identity.pub: ENC[AES256_GCM,data:aleo3ZPZ/QWlSDokhEZ5eUqFj5XXZTYrSXYNT+epTMja/6l9IQcE369VWDNl654SmxcZcpc1dpk1us85dZKbYUqTHk7dJNdT1KhtbLnchwwee7h2L8OcVf98NvjMVBvK3EFtczN0qyotmFzEXCJhJDS5JxqxuClZiHwsdlvkcuzAaKk2flJARNzbv6RJ/8q1JrNwh22BXubKHfgU/grPY9u3tSK3qBTnl2u3WiUUltqdF0lSfAFyw3MOkkhlMaoYyT/FpjV2V46eKp5ykA==,iv:QQ71QXOAQz2yQFRtLZbNMADaWMZbkrUS8Of/gJiKgdw=,tag:I+CDAQIWtlMxjdUS7RNCTA==,type:str]
    known_hosts: ENC[AES256_GCM,data:PjsBQDeialjsY8B/YvDZ9YdrXs/F0dFapomqQ+h7iSMDpHKk+pJgz3D19vdB5GIDHUYmg2JaMY55K4lBmooJw5ELMSzhPANrcq7v5FegAOep5UmT8GVeox7ZmveMrcvaXW7WhGThXGlVVXFHg+3C3u+tYd0eNGhYPqj0nGwcp9HIOyMI/NiRGn24TZtSut0GS5tFk3gtT8XSi6ygEu69oUv6YMRSamGYao4i,iv:XotQrpm/EkDESuMPx2e8dn+pL1Xd1E+z6muEYngQJB4=,tag:xe9lX5k4SWrV0P4LLmbcAA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSmtqNHpOQmI5SklBbHBW
            RWJVUU5FV0VaVURFd1ByaExpMnBJZ3Z4cFYwCmNqYjhqY2g3anJsSjV2R1U5aE5t
            aURVclpFcFlSeDM5VTJYNFZXaHJsV3cKLS0tIEV2WjZNdDQxWFlXQU5IZW15Tldi
            MHFhcldOMkhBVkNYd0ZEcUJYRHUyS28KM3aJLrgb4y/f+ObQhs5n4feV5dpKfNEX
            oT/niRFxbbo6Eto+4jv+z/VdjlgH/ZI9JgWJL3dE6MyCZ0GCTDBElA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T06:30:17Z"
    mac: ENC[AES256_GCM,data:d+3jmAjkslGqk8KqjhWPCCrtqpAz/nwrL3gMt0+OswVnc/9fb3+moaTI2xcosXwg/N0ffCwLdIhprs8VZ9qlo4zIEfLcsYupPlihh5fLn6A6AWPaCGxjg/+yjTMLZB4sxhL0wpWfEGRUTs4YYSrSLb32bu7HubjBrfanXA8o9no=,iv:GB8ejPFe4JDQLj34PaYA9rTAzc95JvXXrhBWcUxW+F8=,tag:d7VrBl16kMjLLtbV0oRroA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
