apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:mqkMByZg9P2lnsSWWpIUBAAFcwPQUvp7EKiHcV8DEH6kBNvtvzI3ERYovnSQN+ZQptmpWOCi+t+BWIUFoTSrXrP6TGdrJ1Pb8ep9ThdXIPbBsSY6Dl+iCD8ehKlFTVEKktHUvfEen3bu7pCIBguBT7L80sOND6L472FDdLw8D7yE/YgFj+lGp+fElW0szIH9ocXEkLViWkvvQXNGcT++ElYPcMgz3pud85e+iFcih2ksGLTImSddHJnkF1YhIp2s7gLIyVU0SrVl/fYWWzfUXKKygKgILrTlpZ2BSpPdO7QvPM5FQMWmARMjt/KVoB2YkbJmln1e928gXOs00iQpHI1y0mvRjuQ1QGjqvItw/yft5bSOjMtOPMdPyMRJL+Bp,iv:IUei+J+Cocl/LNizz2QwW4/PqHNwVRpGjQfLw9Cizug=,tag:3qP4/EAwvMOiFCUUJBuGxg==,type:str]
    identity.pub: ENC[AES256_GCM,data:EKw1SggFJpW+IEhyKl9M72go2Tw3qMxl4IM2gKKPglIDY6uwHr10MpkuAGNpNnVMD1MZxKgVLMTYrBGjVdrt7gporeOA+TbLEZ+4NxtcmHOtEPFnKMDt3xXafeI06lGG6px/xkJuLt6LaYNTQC+GmFth8ZYF50t48OHOmKgd2H1lfk1Ivulxesej5Wu3b/msoKL5HaEo6dakoyMEGiJetj6MHZ11iQWA+NbigTc/hBX+009BjB1xpNYgr7QmRKVLxCAt22NRXghw5P/lng==,iv:HJ/CwzDycPJBRAmIPj7amb1WI2T/wwnbKDll7UE1pIg=,tag:Jy1Bpf0upqBIUFYP89SsMg==,type:str]
    known_hosts: ENC[AES256_GCM,data:vHNqOYwrUdEdCUac7hL5S1NTsE4Ks1EablCx/tYPJSC/K3lo3kHVdp2wZvCnBqZan8MkKviLzfMUsgumyDTZTezZO7nEDWoNHHBSmC3EbfbY1RMRokil+/UegPOUa/kca1u3qHm36bBi7NiDHKP7/2kN58ETSkfRi+O71F7KDFc5+sWDbRF2CNBcDzWhOkB4ZWQBEpP2FKZngIowh/oZ3zPKs4SKg6Rjm4P6,iv:ZeV8ywXQ7ah0JW2sPAfrsXixM2wPBJ6EI89FX0yrpVM=,tag:QbM/yaz/8pHQWtNTgCyHZQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZHFTOE9ZYjEzV3FiY0Rw
            ZVRpZWVSZldjekt5K3BaeEc2Si8vdlhoUmlnCk1vUEEyY2QwZ2t0WjdobG9lSWlS
            TVlsOG5Xckd1ckFRbDlwRnlQNXgzak0KLS0tIC9GQXhyWk95QVhzYkQzdDUrNzNV
            WktpSys3bGQvNEM5ajUrNXZWTksxVVUKoa8KDgwVowKrK7wNwTjZ+BMVx4TOzESc
            uqp2G0EuAJisiclxFyVrBu68CmdhKZgWXR18LbbPMFQtzHtRmZ/oPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T05:28:35Z"
    mac: ENC[AES256_GCM,data:cx4zNMUTvmqg0lZMQmHqVlcOJTmHuil9ggR3OOD0dtDJygB6TyDIEFcProHVTZLM5H7uB+BFICZXl7yMaBCrfQFaJWYgsUTGfd5MZcaQ5iegFOGC5X7gYIoM8rkKWYiDxSPvjkqF4cXsyoMFaAG1DkeCAmaCS5U3Ib0sczdKHMc=,iv:gLB62z1eR3JmpdgB07GQRXSrPrX2OTj+THHHapu36K4=,tag:Np9mXTggQI1pHZ05R16Csw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
