apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:HM6Ac/TODBNZ8NiCI2jaJbA56F3htKhlPjU8G/nP/L6kyBiRmp5LprpsQDNPwkSG+sOkdaxVrNlPlnPfFQ8VUmB7i4sylmkOH0HRVo3UN0LSaJD4A5n6tVgnKkmaPrUvIF/mmgOOpoQSlR+BCWznw2kHfL6oF/59asXdspX4xk5lSvJwNKeoHQsPE0P+YU8zUK5jik/Ib1Idys7JYpyqCpIJpb3umPjCfcptChLLJ9PWKE3uU0KjFX+gTimQsPl0BYILyUc2sy1wWmQgIt4N+OYwqziAnsO39fyoCtUCehU0TcXtVNYMmQRoqHHKoYWyE9kAEaalYcpuo/lZHUDHixzEZJeVccUFGIMCPxr6rqwpbHtGRgvaBhclkUplPshd,iv:ZO/ON00StQ0pB8xNVp6vuoYOIxrhImWJRQJXOlpQtrQ=,tag:q5QeLbzjpj1hMKJWSkWv+A==,type:str]
    identity.pub: ENC[AES256_GCM,data:FHecQa1dBt8Ww2Cn9DXwIBxTxZcaiffNsiDNHIVJQFiXLVi6qBM/TFjmpJd7hWJqRQ13gtjUSt72zs4jE3WI5HjbugUc33dBrUe69UN+zTPTN3EkXfnTK7m/96R1ltDwC7yIqOR2BiwWH1+bhJ5gF2AZKivdH0LxMJgZOQfyTx+D/YFubwEjeCvzBB3PFgEYDxUTQWhB+qGZvA9DJ3+cVi8AXyoWm2JWDshMqg34YVGCChSDEjk8diHVgngv2rCBOcODDB+yv7xBb9NJdg==,iv:fCf+0zzgL6ie6tad79bgyMCQhj/qUCxCmI2i8J17GjY=,tag:XGSf9ClINsIKwxR4QR/XFA==,type:str]
    known_hosts: ENC[AES256_GCM,data:bNoZlW/XNOIXyNAmUeCuoC3xNBRPxscN79R4BD71d/ACn5eCFv7g2h3j5ftopV3cmN9uDmvrTiA97V31r8u4kLP7idnAkHIe1nI+Tz7PvoUzarrB5kGoac52yfFo30ZReWLvkkQmh9ddE7OUqB2cg92tQo36cS6eNL/NpKyE3xwsII9pZW9YInS9sT+9FQWmOIi8rQnXMRYfyrRxkPeU2HNu7Qr1/CsUN7cf,iv:9FLcIQcB6WaFGvih2tK6iXT6Cb6oqmJLRpzuntE0ivA=,tag:ilsfgzPnQavzX78rPgE3cg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5L0ZZY3ZBNmFUWnJGUFY3
            bVFYNWpZb2w5azd4SkJVQWJlajFRVTlDVkhrCjR4MDlNT0FIdUE5WGc5N1MwUHAy
            Qkt5V1FtMGxQNVZNeE1USGo4YVRwQ2sKLS0tIFVrVzRLaXhuNzR2UjBTTEZ2YVo5
            RjN0aXVEKzl5WXVONTNjOWJFM3EzWVEKQaKMeRNEewYYXqNyYKpUN8Onbnf2ijsV
            macZJ4ifhM32Bg2lvShUghfa0JQl40wzgBdRjrCIuMqUdBFzOsw7VQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T03:23:23Z"
    mac: ENC[AES256_GCM,data:qxQ89sErrP3HP0xDbs4V0DwUUIbn4kfnn7JqjutpZEd2enr9u9FZ52jdrdi6QtXJvrfPWG/AQJAA0/evHr8CTz7x2srLPBE96ZoVwBmUmQgEfY91lhuoqFYkA5zgZ+2PCcBIbE1fMtyokODu6Yogn1bLkB5vNgj7WHZnADDSHPM=,iv:pCY4ywzmAM8iy6VBRHZs6S2UvfuoUNkoxMnAy+/ST0A=,tag:exI+B5UFCUKgXu94ZhrVQA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
