apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:qtYejM/2AjIFV36zNZ3g71mOvNA2hNw8CutAJlFqAytpZf/E+E6m6T17/raLu6ApGSsPyPkxmFeEEjDxiUwaTqffwMgVem+h4uYPiKHPge+wtYpDW9ETPDu+4vV8w4hL/wcY716tKEnxwenG4oLlUokzQUmJXGKb971+aJli0jIzTCahZb+yzeNRbPTrb+jdP+Gp6wQKiE+Exz9kJ/aFdTkvteEscVYjoVJwIRZqbHh4Qn4mM0i9pfKtBtRVFZrIOZx5gU9gdz8haVyjsvjmWviq+gM5sieGxmOQ5XDUR8+QcvWrH0+3xd8TsAB1vOTiKVcKWniRzyk479/Wc3DY+rX1kThm+/sivD7ZhGEYsDK+VX2CpV+WtjiI+nqACxqG,iv:rJY4oMWXfkpurQDj2o0Q1kLnd6eZkpZWATJRjExEQDM=,tag:KOV2sDUfPxvhSqK+sRA4gw==,type:str]
    identity.pub: ENC[AES256_GCM,data:2rgFFrsb7hjcPqxE4f8uY9iyM/ahbKVc1YXadfDUMrYgK5LvwidgROAdDWYtc03F2TtsCxB9UBnCssO67ifIxz69CkEji66AfufGXc6khAfBJuDQhbIL/1/FpUYdzR70s6eaD/0o0qe2wVAgkV8KVWd/67u45gPZr5TmE+AGoQLiswxK2hR7DsgkRAcYSAVOycJUdHswBH/PJ+FF7JnmUbvNwJs0sGFrAzKUjCr8/IjTs4TAAAC2Y7OYdmmZ+nqQ+tCQdPpnEM1qaCYXGQ==,iv:SNulJB9agbHpjLofjoq7mzmdfBexew60ZWk7YkS9BAo=,tag:RrD/lbrog97BicOa1RzkSQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:rGPQLQx18QT7liDGYZcMSajddDlYS3cv62+AWpqDEO3o+WM1gmERnPArlJq/0YfkjWnwrJz+LboqaNPPGDWgbFYBwxQHqHMEK5CH6H+rcNDqgLROb5brIJgdvteM5fr3sTTk9ZccQNqqW+07hSQC7jJIIv2AVAdPtHIs5FPf+uztdaApoXd3mstvbiP9ZE4YFcPtB5IfM3whCJd87GljCybPtb9A8kjtmKPd,iv:N9p38XRdw3uM7DI0Gj6PKaEERqNX5yEFgxfCjR2Yimo=,tag:Z2vUGP0/g8kZw/54pnYatw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3eHhVUnVYd0l0d0pJSkZh
            RzVWR2xEbWgvdzJCd2VlK05pck1yeEhkSnlZClArcS96NUFCelhPVnAydHFaN2hF
            dkhGL2FmdWd2ekl1QW9laW1TdXdKancKLS0tIFJDM0htdXgyUFlBcGpIWXA2ck9u
            QmxPcEtHM1RxUU0wZ05wT0Z2TnhtVXcKcLaT6EepOtxB1J9o+2VTLSQJyV6tJ4Jd
            U2q5Jrqiwt/MaX/lcV890q8REkApNxzA1vKoob3br4B5jlNjduKRyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T00:03:34Z"
    mac: ENC[AES256_GCM,data:gqRrlAl7z+WgUyoAtkGFoy7BvU4qPf5Cm8qiCxpuxiYlb0wLs8cmp/1aXvIIm4CDeoDGO2qNHkvGtU9eDv+cgAI3qfHQyRYNhTN+UHp69Jj+rdQtg18ZDShgcIdKGKnlJHN7w6HQRghYPivenul643Ybs+bvbWdvZ3qaoxCkw/k=,iv:VwZsOhv0E6RRVmu+lBGkGe8Z9JinQsgkX1NU7ztd88Q=,tag:QTTu/M0nMhvKcFFvoFkSjg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
