apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:pNFZwS2fmMm1s6a1hFfukpmC0OgQlb40rrMZYlbY7tdVqtInm9waDIvB16xUuMVKUzLpGvqK+eAPKrAnfWzxbmG91segO1GYAwxK0QUJFko8leCa6A0Y5tre9/Vpn69zbR1UCq7B7KEFIHXqVhhWoDlaEaIb2ETemrKN/6VnIWe+H9NWT/1RPkiwtBHYPveKO4MyA8Ih7n5hQCB/18Vpz6Pnlnd/7Q1EBc+4+L3cJ+LkMk+3n9dH6ILAtYzSYuIzp6K/xkQ3qaqRjmghNvlnDJ/MvTwiEfCuZocZV/he9WcNURykI0BwxgpBOt9huJD2qQBBzYgY4UB3zxWKFgD8gpal7BhlYNEyU/epYaQIJjklIcWjTp7mswBp7/smE8dR,iv:JlazuuNKR5AAOyoqL5Jdv+uxGyi5DE/uEsNsbjTWEiU=,tag:3hh931J/vpm+CYjcSuNIdg==,type:str]
    identity.pub: ENC[AES256_GCM,data:v5TeAqB1w8gpx8dpZeVxIJ3Abele1+L4VlTDFf8kzPoulFo3TzfoTR3DuzUNPLnWJqKJpQQPDrLEFJbYdtmRQeXauh7gmSfBqU+6iVB5VoTRfpaDqA/4lWRuq/ledZgrH4xPQvPQq2tAKA8FdVhO74ZB2WbDS6ZB+IJw+JUT3BERIZer/DLz7GRyr8nj6/dxmEPH+36nE2mufy0p6CiDWk1YbwcBmUCEJjWwLr2CUAFZ5/rflwHOX0Lm7J9L7ZgLzep3PaScfYSsnw0abQ==,iv:EVa4NwQ7Q1HZLav6za82gwzqEYo+UESwLPupspzZxME=,tag:kgMMAomKOoosjbQGdjlClw==,type:str]
    known_hosts: ENC[AES256_GCM,data:+bc05j/2VnEx2KrfPnssUjBZxFbVdPjucIMfcMeOFy/BChbcnnfEX4dYfdCtwuKGlpA9otyWgRCcUfDRzCahLIGyOVQX+ve46AvAT98ZFHqq6E+gMqYmDFRoIfT404qViDyoLlom2UzilEvVlufaczJ2tjCzIHRqNohzYSomZmeu08wlRytdB5nK1mBUHi9vayrIu97G+k3nTrTFY/ecT+l4I6ru1aKOpQV+,iv:wnxSVuUtqm0Z/sPH4etpoiyZuz1miTiDcUabmreXBuU=,tag:N9KWmRBXz/ERh7tNYnB1ew==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBa2h0d09IdlVNaTcvb1pI
            dnNXbGpHM1liV0VjRDhlNkd4VEMyKzVFRzJBCmxHZ1pXU0xrdmU2UWV6ZEREVUxj
            ZjNoSGxTbU5qYjc3VytISEw1MGN1em8KLS0tIEZkYmhxbDRxK3orT0VCeGlLamMv
            V2VFRVpSeEwvWERQdUx2SzZJK1VnT2sKCaOpxA1o7/htiXjP6VDB8FFKu6N5qxdg
            bcBTRF+56PNaIwzqX1YornZS6vb4h+dEN+VrCTEIrMIkZo6vcG8eQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-09T18:04:56Z"
    mac: ENC[AES256_GCM,data:9wMeP2yie7gx7RU05KslhcpEjXYNi9XYfVhCvJcKrFurkJpebtKfacCYqVgYTprC6U5lTTnl8ykdVQOm5bceNHlfouhVe6NgmVHccfeSpER8PkDrnnbHm/ebHsdPBn8JvNg7gv0jM5bI9/6A2XaNKuIM83hJBLaJvDol1ayqJE4=,iv:gk24gQE+YOV4YO10bHqc/eqV6EnJhTxjvWRKsh73oO4=,tag:Dx9gUu6fIgRxVYYf16V82g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
