apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:nfbRALaUb6kr+5vlpuRfpUfMSdfitsF2Qo6W2P7Sy0r0C1wKF2EOG7gLHx9A8xZR5+AB3TftDVzWHUmIzW7oSTRGEiIS/ePfn/iMn8Ecmqao3uzMtumY6NBf6RD//LQ0gBVIPEgdTSmp8JYvD60+BaPPb0LXV41GCtcCLk+qXUUIyTRKMVB+y4/AeMS2R/i3cIgHHN/8Dodju/3W5WUD6owrQVLk0ERIteYXijKdajbBh6QLRf8eAQ1pU5aoUF/FSFKFFQfG7vvsdwiDk01zEml693UiWTIgMyZv7Q6MptmYLPHWg5vjQLZ3bhK1o9PCkpIeClWSsBysGUy4uVBQlD2T74XW6ou9xaIb+K2gKQJRXlEaVQtpA79sW41VJsBJ,iv:0xorRIu1K/7ZhTJ39TJeshLSEinMYRlwd/3VvmPTO0g=,tag:gpASyn8Gxpiu1USOVCMTPw==,type:str]
    identity.pub: ENC[AES256_GCM,data:ZjP4blz/yk4vMEAPLhsXdnsomMgpqJz0kMd6ZMbBGerFjcQDvJ3/3iQ2Hi8Iqd2ZG/zMMiKYoz9m8ipJ7YUzEKr5mam0fhiuTyLVky/m/SVJYAjEaBvooLTblDevsqsAS5JFpqgOfueo0/MlSSatJTHhu3fYSdMy3ho9xaE+gYe+/6ToUAArhsnRHSoTnkFbyVz+UHEIBxbltOjL2mqxkNJDVBf/h6KmHk5Z9lDALMb3nN6499rEYWaoYUQ+D+LP4QLg16VrQhWWStjF1w==,iv:nbq9TBi6r09KINCaOk8Nz4TDW0A3DpME23kV1Yf7pbo=,tag:pcvk0D1ORbuTOlzZbpEBFw==,type:str]
    known_hosts: ENC[AES256_GCM,data:4IJTeuxt5FFRs/CTjN3LeO8s8JxF5NGJ2wlnNJoV/8Jgn3c5ckQtsbyDINA3xA5RRCYKovrY7xOHv+D6H63/0qPq2Tu7mVsJQjBYW4ZB8InpKvaKH5DM3Ue40gnIEK8yW1GzRnyuiRnnemUR//F+robBcoHxopi0jribWG9IpD2q3KgQj26qa8RHmZiwODVXJI6NtxCJlJmr4MkLCP8P0SL+FDtkIMWe9czm,iv:pmAXj4d99zW8fyovRj5hwRc8qRAyg/hrMPv+4uTWJ9s=,tag:hdMMarc8L6NzaamU4lrt4A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSWDdoM0U0SjdvaUVrVjA3
            cXg4ZVUzeEVkTVZpZUFHYmx2VWxqM0xCM0VnCnQ0dlJZY0VENER3QlBVVjJTc3FO
            bDlBZldtN3hSV2dTSUQ2WkE4T0xLbEUKLS0tIC9qT1E1QlRPQWRFdndXWDM4WEJ3
            MlI2MWFaRTJtM1l5RzV3UWpXZVE0dHMKIIxv4tKvgzDcYYmhuy3RtJKPTrVQhzuo
            LwGqRILd5nqX1ZlG8o4Xu0f1vkbmearDCUQo7+n4yHFPcGJKyx0ERg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T20:01:30Z"
    mac: ENC[AES256_GCM,data:4gO7SMY8ksYN8JDcnId+E5Mlu/S6I+qbswRKjmuhQravNlbAXDywqQwubQOBbo67m0eF1DyI71ar4qr9DlAQZNec1uJ4/xKF7hiAka6+3JAb1OY1eSxtgiZmmb+02P2E0ovjZw9d3rDKO+VxxstBMLCNYtfTFen1g1P93a6zL5I=,iv:S4XeMhgy1EfPnvRjIhpm55Efi+hyFO8cvor8aDFjOYk=,tag:3wfTPQh74cQCQ7JpM0NZpg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
