apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:7C3C7tsx0H+osJtQQquU+idWy+OzmKNYvtWCyHAjf/P6pjVUPJsMc2k7PW/w92yd7nWdZaBoMZr5uxi9qKIXWUwp2cmMRL8QR9Xjy2zH/SxN8toppzrpcT5Ty5PdvPMVFKUMltFuxWjAv6hztbKVhrplcPcgWPnjvv7hmZGmRzPtUW5c2uACKRgsWaXWPn/KNbxQwM7GdFPVlH4B0sYaL6xZGAF7iTMjRb16SDVRkUf+jROHU/TlwA+Gzj6q/8VIQm5VHXedssQpR9KWbrLskiFlmFaMip9UwFLeylJZvxx/JjgK0V/wVi1kdyUG2ONUDFOUYRmBAENIyRwRXRXBtQTBlKncvB5lTXNMHmajjdCOy21Imz51/WWki2TDc2bY,iv:Txo9p9oN7rAAlalEfyfhWW3S2uFGhOZjHolAsnfcyvM=,tag:swAAcOzBFCAe7RB3sodzQw==,type:str]
    identity.pub: ENC[AES256_GCM,data:easXgOCPi/KGwsrnhSzDdLQ52aL8kza0vaXd+qJj40wHP60RuIKGK2yFA0ebaP+FnJ+DrScqMuRzXt17Sj23GEzYcwGOAbPSgijaEaAC3WRqbTKUsrAQww9E6IpEygyw8DHIqa40EeQabxBq6k0vUB82zXhH2EfTuLAkegPetK+lPowgHaifwor/MzxDLtUbfypCjFHOaKCIh+nc8W+vLYqHq8o0auyC5EwLI278XzqrSSbLmzuFV4d0GdXBc3jhV4S7IuCFP+C9s4tHOQ==,iv:RAnfTIS6FlvnXCeOfVBF+ySZB23QUy5AFFbGUbKiepk=,tag:AgDYtOokflnC/xesEDQVyA==,type:str]
    known_hosts: ENC[AES256_GCM,data:+iiteEW4MWIfpbtV+gtFQZtkU/nY2FhYp8PP52JJ8/jafAGb6eFc3YC/KiOQxKqtPQGqRmZkbugdxT7F4lvDv1ZSIWf94bHZ+2WawoB+xmY8Nn010aL1YXmjkKpdgHN5rxDOFcymLO9mFeEPPNhsBi234kS4G4SSVpGdMTAHQsmGJGLGXUEx/WlrhG/p4XnT/Q+EajwzRsM06lqulmhOiwRcMDfgPsTvyXPV,iv:58hUVFnRliMYWT73vLYAg0hDyekaqp9C0ncvaGngyMg=,tag:L5BtD1kxYM6FPp93g7+u4w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSTlF5R2M4eDJaayttaDR1
            cXdVQndlNEFwN3RGR1BaQ0k0aFo4K2NaeG1NCkZBdi8xTUZaVTl4VXdCQjNISml1
            dytEZzU3Q2N1NUt6MHBaV0FVNmN1VzgKLS0tIDQ2ckZoTXhRU1o0ZmdmOVgyL0Vr
            cnBpdGYyT0w5aHFleDg3U3ByUVFickUKuuBKfJTNiVQlZlS84Y7pFXrljkKV2j4N
            WQSRjpMecXXOYQlXYrHfxyo0B1Ff2HrOcvgxY9DmiXuExrNQ1xOxJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T02:31:44Z"
    mac: ENC[AES256_GCM,data:BX+HYZtX4W158fwEW09y/x3QCWXUMHm8tel1G9NiQ3r8Eecl/4Y9JxqV1cuMl/ZhbuMaMcvG7EWdsDO1TsSuTRdu82v6OUVUc43bXxBkjVH/iCfLFxmvSO2hyysSwtP4qg/didIGo6ajl1NfNvZCZ+4nQglaXnYMv2f3/UiN84A=,iv:RiDv+I80uIo4P+D0bDGAQdCHK1Hi91TzcCMvlVZ3sFk=,tag:w6AP39giRdYhC9UaM31IeQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
