apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:1vgBfrzR6NUOdeEDifCNKsCFGah7vWNs74dCj8RVbVsWKsJXi524xI1CUJRhHW7bmOoGFslRoa4DaCDsA0KycfdMBgLKuPw1TrvGq5o5bDO2GUQOeMQ0Tc4mjNDjHiNFTi1nWU8cAq5m6LGsok+88vYA9+lIUZRirlt9+qLwIBU3Kb1B2xQmHtSGADXVZ1fwqDUMCup+9/T6B99hIjfvhj+exzKsp3FwyZXhfpH5TUprJvyQRD3eA0Oy6ukZKJ/Yn6/2srlFuukx7xWC6Vw1BfTnX0q5GF1o8P/jElXP0kDqtAhmcbvmWWUZZLhDFGZF5V381YtqTSn/utSSMtAIWa7xTG9cxGcWkGGZF3QY4lUcdZbU3rgT28vjv5AdP97q,iv:b/7y0Miw89s6TbIBdOuFN+dEvxRKEfCRkrvZhEvie1M=,tag:7UhleLDZBQWGiBcnTBlgww==,type:str]
    identity.pub: ENC[AES256_GCM,data:poIYgN0W6Bd0pO42iFMog8QnIdBr1yu8vb3ATVUq3895ugTP6XzLDSwdWJz4BzcvJY4e1GezB+RBz1bqosXQ1y9yZ/C/meeQ5xcvMXl6Sy/ZP7aku3P7RkLg7AFgNwWd6ZQde1xXSyrGr7yy3rDLIYE6T84EXyub6JGz+zvakenhqzs1FsnGouCbj/kHZHKrOJaedShI6Q9wHhN3j4XBpqCaFSHabZekxyZLKxhBUc6ONfi0+ASN5lGHSkkW9Ja4v9D4zVdEgKILXtLB9g==,iv:828UbbbFCe/Vvw6X4x7U1P+OJmsuqCXMB4t/mJdE6Eo=,tag:MQoMSf3iur5ZuWjlXMlTKg==,type:str]
    known_hosts: ENC[AES256_GCM,data:7KgFXsju099JzWDSPoDrKq5KhSdZxb90cNLeLIKkNbk4QH7T/OGtkbxksEDvLnuTQZtcaoJ7iEZPVSNGByKxgeiYwzMRPgE3wswENbFTToH9sCtnzyfoodBnti9+R605m5YD7J6QJwfMa6Ic/o0FqxmtcsEEUrlraHKHTWGJ4eW2wiJ/w1iuVxlMkpeH0st/1ICEBfIhp107V65ToahceTs1tLvIK725ge3A,iv:ZmH6aG1WWQ3XUfATjT1XLXqu1tzp/9tu9/QuYOFbz3k=,tag:WyBBBqDDj+VB84Of4c7trw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvbFAwUSttQVpJTVhKQnR3
            MVhCSy8yQkxYbmRiYi80dzl0UzNHeTF6dEhzCmw4cGRMWjRHcVpuT1JjZStPcW9J
            VEl2YlhJWFI1NjV0NU4zWjdCS0ErV2sKLS0tIGVRZlRaVEpYY2pDWkpNQ1owbHVp
            SnJhU3ltNGp4a2hTR0QxZDNRbXk3T3MKDeWdB89hMIVbO4sKpAWu0WeYX3tRTIpk
            qKLPwUzF8YfUM4EXwmwQ2fM2bIg57tX95iJUylVwwZGolf36B3gLVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T18:53:56Z"
    mac: ENC[AES256_GCM,data:yHv23nfKTPvFe3dJ6sA2zdydCQyRa1No+BQQf1/ioAs7xQOySVk2tZ52ZkegTYu5/troHAX79Yek6o8pvjTFnK6Bd4GhZEyE6rzW0jgQRJyDSj65J/1nq9PRIX5+iLxGbUrLZCwPG/akRzfQ8XB7ZdV3ULvenSva5nDJORusngM=,iv:mi9gj+PJkCQGgcF29TtH0vNS5WUR9M5hTmuqzK2VY/I=,tag:xV5P9keAGN0IEQ3ElXLd+A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
