apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:6lFAMAtbz5bl2Y6eTG4qyMtEVD8gESGlsEoNCpPruU9f70nUf0tji+dHy4QnDrscPW96oLHAbe7iZefipaSQpnslR1letIGcL846U+BREjJze0W1ABAyPtw122CUTIUHV+KwsVyWD+r+slZ9bKVrdp00i9r4sRWycg6YYECKtfqxX6/7rAADGQYNoOzs8xWgVljpDmlKT7ifLIua9a5so7Hi+i/QTkpRcwOxYu7Ced5zNP9I0U27S2Ojv3U2fSuQozaYBBRPKDt1RjUX4XwJj7LuCV26KxXeSax8w9WeulK6PrNdsXzih1Mu2v0afD43ZaDLsK/mEzz5KiWwbu7ilKJzkfuZSJT9UEzP0IfnuLI1DE5Z8pOHtGEYp9D/nX3q,iv:0qBkAZkMCT/UH5IsdmzenWwEZSlNBdVOM3O8pVHmTB8=,tag:G6LRtWpcSRFZiVwDjPERxg==,type:str]
    identity.pub: ENC[AES256_GCM,data:nOEozSOtH/zx8ShUWV19yeGcUKYwMZ7qzJWD0CzAoJZ+9ZJAwCHxXHSV8vTCTBxSgddMTc9S3JJs0zRfHThqzSCK8523kB8+bX/QnqPFjgp0d5tr1or0uIGSuY4nV+p3qbJ3f1knvPac4AD0BN0O1G3Uk/jPJiwgylMyMCxiS/b4ZKU7pNrqkCOI0k0ktevqjQIuo9PQbqvJ+Jd/MfRrpfMoDZGJKqHaGnBWq2vl6lxDGEwgTXkh7WINiD0UfqalIL2QhNru/mM4EyXICg==,iv:oJNjImAR6o539Cq7bNwDnwAAQAfc/WCmQKA9pZ0Hxek=,tag:r4qEaTBaC9Kbx4Y3rNF44g==,type:str]
    known_hosts: ENC[AES256_GCM,data:LeV5cdM1svRmsWu7SOjJPT/oDJEYt3S5YQQg6kzn+kdftaptWQRk/CHbau2TBGt9k7/4cUnorH1j1wd4h6m11w1cKniAPW7Q0372zdQ0Lk7BST1QFdn+5VajuVy1+MrVz1hFEJ8yK70A7qlUme2cR5l7O0Wufho6jN5vjpqsoqAv3rGXOsuz2NdGuHhQC2xaDYTy1F0fsAf3cSsIxG3Mw4chM194kfl/CiSg,iv:W+kbO9d5nGUNyNgrB+/350Pcd+oZCAo9nYJ7HNgS2lg=,tag:IhFgrdvtzIu9l+pGLklreg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwRmdmdmhQNlZiRTVZaXcz
            Z3BEUDlLNnlldlFXZ3hHZHU1ZjZhL1BBU1FRCjVZakN6QmdGakduYmhteGxRVnNK
            c0VVUU93ckE0WnZZNHBKNE54T0xzUGsKLS0tIGhta0ZJSFNNK2EzcTZBMWV3S3JD
            bjA4U2E4NkR4U09WcDVzWlhpNlRHUzAK0HFQHRtN7YxUCLLViN5KdaX2wkLCFGXw
            Hx7nHbTObYnmMi7C78oan9wgYeRS/O1newsKd5zdIjLzJDfU6FWRiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T21:34:44Z"
    mac: ENC[AES256_GCM,data:DTf7L9D59H/swT/5/j8o7HJd2Vo9aHC+K3jcOIQG9Pb/hgfoZ49ro5OM9GXRaJ1d3+KajeYRBt9VLgX4S7/DLXjINarsw8XaLFafuhMS7Ng6cJt2WjuXu6HsNxn/pHz8fJXbI1DBamrrNuYvXq9XKi5cQq310PrTtt4mC/Cp47M=,iv:9KKjw1NGXzsc3v0FOhNaB/lX1QWP50mP09vhrbVJSRU=,tag:V8YHDt8vIQUZ5miWlhAvEQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
