apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:4wMt3Fp08eW4oka3KpwB0791Qi9YGYYFPh27EdxktT4rf4Zpiu76/HUpdv3cst/uPPQysxENsBY3XxECtxBrgoK7vBrT6zUHWizW+xkV3FLYfQ43WjIAZDj2Pfv70tKw5LfGGahZp0pz7cqlYu/US2WsKpnhD8B33oKG/iKGG4l343o5/FPWR3UsL/ybigKWPwspbGZ/iyTPxNeFeB/9tJSI4TJ6Lob2QWn6JRsniRcSjnNiLR/bVomHZAXOTMmMPBkbA6NJYASnmxj+R+PJYKh8+1njsnaCVs+Lt/bHOkbz7BoOMuOklIbrY7nQOtMt9jFtupPdZyKxWSWkza6aivfVRUWSifk6wbDjqH1T+Qw7ajTvLQbYgiaEeTejn5H8,iv:HJ4TGMUUI18J74eGe/D6t5K0yuWwPmLFpiZnLoc1JPs=,tag:txCFJ72hqXJnEOEI1WycwA==,type:str]
    identity.pub: ENC[AES256_GCM,data:WcMJIwmaPMLJXj8zpE/i9FDddQ2L2mXy1tTEkX50O5Ib5S3bR7VjvZu9qzBYdUNggkVGXewSIwnjegQfmd0fyedfw5OMZpE8u2l2BaALpvNk9ryDRBVXWjfU9ZVPtS60aNFhxA6t6Fy491LsC6pMpprheJkpzSXswsVwwbRkctDaISUbbIfk0O7vVauhFKLCMPpYei5Djk8I7ennlh2geOZJgSMdnOBc62k5WLXZWFYv3MS+ClHFw+nsgwSci2RFM6B6gkOeX7TLq+gKlg==,iv:1hMXIS0K66uOwAaPs2BBOAdwqpK7kzoCvVcEEeAGkCg=,tag:nSf9SoD7MX0r45oZCEbwRg==,type:str]
    known_hosts: ENC[AES256_GCM,data:BlUbvCCBwkuidU2ZaJ/TDyWjKcoPI41DpXaV0daxbTyaqlJHxOy41W8V6ghMqY4snGxfpuGL9iZxPxJo04KTCqaWK5ffqNMN7vQGHp//xehdwsjE1b56dDPq+2UBP6/5ijHrDGNGF8UcGa/k2GzkDY3so4s5yP7uw71jgmC+p59V2f9uCRN3gMHpxpumWjEsfbyOwxWg3roffy76X9mfa8UcBsYTD8dl84HS,iv:Zxkf4ejoITBd6nzz4qZXfXlGQ7lzJOutCLpUTmardRs=,tag:RGuPNZwNcFfxjHqCpNFyrw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkc3l2dE0xWHZFamphckU0
            OWxiTlNvRzd4U2I2T2d1c0Z2Z3BzRXZyS1ZBCkxlVnpKcmM0ZFM4VlRmQ0d5S0Zw
            bmZJRnJJbTFaVlJkcytmTkFXTmRKdmMKLS0tIEx4RlFKNUhPN05adHJnekNqcmFS
            djJNZnU4RXBsR0U0Vjk0dXpyVmJCVmcK+ovSS64PIBxchWtEH1xKtFVAaKGL4EVg
            4wdV2xM2UEfnX59ZzZSfDPEqGy1oglf15CO6GSEb3EgdU3Qah/Hwqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T01:57:41Z"
    mac: ENC[AES256_GCM,data:UUaTRcUueDpPnjfWST5giJSR2iP4SPbl/mrJfWqv++RGUFL6IkqiRuk39l9pOkIQvd6qM70Nm7KSin71tV8e9XQgG1H0wGV4/LA5hH6VpcuZdnWBy1R81wfhyS6vieRCQzbgyfPhvEYpIkyHTaZ5Fmt4bU4p1nK/12SXgAo/daE=,iv:0fUi2/eBhNnS5fUFJ4J79ByhPutj8JBHiFHVcvaFOTk=,tag:ucw5p8uHDYgtP8pUrCIPPA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
