apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:iqm1WDxZvt56ZqqxOQ34ywnqEOYOzlIg6cHplJz/hlvP3VqZ3YWcGIHM8ByFgDHlYaLFwASzjzbYfKSXn4FmT2H1xi8/WCBLo5UYZr7JajKzPezbttuM2ipqEHUhajBTAAEtAA1gloGdeNG+NsgP+bpjHyDvzihlaRtlfXB1T5ljekXYCysBkMRoCeA+8lA1rG3vCBZqKmQf8iUidQ082g8aVtJJm409oaEDJKOgc9prdBA+IqvCFWliKOdTZ5cWJYIiDja9tsvslbYorQTtM+QOoggAv2H8+C9pUu3tqT+ja3LYtd9wXqsCYzo5tPrVoJHPyKtVV6HQKTf3Ph7eUb1emS9zYVCqJ19ph3AM/lQT54AHquHn+Rmkudoly6LN,iv:GRwpLGSAJJuezC08donnSEWzi1G9QUntsJlabUHJRMo=,tag:6IoRYj260k3pf+W/9LdnGQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:1qz+QWBVrrfjj7NcQqDf1x/mPsRqHzQ3R0YsMHC+8GEXS6RFIVCvwIGe5Ux62IRBQFfrLSwoQ2HVQxWvJYU+Io1yvrL8Y48ALkj5poKm1BI/vIkMZj3UVOpCunQbquEnBPCCYdf/vd+PkC/DWc8z/LpBDxyJwYWp8r9+vayKiZ8M3EkGu0SFti/Js7okgjpaMefGAIOOmXbgNGv+SR6vwmZU8gKyB4iWDonhL3gCIELWRevNe4+4/ys54ZcjVvwuuNK0AcZTNvRKisL4yQ==,iv:0LhkzfYghEjLHHXzk9xpncDFq5+mxUky9UeSPNDBRBA=,tag:aNASursFa2dJJOmA7d0m6A==,type:str]
    known_hosts: ENC[AES256_GCM,data:ZW8ImQOY3UricolWOyPabArE7YEvNwcyjhmU6CVRw9Ho9Rnpu2+A9ldsHrGGaxaBAg3zxHnI6zhxaBzuhrlsSLC52Z4OXhvKU+B7PmgN3CH1bGimdIQ3WJQ/Ym/wAv6jKIqnlY8EQMRWIiVbByaehM+VbwtoHpbFs/Vr8VS5Y6QTnSC3ED/FFsrsRbcbiGSIvgAHs4LtYG0sC4M3emWkU4bvuk3KcqGhE+dL,iv:+C57XzOzMtj8V8+pf+n3ID/V8e/gfZQSZFtsZonAeO4=,tag:e1vxkYP5vcIFkWJgBeht1Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDc0pqZzlJQllkc2VKTnhs
            L3lybTNHaHBpR1hNZlJZTUlaLzZhcHRFZ0M4ClFGNFlkRTVHQjZBYVVXUWg2MmF1
            K0k2anR0M1h3dGdGU0lXVzZHeVIwcmMKLS0tIDUvQjdzcVNMYkVoSmFydFRta2M4
            MzRkYks2ck5jL2I1ZC9PUVJ0cFlDVDgK8YxgPk7Mv3Dn/8nBpOS6Q+12qtvjB7MN
            wKlLo7FHlmk3R3LJZXR0CUEscjN8EOJCBjMN54IozHOgECwFGJwCWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T21:44:33Z"
    mac: ENC[AES256_GCM,data:YOVlGbjaUfYIJgsLbWVoBsqkuiapbiM8KajCvZLEyI5do0fgYQsTfgds8ql4PHTA3Wz9VtwVmagjsCZ1jUtm0NHWQxBmfYjQkMWLT/zJKeSTLo8x1jyvqz388h9rAmt2V8DZG6ZU3M3ALah5ALxuXq0rMI0gvxvLHdPHssG7pWU=,iv:ShoqRtPZFpkb6aKPKym0ZVyOZwUpnhaLXV9wtTRG1EI=,tag:GaxvXc53xIY2j8WG3oX1jQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
