apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:nNTmyqThxNfoI4prLLWGBdSqokRNIZsBOFvkXdGDEUKdTbXdXvhGZ1ms9xUhFdvC1Kffcm1YxbWiPGF+g4UmtpTr64WXP6H3pk1MbS7BGvDSguRffg9Q5zqrQN/eNh2UJz5ogxcNb4V5qOJYKrCVUSUhLKcPmAKQLYLi7jcK/nXgIymEx3CrQ8xepu7JJrYR/sqmXg4U7qUlgp40PTTSPrFOekraxz531RSqxVpNjSGe18Z0I91GKI6/0eByI7z2fIaGDL88iEkJGJF5YIvy9fcuZ/ExKU6INtnwDWbTQwSNjKbHZ+/HegVzd354z29DpMeMWpWjjsTjXC9Ggm65jldQEW2dv09/8ASXl78M4hx8FkkPJt8D8EEHNuHP04TI,iv:x9j8Rt994GEQhajOYC/G8X1UjvOlDAWIcvD0L6Kzmow=,tag:eWsASy+IqvKLXvRFPlbSdA==,type:str]
    identity.pub: ENC[AES256_GCM,data:ZQnN/zgTN5QYxi5gWft4MlYNxzRjlAFXWp3nhTLd3kZDLrw9veckbi7ciN/2p9qt1Ed09R58tpfRxChpbzp35g6Aln/FWxvptKbFIDaa6VjlDWatt8Tj+F+undwwRh+R/7t0DFVQPo8UtDMNe+8qMRqNzX5Hir9N0cjV60yCKgv4HR1DpHkj04nowM7sQ+JuZaAcesWBJ3XYBkeZzxMk7yVP5Xceol+HBlQmUiLcknh1AkceR7t9BoOhhCexcXoZPdTz7ZBSw7nU1+RF/w==,iv:wpmLVkp1Gs6xsqwrYiwimRk/edP2XF46eAnHmZ3XCpY=,tag:mSoPv7CKQ7CHIh9dyQYu6A==,type:str]
    known_hosts: ENC[AES256_GCM,data:5G7aIYmN1NHsUqRVrzYIBDYjU6TlMjHzvkE9b1kEMya7+XStayM0JrrTixfG2KWnGIgQTs7gXGxzrZ3ts8uIFwbLVf4/fsUGupWhJ2nCdGu/cgMuIbXVNripjNXY9c3aGC3MFK3LTKPmqcYtVIh3ScuQKPWRNv6/dPJWm7E6VvDRfZV/PAMB0D3DXY3D2LsVh0kMuALhOhWSNi/XAZgpk91LjupyaZNhg7fo,iv:QzQRwbLQc+V1mg+x9Vt7uQ+fj+kCNWJyDPF7yv7V7Rk=,tag:aCYnzqxD+RyenHxXB7OhLg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxWUR1WnkvNFAxRThSQUE0
            UGNwdFo4SnBYU1JkUWo2MXRnZHJkeFg4bERjCjh3TG9EU0I0ZDFtbG9UY2xIcGpw
            RFA0U1FEVHE1cGQ0S3hNVEpCK2J5bGMKLS0tIDlSN2VMRnJXZHNiTkhtbVgycjJi
            MnRYdWRxdnRUaEZFRTg2T2Y0dzNldEkKboXC9gIJPnhwRVuqyJ2gQmJnKdixrX5n
            Hoq+ms82KgVWJ60pMJ9k9+T3JSVi+4QAmQjGQ/hKPKmLwx7ZDGMzaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-28T13:55:22Z"
    mac: ENC[AES256_GCM,data:9UG1Lj0jyK9eZkIUuqYQvz9LvvrjnM3FzrU+PUfvGV+15OVt7AClcY1G1rnWSqxaq2dceyK9A78tOLKiadndboWOS0ps0UAetK1qHDnOFut/o6JaIlw6Wve51qbdmfvCJ50qoHqDANT+TytQgKuP1VY9tH0DZ/UwYs8XRqf2mSQ=,iv:jPRo1q0vefFOotJJE114QEIT8exdfZ+LP0qEfocZ9fA=,tag:nE2jGwtrb2JJX7J2pdIjMA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
