apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:pyZosmgKHSeOvXCKVszmlPN2N4GG/M56gk8V4WvTuWZajGJIJl5jEJNnEEWkyV323XntWPEXznaL3Herh/1CivMiabE2ovyXoMjvIcwJUUaZgFz4PaoBVqK1G5U/s7kUYcGP+WXl2cjkGWRsgRKS4ntDIGMtr8QfkC3O1Cvue0ulsidBn9dTjKo7Ab/xVM0LBOAPZ6qkFq7rgDsEXk0casuHUsa0gozG8rlA1N+P25iBVBgxuJpFz0twL1WKhChcvOKPSfXunFWGZgRImnTSlaz2mfp+hET81T9+lzHDRyIfciTLAQbFH6GwrTt5jLqZB5vp1w+QQTLi7sfHvELLbJbO/fnrvXyvvFHUgswJHLrzy86jnQ/Y2YSNssieuaFp,iv:C1MoyxLS43MmvnlwyPnmd9RV5oZ8VgymwNlUslLVQAk=,tag:Re7Tu4p+6Y1lXzh1tlVQMg==,type:str]
    identity.pub: ENC[AES256_GCM,data:snwkJF3t82N9voXC8+0KtjdwkbED34ZlqUFINobwNOje8sDpkJqhjSUHeVotAsHXxZLA1UI9onqFY0EofxvDrtphzoQn8CfrXxJly+bKeWZHRopkqICvnXAoAeBeP5ExtJpNBGEXm4Z2WyeEcFreXKzldZ9Sjwu9S+DZfML89aG+PzSj1bOUTPgnWMmUq8IgqzV6d0SEM+aSS1U6ukcUFRUqOTZFwG4/KfzUFyRFDqTYEP/pxxVa59LENUBbcmgadvK4gC8JRyQP1lWsFg==,iv:vX4vMZ2p2v1wgesKaZGKhEkIgk/9preT1ZL+IOt1vSE=,tag:1FFX15iEZWsGW19+Bg0rFw==,type:str]
    known_hosts: ENC[AES256_GCM,data:YIJNy/NmHcL1fuqrkaSs/i/lNo8g1wcdJkwRUkFt583Aio88WN+XowP/u2boAjxejMww/q54IKd/ZF+hAWiSuq3Ucjb57UyKLRk06NzeXWZPP9EGWdCZr6OrEBkfsR2EogYT/LfZwM3gAhVpgKPxjc8selW1pHusQxQ8czxqgz0J2mRtqP2YnjkcYKkL6G8sNcGltPYc/gKHNpyBv+p7aZsycbOIpg9nBfC4,iv:tW2V8ZcmZQ4ciigxG/F9XeeMFYJN8ky0vH7TI5DoDr0=,tag:2m0DOy3xr56aViARivhZFg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsUDJNZ3VXbCs1SjVSUWs0
            ZDgwQldBdnV6UTlpdHIwUmlhY09aakxKRFNFCkVISmNiWExncmwrMFIyemY4c1Q4
            KzZZNEJlMzJnS3FFcVBpejVYaXJ6czQKLS0tIGVQbWpqN1kvV0NTSEZpZE5YOUY4
            QjNhbGNFaFlHWEkvZXVFb0xLKys4S0kKdRgk7VyXEumwwX4xlXi14mWM0byL3TSH
            +2AcOKA2NLOy+gU6DEwg4ceHJQPYHPSYs5RqtEEkxAVKaXaqzMmElg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-28T14:28:39Z"
    mac: ENC[AES256_GCM,data:TlAZkF5JQIN/adiFzymIRCylYlUP4jvZyWPRBlNL2ZQpIb9la60ymVtTpv5iAv1u/ZZ1VXmQ/wtu2FE0f3S078GBrbLvTm6yCVXAYucJOf4ryGDPrYW8Ulqqg6B7NpIc26/d5F+Dmvlg8FFJwX8Kz4nX+SHkOwt5+IiFPe6kZTs=,iv:EM131I68KnAhIXvTxPkz5d891Yz5rtEtQTWyWeXcAVE=,tag:5g4ZP2a80LqkB8zsLD28XQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
