apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:b/965xfu76JioeNyc0TqNWfXok2Q5f1SnBslcv7cawh/aMb8WgJyPRJGxjt8zwBeUZ/Ww1qPFmStb9aOr1TmB00k4nJ8O3Zj56gVOYnqOkdKv3AEZ9zSBQoLNeucZP0YfkigdFK3r3BUXdedDO/CHnT860Sg1vAa5clgZPyzVB4JXkAZE5S0DtD48+UCyCosKxTCECW1kDUKELSD79M8KYQWvfycrcWQ4Krts/eT7xy1LkddB7AVfBN/yIM1FrepvLG89GZT+BWz/N7wO2/+MjIbuJeYiWD69pSUZLcqP5NhbiSSRIZrzoh24pHx5v1GI+dPAj6qwEP3cpqO4FL+XIa2mnobcU6nzV/OJtU2g/yY4KV3zI1ijLMOdw6OxVyr,iv:CyaeIw1DTMJZF3bKZ7X0EoYgo4XJphxlANvlZvn1J64=,tag:ArdnX+Fr6diHdTSzCt6fBg==,type:str]
    identity.pub: ENC[AES256_GCM,data:CUt2XbEXdH9Bj57ok/Zq1+prJ32CxTdQi4Gotc21vkjnZl984xhltk/ovQRetemNpK7N9LzidUZFdlXDaOOvcRYwlTo6QUSkCxJqOsDuojw6qc7DYOBoWPHqhGL/EqgXDePJZAxNno1i0iZeRK2VenQLSudGPxWCQJsu6sSJ0qKjkAS6w4WeMd2gMiff4MYKInZ+7SI5LKYGxuoJR/GSGAG+pM/EThAoOGcRBUZBRVwFTzILPEGTX6HihR2LVPwisbM9bdnpl5XCqKvCBA==,iv:SJvMNXdS+aLz98kpwOHxMw0jDVgZSvgDzKlVEpPDtYk=,tag:fUg4CNRy5eXy5t0Tc7xqvg==,type:str]
    known_hosts: ENC[AES256_GCM,data:aLPrztm7sZOS7WUyXJyux/l031ixaw6rNHCM2dGeH1Gtj0tgzNkDyfxOs1eEjTA0hM6XWLn0wFBsEWliRZBg5t1NdE4XrIm0ww5g57syp+gPrT1A4Sj1v7J2bm4KCrCTdUdoLUBMsc0JWL6tuRBKKoOxtED5eu8d7vYXWrS60/+WeONZYWJVR6ijTuyIjM9ffZEDc0rQsp9Lau3gpVbRxXYIcwWqAMH+hRd4,iv:mF4zYIxvpixRyarsUjeeJYWSAec3ppSKeoo5uYcYPkM=,tag:I97LTg4uvCICmyKdWDTwWw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ZmxYZTREcUlpV2lyZzN6
            bU9qZThqVmFwYUp4VWFaL3Erdi9OVWMyQTIwCldNcVJwRENxbE80bmtFTkhWVFk3
            M2ZYekllaS9mbU5iYkZUZDZUTFhKVFkKLS0tIHZRcGNxV2ZleHdrMlpyMTgrbHl4
            N3kxc2V0YnpCTEp4NjJuWVFJSW5Fem8KtkqgiHDViTGHLusEPsu/XB21EZB1L0IQ
            M/PuIghsqMc4Ngv/7WzpLwYM2MkbFoIMA0r0dRVDQQnReOyDUi2d9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T00:51:29Z"
    mac: ENC[AES256_GCM,data:11WGK7rBDQezb1PNJeHb5VJID8pUq3SmqRPyoHyA53l0+vHKiBDbiVvbwyV57vbgPCWbc+6LIn4jv5rQXL+uAptEqSFmWoe0qNUGHPaSKahg+JzFkIFrT49uHEHmS2qi7MLaz+nwK85l7jfhv74+/N4VWszPSkkYjEPt/J39bYs=,iv:fRhvG0IajxFM0x4vw1BPaMKo/15T3JZbkL4PTj1Mcbw=,tag:0/vt9T+Pj2vAyURCuAjJpA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
