apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:nRSNf10ECmHqz7a35RWJJRSga3CwjIWjqv1wzhYf3DxRFPDWckZA+VlIWopU2r8SsI3BkCy5FIcDgixMfwYIxcNIsJy07/UsS9pNskaCE0KpuptBHWoK+srKH5S3Q/ghrA9TfnBWpLHSIrmsyk1mXcGTXuiT1Yx+bSrcOZ7dkSAKqO0bLKXC79CkOtunQH0Sd7fj+mXCZo4KWNLqBvUFD3mFh0HmZH9opwy+lqmtD8tZ6HRufklW5bevsRHIYB0QOTOULkfDGnbIM1xfpDmfwjraK0+zQMj5AlqoDAl3KIxYwQcWVfEW7XLPTGtELhw2T1QKu3YynyOSXbJsPVxNkMmvMQwBsOSWURVDHL7Je0bAa4FV4bbfvHarpiXU3FOv,iv:SO1buJCT6ehycBgmrKO7Bn6dMBV5TOB7pqTg8o7vstQ=,tag:N4ZdRkbaBcak2xuYniUypQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:OETXPEaTJwvi3dtQdANFtaFBm13XkgKUhbWnCdAC54bLbYHUD3bEqkDNP5OJYwR8E5SaD1XXst2g3WLbmb/P55R03B9nmpbGZU+HoiPN1HwS00+3IBIpQuqA/q7WFlCrgzzfZ1xU3obG+23/yRbs7/gg+w2unag40D2tGlK7OKY5ZWAioqkQ+mRCrk/mZvDFOPulrMXEgHsXERm5NaRPYd/sO4hb/Hc8NA7Tg8GvgiHKJ/i1NXn90eHHMtsd8BloflQZL/Vs9XOP2zXFGA==,iv:4h7ArE5L/x9bvZ0MRN0rABuN4af3PqEJP4efxB1F3+E=,tag:YbFa3Oc7jXyOOIzj9a5GwA==,type:str]
    known_hosts: ENC[AES256_GCM,data:aFVOrykHGy5qrYrZXjSr0kWlwEXTM2CqN1hVKBEPOHVg+v4o+X+VMiax5wqiMhqSyFKqxkeY2w/skx897+uJXBFz3qHhBAo4gaSKGoXpPmaB/vvLasoKf38fqByoSPuUh0zdZHB36FYfHagbkcqoiynsA6xz3cCbaZTsfaL9hpWjf5Akx1QY7BBDJwYZuoYZwdkgnCQMiWXHKo4dxUGe2f6sppbYx0823UJn,iv:PssjJngpFSODEquegZxyINOAXdxOZrMZBvWlw9JHSuk=,tag:rC2oncGEDgNb3C+ESo9Z3Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBRVA4eDFoU0F0WXMwMGV6
            RzN3Y084VmY3R0Q1eFJKcVJ5Q20zL3NkRlg0CjY1MWN0b1BTbHNkUXVNdktWU2cz
            czg0ZnpwcFdvUFYzWU1ISGhHWFgxSzAKLS0tIE54UnRrUmxnYUU5bVZUTzZqTTZ2
            KzhtQmgyeDYxWU1YQkJEa3BwandoUlEKvgFpb0t58FRN8EyJI60Yu5ebPleHZX7O
            /yRLg/48GHRQU2RlC3MeXmcuiEi51FNVplSjzvXxpIM2BQzbKa4g0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T12:30:49Z"
    mac: ENC[AES256_GCM,data:FP4q4+BOqmcWNS1IZCcLCdot+pS8zNatj2giBP5ite+P9OzysY/EgeWd67s0I7zrpiTENRf/B25uz6FBplpSKi3FiHNJ2K6io8YfbGu7A19hSGzpX7mnHmJdoMYdxGv9xMU/fkFihNxD76S/wFAJjuary3g9TrINZOzlc9BGByw=,iv:INDN97GpE8Gij2DWkxjqNsU0D0kOQUxPKhz7cybI7Kc=,tag:QvSi8Y2v7o10Rn0f+KFV/g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
