apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Dqe0UWweU/1edBjIbZufAuoOPnFjQFEHwjBf9XlVfp0e+Y+O/rkQX4eIftUhIVT8c0OzyuS0uMgsTAmhbaE8/Hs0Pa9SiVhhn0uS0DnYhL7Jalw8C+mYnoR3Lyf275Sqt1R1ZdW2tlbH/s8faIRhqbQPHhuk13zrOhmL0dEB9rQqGjqZpx0Ux8vW1cA7pqobl3bdwCfnWRWdr0m9PSVrTVvX2m19hn9uU/81CN0GpuCAQMbZ/Mp8akak+cAc5XASxCeuv9+6efggPp8iKngXZz7/VybmXRLFXZXv2wi1DXLZxMs9JGhwNttkE7ksyVVVx4yIAOsFN7FLi1IGHxOlVCeJKKs61CIe6z7pYj6s3jQ/AgkRoZ6g/NzGkGCvvTsQ,iv:6N4feSF4eWjtI5JVkMiuljydbgKeKUfBDJfZ4b/74bw=,tag:jCozoc7fpNFypq2c/ORp6A==,type:str]
    identity.pub: ENC[AES256_GCM,data:vCRyFaLRYpmdNcSrhkLGsCciZLwxHD6p7unppU9oVjvkii8pzRL2LlpfX00LnZJ3UQgI5nUjL+ksIU99/KaC3Ik5ExHWU3w5LzNh3wqtvDrtUIMSnosgdzgg0RIQNcGcx/i5w6ixu+lNiP1u+rX/DSaU5Ho3qKMquGi7jqkwpJQ/v1fkDTKvMmnGKW7QpSJt4QctVKbbiYuyUCpSMfbqVHvwZYBU4juM08A5lZg7+AcODXTS5G4rPviMjNlS3Mk6Yoo7kBW/0SIJUaN5jw==,iv:MqKt9rO3HHo0MY93kk9GQzAvZItEd+xOuwzUdOWv1DI=,tag:TjL36pCGLOPMLcQA9GuTwQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:ePb/6XzWD1Vv165TbqjtoGUeXZRD+GVSA/zTxGtTjm7yMyRfqDREycYZ/Alcb2gvSwTuxqbbMHHtKj+kEJMUt8fioGyuXEaMwi6tyxEb2ytvi4F21V57OBTMOC4dcYBxf9JaVW/dJ9fa1hx7nID2Q3mcGtUhZSImVzR0xTkY6A3G2V+28rN55s0zXt+vB1XIj5JdwuiyeH0FTrjtICaL9EcIui0fynM9Ltrj,iv:KUqBrPsYojHMxFPcsiarm3M3Fqrq/xW3IIxpGUqM12Y=,tag:q1MD3cqNLbfQCKhI4FaBuA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZ05XOXhEZ1lTd1JUS0Fk
            NkIzVDArK1Zvdm9tRjhYb2JSellXWFA3VlF3CjBET2NEaUs3RWc2RjZBNEx2aGJq
            TTE3RDU4elkzemVJbXpqbzY5WTlyMGcKLS0tIDFIaEc0ckNCR2h5STFJK2VmdXpM
            cHQxS2lnUWt0WmE5eXpEdnM3TU13NXMKt8JITG0k4CtJVRXDou2ZUbHl2z8tA4ce
            hc57Mm4JGZlN/7sthACDHHPoo9gpGeO1tG0Bxs21XGY1LzLxbdDvHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T17:23:28Z"
    mac: ENC[AES256_GCM,data:/oRmX7ZjCAHYsjtkWf0bFbiGGLxWp1t9C9AjjVRqYQocTR7EBf4v3Eb/3U6HNNbtKT4eBfFsbKkdYipTTKl06j0Sg2N6auMlXccnddSSzkOPoxPmykbi9LtvKH0vVf84ywV2JcUFv+Cq0nPsmYRukVahr2hMuW0mrqtvPNJ6AI0=,iv:xRSzY6EByfAWyvAVdVf++7pki0p3rnVCey1az5inh0g=,tag:U+apD4vghB8t1lsbzXhOGA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
