apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:aSmUcoL0g35oW4XBjeCuoolaArYaxu7chbe/A3fHium1VDEmjQeDYxGmejtloCykLQaJEnMho30hFvpKrq5FUMvmZJFZRFiwHAt0lK+EeqdHI8+ZJR3/jvJF6MCBE/IhOQ1XOUZDJvxtjM4fw7cOQT4f1irASNOJxNs0qDV+Y7QvZuVAxTX1h5rrOE5mjEsMwtPE4Blom0XoUadqX5inlaJ83JKNNO+Ez8QdG5l7MXTrk6KWDf7Zu/RIXk4RAK2hsvGrlgUCbp5r70t/TrYYMUaBxufFNnPkD2p53rZkSyLwB9OwW1bVLZn5umvMNq9AknztwzLZCy4Fto80xY0Q+BEmqyrhOnNBIfiOEJJLm6sExDr3kU0m0BFBF6MntuQ2,iv:I4dIcN8zc9g2jsZpuDhGCfsRjgphT9AZD9Qi0q3C2CM=,tag:veHmWRRTFMr/GEvd+8qGXA==,type:str]
    identity.pub: ENC[AES256_GCM,data:1hAlpm6dYojOwV4o/EYTDqmmmf8w3JKJ2gghDSFtTjne8I+7xjaEdnaO/+uKdQUaUsIaKImRaEULVTx8QBU21+iihzrR7aT/SOWEXTFwtgymLtiKN3EocqDvmrH30YbeLxXBi6LjOeevZ/pI+NfqgXm8nof/Ch8L6QXWytbmscjkywwD0+8VyL5RLp4MLZvqIo4bX1Z3xGpfZEGPInT0kaxZVTeVdTYuVLwPgnG8HEbTy6TeRPD5ZRBr18MpFIwfxLOB4Rpfw2PmBdEWbA==,iv:jyPn/AJdFnXGzxBKyZp8X31Nu+w0VNvHyMpV5Zh6yU0=,tag:p3qfe311thIsyIKb1e7UpA==,type:str]
    known_hosts: ENC[AES256_GCM,data:A3cfGgyzACWI/Xic02SYsvnhWuQa4ocXRlEvkK20HPLIPCZEaOwvJBZx/YKk1Z5fx7ApkL5D1JUwVV96gO1SRwv6mdmPYCZ5YgRLV/jJXGlVie3jprfmsuzS1oOZD570njVM3dqudLORlDpbfnuLCl/Qi1eYCU/tktUWcWdWjIlIKvxvD42hSvAU8I/XuRKKp3XzDc0u1cFHX2dDa4q6H2SxbmA1xVQNWlKY,iv:4pv2DiGBPZNoKzbKlxYQ76sytS6pS2dbQ3n7UbwnTB0=,tag:3mI6M9SHcXSXBkfQV2gfoA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZlQ4MWhlR2xtSDJZeUhP
            d3hlcS9TRjJhWXpGY2xpZitZV0RsVXZsdDJNCmErVnFGL3l4bU5FNUw5NmN4Njha
            cWxhRVl3ZWV2citpQVNGYmVPZG80RXMKLS0tIEpUeHU3amxjK04vQmIwYW1odUZY
            SWtESG4zRXkzZUQwL0N3RFAwdFVQQ28KZbjR3UY0SSwhLHvlsuNtN7w9hi33+b/W
            sogYwc6M8gTU71AGjiqWck/jv/tPCkAi5URKSKyHw3Uxwl/ZfQZ8uQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T18:52:48Z"
    mac: ENC[AES256_GCM,data:4IRnKHkFzZREFQ0tY+0QWt1eZmg4Xmqw4VX8pnw4ya4ZuMamr/BsZMgRc1qNd8sK4WX0wK6IX2/9mmiOK/ZndYrEZNixPyTLCaO4eCXcK1bIHSP9cHO7lpPoihaJUgx5RTewj0Kx7ty72M1JSkoML4ahkrqCIWwKJDP5jfnYPBU=,iv:IE7ZHdWBqZJ9cvrG6sJ9BBCgoH6vltV38yGvvHdfYgA=,tag:FlYzdXMlb+bOxAdsgCreLQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
