apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:FV98itb+5CJ9SMfVgX+APuqR//56wJT86kqbaMgomYYAK9ggCMmgXT3e/gx+UtgZIGB9q3yiBmCiPfvO29E9pCmVpGMMZWvfuHKLBtrl1v+WlZqvIDzDEUyZ3fgaZCuBl8bMGdJGPGUNJQVZy4mYXZZXTDvZfy8ZH6P6arkaAVTzA+0DSLjlWTmY/oR1YNz1pfVea0yinDB+omz2Fx958hgeE12SG//ssUuNCDqfK/UghNZ3x1NuKo0ZWy0xA1DLtQE3kU43DSk17TbvFxNIWvKmxFTih30NXby3nhWbAF3OxXjvo1G558wOSyN9iZhHqnVtN2QW7Urn/u6jYFytcnRfFZ1HLI2jGgi8b256IgmbVbqcWZet15n5/zRBHTAi,iv:q+77fnhKHrNwEJMxo096+5QpjuIfK07pFJdIqm5H+uU=,tag:DsVfut3Wtif8pd59wMKvcQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:5r5rTXhYl3mGtBy6Hoeo6D5WzDTJgpMU1YIaCO3sLmhG9xng8N4B1A2jVZnmHX/TEUKcnwTeZ+hNBSR3NY6DSGe8uZRI0zbRyNM3PdKeMrIlbYYpB/8Y4nuePBfhmbovIPq7FXiEXgexlhLOMSNLje4zExf1Xal5aBQ5RoORUZyEJBIhQg9nGlbvBHULeAnPLS4qSS3GzXIMdphJfb8femZSzJcvzbTewFbtBDt03H5LznYt4nPBQsjXNiyh3IzYe4npW6/wt56/uSAxlw==,iv:KUZ66nKRz0uUfXpte28Su2l3VOm6Zo1QQj/IBUb5BzM=,tag:ObEJyCxS/ivGPcwrmjsM7g==,type:str]
    known_hosts: ENC[AES256_GCM,data:rwC7FfyGNstcEpR5VHwaq12w1RQbZo2VofYf68W4JAYz7kE1LHwj7MBg2BJkNgXiX2aOjFQZ1YKVZgMiZwokTzZVSs4kXYbPYd97g6exjN5aBsFqexJ3RdOxRR+iaFj8RduZDqr85u5HL768tM1lcRVIrnI3/qD2ZjqIlCaqxUuA31qTb5DY2Ml9uJV1Yzqgc+O1HBKRd2bUPdxBXshVZC6s5M4EW9LObcOq,iv:fF/2VTcfvyEYb+66PwwHvAnGUxkc4qj9EoTNHA0JV8Q=,tag:3r9IfdU7/4JKYEsE5DLV8A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByT3dYdmV5Nlk3TjlFU1lM
            Q2g0VVNuQWllQWYxMkx1YjZHaHhwdCs5OVNvCnJZWXJuVmROcmI2ZU5EL3FKV1Ra
            NmxNcmd3WFJOK0JYTVJDMGlTaUxPWm8KLS0tIHZuK2xzSGt2VDllMUdJblVZMDU2
            V0lOWU93UE94S016akNqcE5ES2E0ZVUKPVPcOa9REUwEnUu28sn1gITWIe01udp8
            c8cJkSNIg4mqJpWbJOPuwsjWciVsIa4n4Rwycfzzw2Lzu85sStBl3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T01:02:59Z"
    mac: ENC[AES256_GCM,data:jhRXp3U98hxe26c6dt3KPDUeY7UrBt+lIpTH3CwoG/GRwTyselLCv5kDqk0xjhgWem0J1KPktnEIwpjJFDWcXJrpQlicFWWUsBn+LVg9FMaAcukEBQXufi6lZ8emy7WBgfIQENuqU4V879GDJZXO7vzGLbgoKW1GoRa5iUmkogI=,iv:RhVaE4lcbIj8dHzj4nQOYbQuwIGKuPtgMMM2g158NWU=,tag:yI1oLQD9jZK3e6OvCK8zNw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
