apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:AIPKgAfWisBhLeglcVwAVL8cF2I4iKQ99ASACoRmaBrArsEjAXfKS1Tk73loS55iuQk3c3OZVLMr0hM8ndU0s/upZhTeQSHuqdtTUk6x40Aj0g8S6oqbrC9AirwMK4Me5VdJTF1Bj7qXSsxEps7Ya9pcFXymbimQCet2t46KxKstWt1e8OkxB+aiOk4ZmfQ/JHP3aKP2bvUi1mhe3OkV7NhmV7+Dd1to2RMMSTjKFJqFR0fvjIGOLz8izM+JUfoUC1bm674pgGW2uIOtwCXd7snPX2ziAQNvclX14xu3mrZT97WmikiGik2J0t5rnUljCh/ouqMRw2JnEaJPPZA6jH7Fw5ijccHi7G3dFW8cpzGoDnsAw9hw6kk3Ha9WwwRk,iv:dlAh6oomtmrwkkm57N9maW7Zv+8Y/izLSIw2QErwPgA=,tag:HAndUoLhb0zhnqWyJnc7nw==,type:str]
    identity.pub: ENC[AES256_GCM,data:U1+e1EO06lZqvhYf4BHH1EuIDdVfseldjeCMhpwls88vYb2veV9882fInmnJykX6PQf/hS7Nac5FL7bqMHyQoOVF9tOmbcsxJaYGviDZvnAL2wvqi03zFa8+amfQC427IXKO9MiVU94CjyWlqzjihflQiNsdXAkT2mSNznbY9EOt5JB3eHwKykaaSs5V3ZFv/S6QZIwXED7bs9dZ8Sd6hwT23qoZUDVewNpgrOTLNJRK4u7dNKJwgpCuD2V8jhyoASW/Rtmg7QV7i6/3Kw==,iv:oNDjS4cfDzjPuXHiFpmBMQVm5RG7ZcFfd/n15Z52RI4=,tag:WVmuTkVLV6l0BjqTvdH2fQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:h9ZgzUiUVoUGSmuC8qsZh+zc4488SEYI3DfzVkBue4dGT/MwqvWnulTYwHPfMsHXlijUtdV3ZkIKTgIAgR1RIL13RdUyGNuUi6QyzWQBVSNnYAEXmQ1cuqMacqmTAInO0kLGkApjcKgiREvKIqDqe+YL9tpBq/Ip2SOMD0Gd19LF03h6/wezPEoEDkf22K01fNe1Lzfu+ObBY0RNg/nZimH1Wu1Ep+lEav37,iv:8AiXWF9nO1lUESNmOQzIV3ONp6bxhUiWCCw/EyapdMo=,tag:3T10pKWd+RTPwoRUxBJr4Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3YVlaK3R4UE9SRHNrZjUy
            TnU4OXgrYkdPL1dDVVFWN3ZHa1ZiTGtLcUNzCnBWWnRPclEwSjFrTjR3L3l5K2Vv
            TXI0dUUvUEVPUHZkSzlMMU1uYnZ4R00KLS0tIFN4UTNuaTFlUUV2NzhSN2x3dG44
            cENOcVdwbXE5ck9FK2l3UTFmZGVlNm8KKyAG0oSVCYhx21U3Q42rtuq8hBL0tS/m
            Kuaf+S+9COSGaZgvErT+6PPgN2lE7gl+xzwOj8njSKLg9a3AvreECg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T00:03:42Z"
    mac: ENC[AES256_GCM,data:7SoZEMy14M6oNUheiafngaulyGFsJbiuh23JQsMbOai+QOfilsm+o2pNw8O3IGRodRrvG4hiuy9Rp1LMRglZPQjYlg1qnKJbbGCokW9ZbVqFi0bBuF1Jw0FH3m5OZ0aWO4GnUxJ7sW+DBYx12/tjvlqqwJVLhx5Qt1+HzNSC2QA=,iv:pg2vLz4iVt/RwzhYuitsHvM4N5eaullLeqk4q5BRZ7g=,tag:lbYY5rz+WUyYEeMOfrYAIg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
