apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Nwdo75WndNBJRcfPT3zA+YLCzpLRCByFuXFPYAPp7It5PuX3i+SDjKhBJu0Dwf3PLpsx7JzF4Crhp2/X1AT+77kX0NceOY1foa/BSnNybL7VF4thakIUQEzJwLE4tGpAThild8we/2o5ksEMe993QiFObCMsOKCc3CZuc3M07DbvGlkXo3R/xU4EpS4ygsZQJzumNFHFQMXtuOs00TfNqVTzr4a0evcwsipBbn1OliWzLSQl0qTGGr8wUfdvoXa29VOZh/J7GarQxtyVDSV+unS+ZLhEgIjcsAzeIiYrAGLTnUwsv5Cdf/WyQuNBhJsJhVufPtNh0Olf7gMLBLGZ6rhN91G4ywLkIu6O/EHUtXYf3xLr7BFcZxDyVRx9q0HR,iv:dSAAd06io0GDxwCopOliXbiXk9sHUMAlzj0LyWQ14lY=,tag:10INqFWnl0zxJO/GsE5/vg==,type:str]
    identity.pub: ENC[AES256_GCM,data:QPvOBz4OdrYV6MR1dD1Rmh0lfyxvfqsqEcX9wgyT8pv/k2cJ1KoQKmbAjyI5Kq4RVZJkMS/mDLVsIPpZsCSQDaZmtkT4WBT3wHQA4PVHDwVPswubN2kNKg/bd/44KiqKWcN45o63N3OPz4Mf7jEi+akKbdNPeEcw1OMAdj2GTSid45/+QA19gxUGxjbXi+L1gYm4pikPhzOAlo+dbSqlaWN0DyDxH4rOal3RSYCYAT3LM1x6iLj0aYwEXYwAljtjAna8/t19m2JDqNAwwg==,iv:XrbQOpIoJr/kYr2gXeXqf3bKDigK065jD/swStIpz9g=,tag:zC54tr+mf3QWlyT/nNK9kg==,type:str]
    known_hosts: ENC[AES256_GCM,data:ie3INN7e2Ehj7PJb6ziogm3ju5aEC5ouu3ukASVSWrFS2nkQkQd3cHrlE+A+NHXyNi/BEn1TyjD2EAPEnMySUMcYq8Xp8jDql/7XZT3IwVaiRzLfgrmSTbmnf2xrcNSqjqlVw/I/Bf97OgS52b6IA0tr+5RgECB50L66jvrNjSP/oIgMsznJF5E+iK1JjcyXtviOAhtz3Wjmb5wUx7bvxJ4Ux2J0Zcli+siE,iv:GdP0s1RxRrTzisD5V+wdg0NlEAeR9PcNOcaNswpvi/4=,tag:HeLwY33PPPwlR6nAxFzi9Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNVkJGMmMzekhPU2tVUFFx
            N2YxSVNFKzVNcUc2d3ZSSUhaYlAvVVlwK1JVCjVxQkRRRXEwT3A4S2pHUUw2Z09J
            VThzR1hpNzIxNjI0bk4wRnQ5MzNBWEUKLS0tIHJHL2lpQTRITkJBZGhMUHhaQmZp
            SmZDOENkV1d0ZkJ1TmVTMDN6aisvMGsKTaMHgaNCdtdxLh45YV4psxPuEjFhyzbg
            qmsF37VqhNmSG3kLPQ+vae14PSBzFok+8llnvDQhx2Km+jbHlQ9nBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T18:22:29Z"
    mac: ENC[AES256_GCM,data:3UxD8PoUygOV5hUdYue/BnJJcJ6/EX3IDQ+8TrokOCtTCNJN+DX7Qhw7fV+qu8vqBF8fhCtANsG413bIkn4lvwrMFpDDylS9ECrLRgmXb2ETP1o1NsmyMw/vtpvZ5pAsZFmkY/mvT/pkT6gZ4rt5KTvf3hUUpABSwb4Lr/X712w=,iv:Lp/MkP+KLbfBDefu0ImIIX1vqOgLfkkfHVEzkm95R/4=,tag:GQRMRbtDfmKqSjd34FAP6w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
