apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:okfAZYV5CzvGhRflKcX0+p4Lmql2VxNNTFKg1Gc5qkvlf0tJcw4JXmiGijbPxns5xRhrxk9TL7CZJu5Ktw15EnpcAQDM98/RSlk9MdI1PVcFXcPD7CrFRS0YX1ZZYJLzpRP3ijys9af3g77L6eVoT9o1l4NUq1QBn4uN10tzASIXnt78/sWQ9Nt+1dA4+5P4ZK1YKISonUKLZG6PIsluCw8JyaW/mgS+cJWZdV9Y38r42GFIWDWe4il5vSeq97as9vByQ97XY/wGG4dCMF7qOAFGVfUF/VRM3Zt/esVeFN89HU1ki9wOlRZ/YC5A1uydPY+8AW8TTFEYWSOLf6HlfhtfrX2HNwobiK0Y17GyIh7M8T57b7GCPt9OtzUIGGwC,iv:YwcJbAsxhQhmELaKgyDAXee6tp3Ru6wwaJ2gf2jpcmo=,tag:a9DVdgdgc68qwvOovZ6bjw==,type:str]
    identity.pub: ENC[AES256_GCM,data:ZNofB5kXWqPQW/AYiv9dtc1UrU6w1YyU/xyioJciOuPzwj8jPuwoYym207DVXIveaCox/DWZ6rn+U9V2g3hsk869QYpAhJ5Ssyn+BjcZ55L9De8IpXJZikiOzceB4f3GxP4qxhZnv9lrD+sJZLRJGsEuFWxPjQ3zDBfJOi2BkZ1FGV/2ExnOgOudO9hTexgzJvIfBHH2IkW8Jm6y5co76S5kIUJ4qSJTUwLWLUyN+MuPIaWT1v6adlVq1iN+EsG2X8PaPvtdb33vF+OzEA==,iv:Vw2a3+d3IydyLffxsQcPETrPgTmVKVgcp9EPNTns+q8=,tag:/U+BWz9gW8UEzxduNhLb4g==,type:str]
    known_hosts: ENC[AES256_GCM,data:YMKsnJvt0oSj2gISa01qYjLunzmiwJLguornTaw3X3bRBOsJuiWbHnLkfJrSfLYDy42VzY3D2RghpviTPvsD+kVpjYPHDj6CUb+oL76MzkxHChExwior0gvs5gSrPLF4klm7uW0tlLohRhSkH4B7jylkzsnxsgcB4h3Lc31exnRSKyrNndPsKVdWFKUvCWcOLPprd3LreEU/9DhLVWvi4dcGR2HT3+JkSNEY,iv:IaOv3bolA1FO7i+WaZaG+oQLgWQxWNpQu7/eByFUe9Y=,tag:22hQqVMbNZT1PDzS1MN4Ew==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVaXZnN1FpeWtEM3VQTnNx
            M3ozdWxBMlF0TXNySVIzQ3E5Y0NZZnFtUzN3Cm9LSXB0L00yKzVIcHdNNWlFV25y
            SmVteDlJTkxkMUV5OWRROU5jU0tCOFUKLS0tIDhnQU9nanBWNDVocUo0MTBSTGpU
            NkRSMjVLQ05WS2R1Qi9RZTZtNVc3WmMKNlx4r+v00PL6pEThY+nEirZk1lZd9qza
            QpJwJw3w0rt2lYg0UmOw1Eku+ovZlDNWr15Bb0LDt2J39hUnAnNGyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-26T22:32:32Z"
    mac: ENC[AES256_GCM,data:YvHV/2uxYVAzMr4Jjmr0/kcF2PfkC+a97BKP1Mq/kZJbdURxv7/L0Xq9OYSChbwO/NY/tD9L8CCJ6RjB4UEv15frvTgIzHlpelm1YTBdUQQi+VKpnFrdXxGntDHrsnrgOLkaU7bQCX1xRvSKJoj4u7KYKn+nBM/mVkxWSCVMHYg=,iv:Tnd1P2iGj29k6y7WcBUsvn4S236um9TrMFnlUhXuq/k=,tag:OBPMW0THyirkrLSriKZxkg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
