apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:7We0Gh2sO02qQMgmp2fF/wRDs/iPBvESeZM0pmE64o0zwQutMJN2NvkY0zurKt3zB7bSM9+lyIIKswB8iQ8EfgYjJxiFqQeBX/qn3+YKcS1m3lkgO4vID6rCTp7jR+tQDwzMhZmp9AyEz7zXmY9SFWCbmco3UeDHtE7PFdJ15X6R+j7hCwZ1IEq3psDLh++zwiK2+CXJLlKhHKKjVOxRk9cnIdJ8YU570Uz5+Ls5yI1Nw1l4hHNjZ5ybX6qoLDo7L9oNIQR7ZII3Uk7wvmPRA1S2OAXI2gc50UVDdrMDmrK/NpU2EyGzvFJJrZPgCYRJ6gBBKK+nKqV56rzKJPMLNBFUr6qoOS8F1FlfOnC+obZ8Kl7sJg2BvRGKqWO0irB6,iv:7V9PQVeVqhFxXqJLcv+rdnuObIRHGy/K0VPUHx7Imu4=,tag:wQ+bfKkkUsQ3UfAjGtqzqg==,type:str]
    identity.pub: ENC[AES256_GCM,data:Fw+yA+M2w8xgRpoy4tJSufCO0Va+umLfY57lYGvAnqvZVzWPKghYWdeJzBdfIqKqo0E715Ll/9rs6cyV5Ed0XYGYuhkYCPGLSyagN091Hjf7LtzaZ+MLGid9WcGs5jSFJD6OlIPrP+jHske1AQLPqCfg2dhjZwVpko0CPsGENRdh16KPPgoeWtlatEkm/p+zritbsOSyB3IQTpvlhHlYvdhKn9z4sm5SfhUv+UKD5wyfjq5alCuc1LLZXZ1T+cg4pZodp61xXmJduAEueA==,iv:PUC8MY8lYcLxde3KSbPvJa5RNIwLTFY/5qZ1JAnGer4=,tag:vfN/4E2qSlc8m03gEO4yPw==,type:str]
    known_hosts: ENC[AES256_GCM,data:PpOiUZcTizDxyUknxkrV3dngP8xGgU+61kCjzE6DfIvOY6sO7Ae5EVEAlVSTrXkBG0rT08F7oqpDq6iHFdqdy2IMpXT+qE1pXsNUxTNhLK5Y3C+9zG38Kj3eVUmy23BYWY+qtrsXkpbvyEbtbb27HiZwj1zDCeJSvXoalkvTpfjZ5M1Vctsu5WynlylHsI50QISlTaq14uUDHNAGYipYbxMLzNdVrYznFfbE,iv:V/41nAyc9E0nX1MsFSYvZGPFyLYR/P+XEysyGuq+ff4=,tag:pCatFeym1UDX155h1ooYUw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxL3VjNUlVblA3Nm9lTERD
            WmlpeHpGcUlsRG9mNlQ3TWIrdU9VTk5uOG5nCnRDNUNDMFVMd1U0MXVwcXkrelJK
            YzNFdGtKK1FZdm5nRTg1VlUrbno3NUUKLS0tIFBHOVlLZ2dQWVVRZ3J5TVRCUlo1
            ZnVEK05mYkV1RmJGSkFhS0syOGVNeWsKLwk3EhKnbeBa0hFP+W9n/+7LM5YhXizf
            5EeUuD4OAhcfQjI8gWHNZ3E+n+1AemozgMu2ZJ1FMchCy+YLrdzgLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T19:02:52Z"
    mac: ENC[AES256_GCM,data:DDZ1dqC5d5gTaMCFZvB5yKAxqR2pTAp9Ihr0uR37yfQ1l9aaUthbNM06YpEKHQXKTq3P5qqASyTAzqvdKguiSKWG/pzUK3iPMikeY5Co39ojODf6NcZqH/NgsKhxW6yHlgKWYwRAXQToMqiZ9Oz/zc6evW+uliftql6Pwvx21Y0=,iv:wvzOA+JB04wXpIXTuNL9VBElrqf2A2Ny7TQXoFmqdtA=,tag:iTzEj+pHecByNTjgw6Igrw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
