apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:oot4P+Hrr8Orh+oOoj0w+VJfCLRLNWO+yG8sklvdR4d9T6/+x9NFXEdDECQq3/tGHvTyiSiKd8eW3ra0Y3jBDjbB2pQkEyBuvXo0co1CNBpKpx5uDFCxjMOcVio4NXudvsDDRe4hX2gYpL4nUoPwXiTDAXW8ZIIsVwyLBy3DVp5yIAfcwdl3dllbOvIeHGsCmUfNSUoxGQYvvgHiAHKhwcjMiu+Tg+n1FjE0YFps87IGwfnrNcbNhZCeNdAETtv5Lh3H0m2WyV0MGyfHI2aNMi69x6Xyo4vOKWCf8jZ7A1fcbtgoEawt9Mx8Kouf6PTDTA++zkqFEZxoxKkDxI57aVsQrMyxDD6yT6O92ibmewrNbXk6iZJ38wpS2t6Qwbi/,iv:hT1Y9N15holOnzFW+9KdTyT+zmOpIoXjmoRBrV2W/fQ=,tag:ZuTW6griRocOHiAsGU9AQQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:UzLyjHrxwuCOQWyPGmMvT2eHkQCC3BCK6/iNHPU4tE5vLVEh3+9f+oP9D1GdrUrPeu7LLmtS1eKoNkii+OH6ZTXIy/DaRRBfxuTDR5Yg2ZZ8DqpLHRH0puoNFtzERlaVNG3iXmL/tRnRzA6Nu+3zQLf3uAajzbjd8EEna548LTWmTDrpsw0w+4ibW1X/RkQE0ODqyNliMclywOBguGU7q/Te4M+BE0fvnNPrf4wWervwFJOzasYuAaSfabLONw/ttAKOmiUk9cJihXgCnw==,iv:KJdB9ULjaxVNR1HH3zVZBYrU9AhwkZADK8B2ogHGCfA=,tag:RNSsSgGPcdsZsam3/FNFzA==,type:str]
    known_hosts: ENC[AES256_GCM,data:BIFXjcrhhGjPqFL6EAfC/SieZTWCD6jyR9A35fUXA8wv/lIp2J8kgsJPwx7ma0PG46eT+ae9dW7xG+4PGs5PYEe1yspREj9CNwoXLYDyx/WXkTV6Dw97xVNR376yBbE5nHWiMEvB+Y6S6SFWYjyj8+uIyMcUOQIcYGL4yrrMA8apxN7agKpigGQ80GhQ4BEj/V5RZXAC+NbZDIWqRkpmv6kFPEo4HLGseENo,iv:1PVOGTZpS/X8vKK4tqZErd1puVZIG03dcs3YA5UqhBk=,tag:p0AyT9YNvaceBIv68C+HsQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsV0tTRTBxdTdKNDFoY2RU
            VUdCZHBYaGw2eG5ONnRtdDdwWG9kUHQyTUY0CnFtd2ZPTGMxNml4N3F4S2MwN201
            Q1dvYlA4TUN4cjc3SUFzSmtzeGlQcU0KLS0tIGpUd2VrK1FkTGI3WEtaQXpMMzN0
            b3pDRXV4VXA2OUVuVk1RN0dpbmN6OHMKXcDCspAmgfmkMgsZiCHdy6MBzjeufAue
            wNXEZERzJ2u5hJtgd6lxiCUBw+4NsyPoLM3oXzXRvRlQeaAdiYE9Cw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T03:58:19Z"
    mac: ENC[AES256_GCM,data:FVbZLTjaxOTbAE/EL2Zfd21ENoQpy81JnV0s/EtkPew9fDoyVU6+nJyEGin+DvcvePbhAl/34QfwwyUMXB2lEnWnJSTrGRTtCh07+Bx9TX+AbeDOVL3r/UdDRVstlJngYSLomrgSoAoHa17Zh3Pa7GKU70LmXEGgyZuqzScSKSA=,iv:bXaBECAWv44Qy7v23iyRG/GKLuaefWTj/tmByehEwtg=,tag:n8ClA7nZXMC5zGLJJKhN0A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
