apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:jOtgNNXIQxHU3i9ww8KgdkAC+Y1BhY3FpztqGvJbxxA9PdTHnRMeP0gaE7zUWET4A51tcAr/cm1hC5L+xIXy0pBLo8Qjnv28VGQDhzbpyU5zDyUCCWyCEozA7QTzJpc99ZZB/UXkqbZOzclGojqeLVLfHpHam3WzjZKUYmE9PjW5dfQF86te1Zw9J/4W3nJwgDj/DfI3YF9e9V1/5VXnohp5M4t8XScryUnrl+1b/1XzW6+s9EU/CpzsHPoYwTihFRf/S8zzWQTYmLpExhjOq+C4MoU9yaEH/v82mwq8Ryu7ZZnAtEKi7QOwSyV8f0kFWYJNbCXT6aqKj1jt/QSet0HXRNmKWe8xMNOJv1OuaXt0g+lcuG/p6R6A0aKEGdAZ,iv:ZQkHSoCM4ky8RCBtcoMc5vMOYZXWAwGlAFuSYdwbxXI=,tag:oFlps5D5221p8drKdOffIQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:04SY6xKshE7tujBjTNnMnDePHQfx484aAi8ncwdSdTQlKugD64VoIaLuMeEi2x9kL1L2B82v0ZK9OytQUoaUr5KJO7U3CJFoKXgm29i/I8Qk2exDVXxIYIarH4Efwdg6G8y5aqvYNmz/1vYnSWqLa3axPQ5lDrPDFgbA9BBSWGVIzq6/CuBOxmj4D0jbdLfQTryylvUVA6GKA5efZoUFoedceHajkwLoNibz0cwbvSDNAmpjS5jZXeDdAgKJo6pOprODETTLqnDOd9ctUw==,iv:5xKSNThbR58d2agr6XzLvQSu40ZZZdNlRLPncOMSBQw=,tag:/v2DC/8ahMoX5uG14AfgnA==,type:str]
    known_hosts: ENC[AES256_GCM,data:J4qDnpYPNmFVtfzFBILRENtsuq+OFwgXmng32qB84REZNUHABXssp2a2ZDVgDW3uaNzXTcbqhq2vNd20iLqXdp/hL1Gyy/bLzqSwiicLP+G1D13dtLVzQG7XLQryOvvgr/6+5yTHfqmhwBmkXw0AjkNBjQcn1pUkz7XN5WYY4lqmISWpDI6sHhHKp9uOxW3pU2Z0YLafA3Ad7DApy7euRzncJUP5rGFcoKK9,iv:B9F+jD9hSHxpSwqS3jddyDT3gX/vzYqlH/u+S5vi9OM=,tag:DBGql5k0kD7vQioQ6b46Cw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6RjAxMjZ3a3dkMDNvWHFR
            SnIybmF5a2MraWlkZ2dSaUt3QlUwMXY5ZlEwCkhDc3AvQzZjSjJZTytJWVd5Z3ZQ
            T3dFMFlLbGZSOUQ5VDV4QlJEU2t5M2cKLS0tIHlNdEdUZ1cvc01OQkwxbDhyYTVi
            Sjl5UEk3bmxQVWdWcjBjd0l0UTA1ZkkKXDxwqV0A06jRiwQ9WUTp3eenpn+pLzHd
            BIo5Yaq1diQfgugx/NDKTSNllqxehvbbkycV7WdARv+Pi8PDo2jMEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T18:57:52Z"
    mac: ENC[AES256_GCM,data:4I/+TOYCyg7DnTdQOJUVjCrhOvRWpyhrTkmbMH7SH8FkJ074i5J+0xEIpFdNYqwVuk512yghUcTFpDTKLKHIq6+PKXV7dfiZ6Rf6vyfIW8SKIPHxvO9Mkbnr7I+4xpCfdfLeEYL5Bxowae4nOiVGC5iF4L/aVAz9gpRnh0/kBrk=,iv:+KbnsqnXZh5gbZ3SDgyBBYJA5JnQgxt9Vgac2LKzAeU=,tag:WpCUwVvN/nwpp3aIxcP6sQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
