apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ONQnVkxKkduIdTfpnAMcjdzrxLE/t9v1qpKtDZfsxHZ86yP3thVlBI4aOoFrzPi+XM0zmlc1qjk8VGoVmGZbseqX6/fQLPYAvbrYqyRoaS/6p6T7sfTB++NsWLwXbEAGwmmtxZaJ9Qi0Nj5DWBYqij/Gila1wSz9wmNG39E0coBwBoXrXSvtGKZ9oVCsGgNqCOPxd6G8VbDRkQjsdnd6k/TQqXNC3/N2CxCe30BLiFWFOHjPmMRgfJHBFRUO3RLZ/Bj7vujs9y3Lrwaovmm+M6+QbLZFMmdDGEuAoM+aSJt4e/W0nrrkhmsz+2+iRZ9I9szCgD0GQu8rt7Lq93Jw+bOPq9UzhawYrgcFwiIBeGn2MZyy3l9IJFo5GG0v1sNn,iv:hjJBE3daZU6E4Jx8Pk3HnXZFVWlWQPx6nw53fqrZIpY=,tag:D1Ip4Paqz+ryKU98wl4gKg==,type:str]
    identity.pub: ENC[AES256_GCM,data:68oZuxdk/Bf7xyoP5SViLMh1H9SpYzGxSL7agnWkTBeUqADZCb54pXqdNZB6X/0k+yaY4Ew2J3ICa9BTF+lJvSvAINbVRtXH0r95IJZ2GIbVLGvWG8pcBj7tSvsfYLYfyg2SS66pv3TLNqC4ualXbQXjmrnx3+a22YEIfva6MlUJXJKQRThP4PO/tJe4ZxUx70M0j/WJJqCxSiI6kf6XlIt66xZc2K7iJ5Eg7FfE54yHj2gI+TsGT3Cm0nhmYtCCyuP4HlDIqfIPkOjT2w==,iv:wqcYkmlbywW1od9t8kEDWUIEjmXda/XB78EeNpevsMs=,tag:nrH8fqsKsyv0kG6D+UHyyg==,type:str]
    known_hosts: ENC[AES256_GCM,data:6M/AfCO2gZ5AtmdyO3KdmobDx1BWdMXiOhtHN2Lrw5GdcqdEp8zf6b+ji+N+0CAfu8rs1n9HDsZrPwUd3eut25RpH2rW/D60pqQEnnD+XytuCG+4Lb3z2LtVSHEby4iVNR2xrHtzLYNCLRkEvpG2+zuk5JE1A84K1LWAVmjbDpEC0fT3/ihD5cUe22BOR4946+5zxHbDsZfJ1TjMMXU52mr4bYEjkVZkrbZ5,iv:QZDesjzFDM+YMdkvmR3P1A8xeu5QpDI8vM/oNEyt3DU=,tag:0T3zACxMEgicugyPfuMalg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBENXN5Z3dtV0JUbWhTTTUv
            YkU2SEV1L0xnaFRTNHpBNVNRN21CZ3ZDQ1FBCmhwdDQrMDZocDhKVlB1UkdXK1pI
            d0xSY0pHUkJ6cXdtVHhhaUNPVk5LL2sKLS0tIEpzNkJlZnh2aVEzL1FweFdhSXBr
            NUJLaG4yMDN0MmRqV0J6bHZlUitqSncKVgENSYH7KBH/2PkdSUA/MaKczKQ++ECi
            H0uHlRXHi84WF9pdzHcRY/DzNncBrcGguSPI4+i5DiJNTFGhiIxecA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T05:17:12Z"
    mac: ENC[AES256_GCM,data:kieBpbZHa60OHOhHB6MO9KE9Xa3nN+9+CrKxKE12yZX2Vxm8yI75F9AnsoX+ltVZ9F77iWGdKCiOkX673jGvkDwuEx+P6Tj/L/btAjwIxyLVCOmMINwD7GHWgebJOrkBPLQDZLS4F2Bvi9F42tIQekwRtuY5SEDrg7uMuB7sv7c=,iv:DWEpUfc7R2++mUjACX/wti/YXgq/2QnUtaGx5MlxVA4=,tag:ABR4SXYcfVTnLWLt4EZGag==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
