apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:RCDq9jGmb/GW69GjPv4YUvybUCIFdspgvKOwgoyBDa8XYrivwB/Lwe4jKgi/dXCSRb3dh0FF2PpoKE1jcAlck1atnOgXw1jxrhqV7ilPB/yj3rHRm/MAENhaL/Kfzgod0llR6nDvS2ya+cJ17wLrVpzbqNdLqrP+1f/sEncktMBBD/OswPXWLHyvYHc6MgYTxm2WdoOsdgL+t7RoUV/ugKW8tsxANP1IanWr0otMKyQsvyk6SW9Yrv7+INFMktNCA+3VCIP0w/uE6ctRtFwt0Jr3hXwEo1Rtfk1TgbbXtg81etkxn/lPo7N6TBBKnUms4XKw4rmwJBoN/ZRqfys7yZG4B9+ZoHknvEmWfvtcvpwZIQsapSxJB9q1B8i+dSOC,iv:w8Yrn6lrKxqLyVA1cXqyzhnpfL5Zypk8YVNokrQCiBQ=,tag:NCrolGuTcclcH/rwYqnLEA==,type:str]
    identity.pub: ENC[AES256_GCM,data:/j/EXBm9AaTpJNraRzpY1Hnt5+tso9eAfW679b0aoyiCaaD6wpsYkXBNagkkIqYPJRgLnlzK7hIhtuaEQniboC+aPo1YVbNDgDQ+qzxMH8BOFZPEkAaiWVhgFKs/C4saaq2EwACU0vuJ8kmpou+1MokAMQTmS+UlRE/6Tea2o9Pss4PIzN3MxGBQgqgf8RXXtQvYCRAetNUMoLHKI+cC0LPJkd8awj9km1FDX1CRTlfDP9tdOHSqiNc2A8oyDMN0X158vDVA7GIsSkbxFQ==,iv:RhWfx6l36SSW1JNANvUlmN2ytSOxzALHQbZHyMUfvPo=,tag:vms/fdGxowEzIRL1tQmdwQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:OT0FCDJmwYP3OxaJVC0FcN6ZvLV1MSpNCp+YpFY03ITW/LvHbUpABSEQAMnEYJJ5+EswXfwIey2M9dX21GXLzH7hpFRo1S2117peaxSuBx2pcy9QZjHobuCNhOxfUkPturczJeSJv+q3JH078bglLcwyx62TYvh5R947Bx3lkGeM6nkYJE23I4ttEyO3dojUYW1iAtNBSeJIb2VKpC5e3JUVP5qqGXRl5puU,iv:QC7Qx4uEZ8IToTLGzNmxNXOUB0Lb2mQLOdgWhePnaec=,tag:kaHA9K/mvHNYsv5qZ791IQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWU9LM29TZU9LQmhLRFlj
            NkUwbk53c2FHSWI5T2UyRld2RTZ5SEE1MW5BCmRQT3ZKNVpGZy9UMVl6UXdoZm5Q
            dS9Ld0lDclV2RkRSV3VUS0cvOXo3dmcKLS0tIGowSHViZklOb0o2c2hRNjNYNTBn
            VEhqUXRhbFhRR3hZcUZleXVGenp4VjgKft9SEu2fnDLrW4RJnPhMuQ/iE0wEf1G3
            utsmYYQ4IF9fYrYU6hSL4MNeQH1VepEWdvJLmVdunnu8Ng7eLjfU+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T16:57:28Z"
    mac: ENC[AES256_GCM,data:xbraIGKViy0kJwYarnYdHf8hC1kE267Ga1Pqc2leMQ4lZfyCK8Cw6jVVI4VVAD2A6Y9Dul5YEq3gGYInCxY6QX/TPjKVKuM3t3wX4/7W97Lr3XiTh+70V24F3B0TXz1NWDBxSAiMLkUs7GrqHwlY/PiIeovRJHJlYIctb4WoaUM=,iv:FrFtfKTuqlUMjyBSTp9uHWNW0Fd/mgTI4nCSrthUZYI=,tag:pzmx26mBeD8B/iaBnng2rw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
