apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:shLL0IkdqfeUtS84EFoW+3bS5Mc38QQ2Bc44pIxxKCrsGOoxGz3XmUYVvwaL6YkgINZpDD3+BLNnKU69Pmq4nvbrn7o0/pRHxqhkzEIrL97gcq90SXaMaCVZI+uvU9dv6bSkC79pQr75UEypnusSoyA86A634BjD1fvJevyp2vp9/6ARXpLrYoR2cexhu3ePF9mpypMoumQI/PFapGtfWHqTFzoHjPhL+cBBHHCemrFzMw4S75kgPsN9lC1s2Fz22krAUzb0QjrnQMs4R8yEBAjVR7ToyukN+o6F//ZIPlR6UjECfO6MM4dwKXbieJW/hPzDHXtHECnGzNBNeVHJJS72N4+zu2wHSxzm35QvjiMp37PekvMXGwr9Xv4h24iW,iv:55rxPnbP6YM9883BvsfXLR9ELO0NnG9E5ItnA1KifVE=,tag:G6dG3olfJcIDMLtUKaWmrg==,type:str]
    identity.pub: ENC[AES256_GCM,data:xy9jNxsTrme5w60YLte4CzKt4rlVM68BDTPNt2QrjTgOETtXoBP+1Hw/babtxYm443nFNxOSZOVTfmuUFuWcA+2ddoqQTqhaIiWj97THz/g08/U2mMX84QKrbbsLuhimgs0H4lTfrKM+Ie+opXfzPxgyz3mY5z3X94uWuAIYv7iRjevv0C4fSh7GyjHMdYok/riTKE2L8RFjShUCuv/DpC5ZkMkI+jYhwJB2EQwZflThgrkWcN8iLF4n9DiVI96ru8pGVxGKXG3FUar0pQ==,iv:IgrtV9Wmc1UGTlMHnVbI/nc6Y8lQ9ipySi5jt6+O+Ik=,tag:72Wwp5sNnmqWQloKLXgriQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:+xBwFMas7IEBWekyuoq5qqz3mRfhedr1vjCxwjr31eqz8nWTLBcyhH5GpofArMi/rOAMFYTS9t7+qZg08e8pmk9HbDZhZfKr4yPHRqeDImxxe1UXHubqvweRMypAOtv7dEP/4sBOMuEiIaAJm06e/pW8zlpOOMsurohq986DOSJSLdjpUuH9rBggaJzLVgX3Giej7TXWIweFCUnJ61a9WhxyOdVyzmraHeZl,iv:jkBrxe+rBcetbeeqj3NqaY6v/DsLHkqpRhD7hoJILus=,tag:rbY7fSLxfom9B57ozBHMvA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzNm5hWkpNMm1PNnlkNmFj
            aHVPbDZCKzVaN3I1RXVpYkUrZC9vVk44UTFRCmxiRUNoTlJkdndNZEhCbEhlUVJl
            WjhSZkRmM2g0SmlpZFFEaE9JNXA0Nk0KLS0tIHJPd3pSK2FQZCtNNitUcTB5RzNn
            b3c3LzVVdyszME9iVjMwMU44N2praDAKvwuGDCuLGu4mQYIM+tSpfHRUgbRnAobd
            ZEE7ZIBy3Ir1QTWdmwEQcrEhtjnD3ccIiA3QXnHf/T9RD+dhHNVXag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T18:44:38Z"
    mac: ENC[AES256_GCM,data:XlmX/VwtjTqBmpippD0dQ8RVzpXQcRNYMEtuaLLvmeA7nu1uIRYQayY/3F7b7ZsTyHo+XgpAGc2eA6rJ6PL+SueJUBe5+KezFm/uJ3vkCYwirPhPGnmoDZCxfLLCs00WHBypFhW/ONOBdlXPs+Esy691nsPKyeszLCVeE5STsMM=,iv:SV1ctLd2sEI0fNIJXmyn66OmKXDE9TaULN7ziNPjsOc=,tag:r1a6FRN0cBEO8O4RA1EJug==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
