apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:3Gk5YAr5JqxOQbX+q58XlKqZOM/h88OmNxvPhIuhVoMnqFxMmOZEbCXPuHQ4+DOmJLO7fkhhZWwxrfeFdZN5TI7n24L0zdsr+4EuLqODiaq+7Hulsr5LGtwGU9bNQzKDn4w73uHr3yn+LOmdKC+ayLeNgx1/Hmm/Z+ZUumILspqZ5Ankz02d+KOY5tev6Acw4lFsu9BbQNdcsBW3UvBG3jsaCKM1JilUsw3Gl13N9/sAEA3spaJBvWI/ChnYCxZySfsRgY8oAwbn8RJ71xBGc0xLvFPMofFaUgZFDUF69AHD1qizZEds9DquWbUCaci6QiOSvj0rUTgu8LV/Bo5PNCFZMRmWdmeg6IlBiiwgSm5rpmuAJeOecwKiTH0ieG9+,iv:GXa4oI5MxTEthpbPgOqS+WicbgdxAcwVhqvLRH2XNwc=,tag:/kDi4pFfVZo04J+kl/IgLg==,type:str]
    identity.pub: ENC[AES256_GCM,data:qZrlK9HWTEhgu8o24sOpuWgkmrKd+tWrgIriLfzrVIIOHg8a9tHnVSQrWifVfOTKfd95ng0fEMjOhkBjPAZnCWMvkKgLkx6nSBwca5JZm6mdpL9BpQBy2ejayPVeev4eB2ZyI+J1ShdbrDDE6jWeCnmJVOdEKQ0slkJgGixYT8D122P5w1rBQ0+FdbpUUef9Y0NAn458joGcmFl+/6vzbZgkNNd4pxAwa29HhjvPteEMsdz0WSez5aIUjKC8W7sn3lWInu+ikcmsyzQxpA==,iv:TP2y4d1G2naK8wCMB0KZ96gbRxDhOXP/y7bex/80LS0=,tag:6lB4Q1Z6mYUWZEDTCxFJlw==,type:str]
    known_hosts: ENC[AES256_GCM,data:G82PjQltaK06W8juCJypAElntXUfqCQu88M6fRi2I69Efuc6npPhqI5UAAggccaFbMilpUgcpAjkp2d8Tn2ulb5zkvW6wtu5uYNe1uY92Eca3AtO76Rydv9kUlCY96qopNLOzCwB8/ERA0jnNBP+lghIsubrfFZZCkhdk+qeUn9tTiGGfP4YyWle2r5gOtradG6cd3MzXaqrTYFoM/2ZouPAP7VN1+cbuQjq,iv:4FAF2VgVnOoPUFF4fvPeslEWp+cEbVWJln5jSiNwKD8=,tag:dlps2k5YQjagNAU2jEozfg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLTWllaHVBNmE3Nnh5Mk9N
            N1JMNlJEdk82cnZBandaYk9wb1hQbElLS21rCmNxeCtaV1BjakU4dTEzLzZrZk5h
            UmlNdUxBc0hjeWVtbmFTREpZcEhxS2cKLS0tIDUyODJ0dVFhOHprV1lEa1dZOVlt
            VHBLS0NmRXV6eG43dzVxSGxENG1hcUEK1hFba23FliVBhY/nHWBAV6mjyM+DG8yd
            zNFtQunsRQ9wtTEjXVmPu0bx/2jszlITz5UxbwRxj2l6V7BUZSS8rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T03:10:12Z"
    mac: ENC[AES256_GCM,data:MbofU+f+IjoHeJN6EzSgUzb6OpPfAhKvIGukmFEpzG2UAkn7ZO+kaFsKj48LyLG268dzNZgxarGWew2t00Nar/erl4QwM6cUZ6siE21L9PLj0klfWUaFrybgNffNxOrttgpO5BkCR8sqts1DythCXnltDSQHjsD65eWyHrgDni0=,iv:BMw9uy93hkhfSwNzgcYR/woPWGq4n0bRIQ7n23pve+0=,tag:FWDkxOq2AN2xlkXGSHqPmA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
