apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:7nwbF/vyqvtlLk4flFZ3emQUrWtxQSphj0xE4QqYZvoB9qiQ/M7jZvdbLDR1Vp6nJnVzazoONLPFyBaqfoZR3BIOT4IEOmmkZuG6OfVOloAVbbvKtEAZGqFCqICnzkSfz/ty+p8Rz2ICvTj+lk51PBkk9Zu/Jrc2qWW9g39iurU6gu2xgRAwatPQZNKhwfKVzoeC17AKmXz95tKtg3t5kqZCTa55X3F6WEIC+oGBNJ5ga6YVvcmWe2+a43HmoejYjEi/04BFKFB8OAO6bvQ6YQu5pWVtk3NOYD9tO+YVQ+iXrL4fpULV1Ojl7jTdWlPzydONk0hWFDgHOU3ctae5jsJConmIWcjILipzyTVNDH0IwsTDAX1ll6hUsts5iIIk,iv:7RX5rY2TXUnBPu9ZerRbWlUz4ncM+FvcU7mjHKIEUGY=,tag:0tKio1MlU07tGL04NOHr0A==,type:str]
    identity.pub: ENC[AES256_GCM,data:Wje1axemD2khkYA9zH5nKKI3KaOSw7O1c3tzg2BQU0nArjtFOXBVE5kaEeyKyiL83AbP7pqVFuedsKuzwPOKRYPmNi4YGgJalyKYM/MH+GFtqfU547FNJY+54WCtL3XPykjZFlST8c9mYz0ck68VcQsPAMCgK5WwS+yS2WbWyHeoG7XLJhGjBnCOAY6vNLsX5ch7nsg+XLuSDtk/lzO5tPRFWTYRypCvgY44zn6DB0nruf+FEP9YDpxjwCtxQgVMgyfcOW4YotTV+pq42w==,iv:8/uxZRb5hgZ19tBt2U3t10x70NyynU639nMmDVuVFP8=,tag:hwQ51Ud/Q2DIOI2P1cDXiA==,type:str]
    known_hosts: ENC[AES256_GCM,data:XVK9J/Y/CgQIKsqpsIZrb0pKR67OcQ4gKkYaLx50irvS8NreQdQPcuS+k/WBFglFyBz1zsErgZoIi5aCJcOo8q+w4XsvaTJxsdm8usS6ojdS1hxu2b7s7H8EH9aD149KYGV2kPQBQBQAuw/jS3AjfdPrXiwYJBCVj5Ux2QKlSLSINUTkX6plkSSC0WMR4K2xPDfoDez0kU6R9gaGUWiChR5R9E/M0MMhOBIZ,iv:8tqhFvfkgPwjUPkdzXa69HJmwWEEk+YRHsvy329AanI=,tag:yA9YsfcYsF1fMzp2aAe9jg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVcHV0TklMMytiN2NySHc5
            dmJLbXNJblc0UFM5YnF4d2dxR1pxL1F6TkNrCkhlQkJqdnlENTlCQ3hlZXJ0clI4
            NmhpMmtRN1g4Vm11dEtLemV2TytlUmcKLS0tIGxqQ3kxemZzR1NNRGdyQzVTRWpT
            UWh4eCtCdGZTWlBnYmRzUG5vTndlVzgKGHQudx6cOy5KF9Pwc/tn4W5b6S3u7l5M
            IweN0c7oiJhdfUve240IdOIANoLoAsyk2lwuM7HZJv8Gu7FNnzN7xg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T06:17:40Z"
    mac: ENC[AES256_GCM,data:mTTDNXAQIRFgnRW1+sRcsFdtu5q3c9/F1Iub5MkwkL8e0NDd96ucOI041zSmxODQyorBXEv82H0DFZu2HGDejBs3OI/RMpGdVOMtZtyttaGUZdi171Eidkx2I3zI/EkGL6LEeXoAO+1OvNwXw247hkd+WfjtcXwzLNu2t+VpNHY=,iv:ItUt7BZo+3oiUYRe/BSZ9tTdkpMZF3i+z54M48Aqp0Q=,tag:9uMdDi8CwREZinu3/3e0wA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
