apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:uUcNtD78net61fTvYOuIn9POif3CtuFBKNhhUeJKUjTnSarLRl1m72rvKfxK7J8XyLmB+Z+rzurKM+1e/j8cWrbp5vbzGuqKVxbHYodOxgn8/tA3zMB7BVo8ASs5wPhGiQG5DfW2QUE1dFTs7w7+cFqmu2AY0nE3c2OoJJkoxqv6IcWNJJcGMQFiUyeekIpzlzqa+INnCQOggPFOkxk/AkrPYegeru42Wv8X2TugncKevZ8JIsjf5d7h5aLnGyS++yU9NJIDP8sn/aH+5YSJcQJL1IYpSYmhtBmzD15fQ0NFmeHlFe80Nt9F7+uD1eVPaSCX7xNmYMOTykpH5ILduKBRJH3PF8UR2FgmCUyT8xyd2Qqpk8oj04Y73Fz33VfX,iv:Y3tnH/8irI32iORfvHQ/miF7Kea67mO3fMGvLyoZeDQ=,tag:92sqiTZYvZFkxBIYf6l9ew==,type:str]
    identity.pub: ENC[AES256_GCM,data:uphOgpF5SiA+PgfuVxh/cb1E1kw4gncq822mLsgWm97t+tzeEcfqc82jk33g8NaV5He/kl+zaQUj6Khy2OVUI3jw8N5Z3sqD/B1HNL5OEQdFXRP7R2bqlDt0wCtuvmBCmgSY8u0dXxniWbH46aiQhkJ+3AfSdliHqmu5ZjjSWAKGfghZ0WHaTaKkhlQVhk36jRflpeoCOFtEKD3ec0JF4uN9Emql2q17yQNxBV1YKzsVLaGtsmHdc6FElKw/qDwdvYbEWFbma6U+MOy89Q==,iv:ifJtWvUdNMyNUHPGyq09kILbekWWNMVjv8LW7rvMqmE=,tag:DmQ8dwBGupNBDH4S2uegWg==,type:str]
    known_hosts: ENC[AES256_GCM,data:QjZZIRvVWA/hnUHr3wMzQf9zrSuX4vvT4+hKHxJUlaELcyPMSJnvcy4Hr6szqUmOymi+kmS3CXNG0vp6wohN1Ik2e7xHazcMZuKhSzQoJObJRvYoR5JTFxkil6xAkYXbyIQ8eYZpE0/iQXVr3wuyVe/fZKs86Fkgl3QQAMbb7nqhP+rJ8dAMZ5JdT8n9JYE6AGAvOMgxsfWugNDKU/gH1Uqf8He1Jm48jEsw,iv:4XQ4TQ+z+WKzpKlJJVY00ILahvAoucq8jiObOUOSm64=,tag:93E52Ve2Jp6uoSmG6lzewg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxMm5FSEFiQmlnYkw4WCtt
            WnBRUWdpYkVVaStXdi8vTTR1aE1LTmpuaEdNClRXOTRqZVdyVlNPT1E4VHZ0S0sv
            eEFuUHFOT2N4eEUyR3dUMDI5bzhXcEEKLS0tIHRMaytkYVZxYURuT3kxcGtJYTBR
            aVZEMlp6b3owSlpoOWxsbGpQNFNXZDQKsyMT1lBGsSc9+dtJNSrm2WXQmfD51GTl
            +rzARJK0aTb4DLoqUx90yb1EpLUoqTWwXVfFu+80f+px8xksa2Es4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T21:48:45Z"
    mac: ENC[AES256_GCM,data:W1wBjG03SinqhmMmjJquuLa+SW+rCZasO5lkaJy03+7sne5Y0TsiZTkvnIb3s1SPxQCon2RylKj1fTAe1siuzfj8ZIpJEB7K/NLT3AVU1X6vE2iXwtN0sb0MHW6VMNFZIZcMHh9wPm/iszXWmREJfH+o2LVqH/oPT0X/25uUC2E=,iv:CSJGJYVoIZNxeL6uv9vVila9DAoM/lXz/eKXJyhGQFk=,tag:m6ypebvNb/S+I59Rqdl1Gw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
