apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ra/Tx1Rgoyvxakv49IX4Uh3u6D/suV1UqpX9dyDV8LsIntZr2I5tGQJYM4ESiM/iO06fnpxyGChZLPkejduJaAHbXpg1KzREP5xj1H1kdJ1QWxAfrk8vljHdIJ2eZXfkogUKbec8vxKZ4VTsgAx6KO0CQs5nLaZCnJH1XBWCTPNIlRPrZHb5M5II81UDqtjVHiJcKUVaoNnDZW+n4dX2ayJCkGhDUbdSXKLEnSXEnwY3Hnx0SOBYk73YIfLGBaYrzfqYvdfKaPkADn6e6UHgvYJwhnqtFN+fMFF5AEwPmM1vVV12ivYVk3IHh9rSFBTdQiGmojVmGcpKmGoBndbuf24e7o49TrJceCK6Y1xCVwnrlGMEXnmZjmN0t5crfU35,iv:IlGJK4LZNDrm6Y7O0EgzH5W204tN/Z24JNIS/igV9+g=,tag:wgSOCgh0HoOGDyplkQeaiw==,type:str]
    identity.pub: ENC[AES256_GCM,data:gCdg2K7vfa8Jveho7eP7jDsjND44zReA5LMc/ilt8+5km8o2l7OgeWx5dYV45l8spHR5m/ZFMGhJ/UKD0tcjQUl2FPOd8DcBCq82UUp3Qo3zEGzr1D+v/NrHFY3+OKjt7RQqDGsQBkD0AbIi5sfKmx0YKx40hiQ8B5q52dnqtPDdA7JQZXRRDGoPLxm/aXpl/CuE3VqCiAOcUsEPlu7PUehPRtpjmzqBfHeHBdh2LJC6GJK9PSYTnJIQn6ZYmk9Xqpqnn/hoS+lDQgkDyw==,iv:yOWDiQjNRfXrCKFMkeAqW4bGT47hf6gALQWcXBSihJA=,tag:kUZzC0TEpK4C2qYY2yFAFQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:oDDX2opxTu16fJwECK6P/gxhSuYgGJmpm5S1HzHL9jsGPC3n7mQiSrqlDLREbTofJiC4Hj9FfaeYIV51zqoq+VXZsF3F74Nfs9W2YamyO23mWu7K6T6MvmdhTmCTk2Wla2VLH9rKZE1/7Mjjmx9Iv2yp7amw3bfiby+jXUuBWsM2cmxRC1q8FAAz6w8jgauVcCu4K/5jYteR4e/swmwJNgkF4HDBJ/CuYT5j,iv:C83rrl6GSYkz4ERN8ap4fGYMFzOuoOXmdlBLuicFpsg=,tag:iMIvUnGXsXn4FCiBf2mksA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZDc4a2pwZDE0ajBCZXAr
            TnFNQTQ4WEo0VStEUUJNM3RUUDBlY3BkcndjCk9LQW5YUjFwc0V6dmY2MElyUEdT
            Yi9GR3pBVzgvZkorYnF0TEZ1SjBqc0kKLS0tIEJ1SVo4L2ZqRm5lRjVMWUF5Z1VT
            OHRXaERRYkpRUmUzcnl6M3VZUDVjSmsKcHlt67hMFfCgtyht5uNUc/Lu1JleGNEA
            xdeGWX3p4YNRHqIBwm1bCLdgiz88a1ZIUaYQL9zqbIso4ESt7AZXfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-28T17:35:22Z"
    mac: ENC[AES256_GCM,data:z+F9Vh3ZB+TdWi2grsL2l38tZBK4EXmZ0qP8fsNlxDfCAIn+lRneNprM/NZS8H3Pya8Sd0ZFrdF6nQsOMoxrO+HSKyQqJaVdfXrbV1HBgMdt58DsPR8efrZUielLL8nxcvfl1pgtDRgHiAeWOR+pJ0Q5raJIOYk+/DA6LVr1efE=,iv:FE2UFfQ9Hx+HE2A9UP+GdJjfZhfpek1H9m+hj8tS3Xo=,tag:sY6fHi9dUasrLtzJtwdtlw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
