apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Jhhiwae+AggV07K0JY+WEjVsiWyl5Gb6BNcrhDbV1PbzmNW+m+s/Pi7NYIQFnefof9RJsMOdH8+uoNtJwdpC+YYmRr3vmf/zYIbXHnFsbJrR8e93Wj/BK4xfkQ23sRp1uToTpvmXyAGGUGItcUs9xVWqj93jDg1RnBylVNkcuBK/3wqGPc5/Q3fAS+LZJ8s5SIC1CwMmnA1yLjmOP1lOnwqVxazheJsre7Ya2/w2atI+kZg+7Eo8yPCM0C032ScfAVIewXnNcBwcidPXk6I44Bk/+7qkNN0incjS7xSzWIhrZ3hn+QcIepAX0bW/VoLprxbwOGPrOhHmCBMsSj4ocQtxAeQEuy5k1crPFPvajDaNSYje2NmEkQ9jUMwVdv0l,iv:OlteqGL5jGOAoWy/olz/ZbSAGfQoMtfcL2q5Bu9S++g=,tag:1SONBWz7WxxYxElS/SiRYQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:VKj69Alc9KQ5Me0SRl7lN7ZVuvLNSINBpgZTk2RDvJn2ZV9QP/ocU2MoK7WCiLAfmWmbXHierJkB4ZSigvqFxO/nEyrIzDRMtmkjawBwAcjxYcBqIkAelpFep7Y51BWctrDjENnMVYy51JpnuFKdMmFzMMHRLkWuk8OabdF6Il6euNxrAntfsOLMPHR2d0sHjNdRaoJDGnp6p0hlo+9m0emUggCl7epAQjWwKYWX7xPVLhzalNiqOcut5hmLyFoVwHzUWi6PKS4/JmTw9g==,iv:+9s4W0hjFUstDC/sq7xUHBBD4JchRLWzIa5xKafCnu0=,tag:D5hkTqx65Ei61HnnbuEbAA==,type:str]
    known_hosts: ENC[AES256_GCM,data:bMJJDyZoNjNz/WOBMIR0QYTTZhK+h979sqiJvOyNZFRE7xP9A0BKme8ZXq2+QxpWQa4xxuQvcl7bvl4ba1NlZk8A1hunN8C3Tw5mRV7foVxdajVRGCNDvhvkQp2ofVecGoyYCYGhDnv6wic1ys2bgLqLQYcO65tRjjRoX2ZG+H/pkYOnSgFtIZdo6HFDpWkrSDL+p20mwiDGqqLULQTrrTTIDeHmVuEojzY4,iv:rbBk1FVTArPaZxqOb0gDJ7opt33DsLyv3udq7rmaWCc=,tag:zDCBkCqPHvdvfKBb3+4seQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPQW1zVUZZVzdsN0t4aTRz
            dWJpTVVPa0R0TXAxL2pzSFNrSmNSbStrWEhBCmx5TjlFSWppcGVuSVQzUHoySm1N
            MTY1S1RXT1h4aTdvWkd6bU05MjFVMUEKLS0tIHZQVnVFOVYwYm5pZGtHUEhxUEZx
            YXpjZ1ZrbXFYRGJuWHhZRXk3N2VjV1EKygeod6dxW9SMTsWi7K8JvcUa4Wf7SChO
            FhNEz6rvNJ55YBAn/YIAkgb8gAZW2ui1cft0QFL81dBJGBTN0k8T8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T02:50:46Z"
    mac: ENC[AES256_GCM,data:S/G4qroae16AEwzSUv0ivcWCOvD+UCW7rYXgdgdi0btr/sH61AWGh1qMh7ipLeHPjICBGofvYvnxlXHsnJ+m4Rs/lyhfp+s8y6Fm1Bm4+FO0sRTm9h1j3zqYvzVYS0Lc6SdGxJ+lcQF7B9AJ2UFNbZOPZoV+S4e9x1FwuJ1nE58=,iv:gY9P3L9SQNmf4SCWpQMJ7qgJLx6w4RhD2KtwsZVhTKM=,tag:TLdST9I50O/zmD547f50og==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
