apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:vDxayvO9u2+HdoQa79E4OBVMfaT0tyIlAZ42vdONb1EVJoNEvtzoHxxhaVFZFhegbdyJcxDA4PY3VtkNLWnFvEvjEABZQDSpapZRrOBlFvRI62Tm1MDPAzHlhhVliwAJVvqeMBxMxFFEtS0E9SDs+tOXexSaQeQsa31lYwPp6aaAXb4QUHlZqHEK0h48TvpX2/kbKzYWu4wTlx/e3X/j4ci5O4hJTLTUSwBsALJDd7p18Sg8ukH6IYjzMH1UU9EwnEwALUsou31vwiHjTYvQGuSYmRU/OOwG/zLE88IspiAw7/L1UIziKdLIulOqlCO/qn8bkK9L2bKfVWvPTJ98DycWK9QzMPbb5PeurcozvEy0VuH38Ig72z5tAtpito9W,iv:SejidsxTXsEhRVM7TlNsMlyrAim9FCKrATwo1Ma/fj8=,tag:B5GqqeHItkuUbwJyXJRLyQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:rXQ465I10fSG1T1i8i93pgDHksTeCDDg5JLQHsaYX+OxXzQla5TMLfx82/BGuvpGyK00M0ODfXuShAPm9zVrFDrqDe9+0XDYLWrcaWn/HNh05QfqdiJhO+IHwM9SZRUuiTDa7dTUgIe2He4b/B9h4Waskpshpn8N9KrLn+C/GgWA3Z4S0gxHDY2EsefQlVf2EAJ6vIskeAJq5qwevPUKy8cwJsKnvIKzVmOleIBHj9VgvgmKsiN1iiVtODSsqdIY4X0w7ONKCjDrYc7D4w==,iv:3Krcnb322r8KdHRb8jTacNqAXK9a/rXRb0ujnDlwnOM=,tag:rj2XBtbLCxjUnaP3QDxrzQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:2SDqIjYEhbULUGVJenf+HAxWqQrsN48LjL9fWBc9MsX4/qDL/v0uZPp/SsvaqkZJhK+k1wb2qA+co6v4ZvNC0biY13uINEYrQvOrwAGUK7FjKxK6zijjRVBbKkNZm5JP6C7fmdgkBSW5ppdchBYtrS8IZTqDCfAGKgHXjNUSubL5C0arHcMyNbzCjBtD/jD0JMybMiQyPrU3PETck9Hg1fNT8Yz0dQmVNpxm,iv:/13Hmq4aRnMfVASiL8bOpYlqf4EVasMxUG10M5dk+jw=,tag:F2fIeq8H4mV45mNSyl1j6A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0THFSTm1QK2g3eCtrSng1
            QnRSc0NVUnlqMExlSkh3VjRBZWxyS09SaWxzCjg2ZUVDT1NkcWxRZklDbVR5SzBn
            eVJjYzNTV1FGNXFNYXljSVN6U0hnbFEKLS0tIFF6bzRpbVNzVlROeUFUQlJkTk5G
            OGZBUDhPVTRMK3NGUG5NVDVDZGdGRzQK6jQQjsAewLzLa+F1pZmdUDoL8x/EZ69b
            FwAniNov27j0kVK2sjwKrU1OVoj3OuKU3gh+g1bqa5m9KhvkVeJ0IA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T18:29:00Z"
    mac: ENC[AES256_GCM,data:PedhNiDb7W0di+8z4t5wmjIS37wfzgQmRzb4KEo++g3RLdRkI/nDLWnU50+3Yw3ZmcPrM9UV4vfMbneORLkl11acRf7rYU7rubFMOSm2QiSf9FnhcQ1mfgNbQgYM/Ayq4ksAB1rH5nF3B6F/FEg5WW8Eo+4mpJIejiNFFWc1kXE=,iv:K7PWjfOeXmTyH+fdlxjA1MuO74n+cBk32SEJZSEdUFE=,tag:ZekGzN8uXo7zwBJdKIa2vA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
