apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:2Bin+2eOGkwLqPUFdlLg06j/gjJ+2N/xYX49gnriXBrGTq7PA6xRNvei0vX5VVZxrkhnM+C587CxB5iukUtG2s5bc/omYspgPWyBGPRAOUMz9YCZEiuF5m5XF8xO9wi+tYy0QOPf+XoG3OzlJWwFtyIE1VE3xskOlxvrBAUVVBYczixEXAT6P79wzpFrzH5K7664oaSE6MVn6sBMGc4wG842mmdqz1NvzAXZ3IoQltLpVnlv+H04W/FAM4vuSK73JeeDNY4HvRcJoSqFGPcqfRPZzORExHnZtdZ073mTt3U7G2m2oaeZmGvVYRhR2TkUp/lTAqbf9P3r2N/qJ1lOXaJWBOhPUlLQnT/5SF0VdHrbHQ4najvA1C61T/CSKW7K,iv:4RZ22khDv6hSZJ5SAEkgr2Vt+ROFbuPv+AQV/gyQ1WY=,tag:gm4qF0y2+tSWQTcKSRIz0w==,type:str]
    identity.pub: ENC[AES256_GCM,data:CJyqBlMHRIyyBc/vEZg4cbUBSqWjSbp1MoxzGUpWjtTrki/oF07o8jlvTTwSXO97zB0opdlysavdxZ2GMdZBF/f6VFq3Fc8rr9KXqyrIbHLNAZyLSA82DW7Q+63PflWqvS/VAez25g9MrehbDztEOpeQ4gmd2AtaP70Pjylr5o6j+5XgXi14rN2WbFpQ71evZp/mY/CtxvXRD0lJ1lhznFe8uZiwfzWpEZbs7T4nJxMEV5itx30tq895mEfGpXZcYt8LKDtW329KdPit0A==,iv:vscWVENEAlOW1d6Q4MstVOwgEv1bC9RGPkbEK2s6CRM=,tag:ixp7p3ktHM82iz+nrcemsw==,type:str]
    known_hosts: ENC[AES256_GCM,data:ayiW6zd6qlwWeMWgrybXIgF1pj4MKb73tGOh4IGy5E+vTe+1y48CzfxhL4Ne7Q484UFf5Us/grbId1RFDsZaoqs6/spuM/ERCrCJfULxF39CGgIyU6qQAOIq76WMRWEetxvNnzG2xEnYUURZ1MWRfym/R7jtVW0F6QNktw/uyoVyHwWMgmMTw9ddFm6ggBCjC5HFMuA3BN2JtC4GvmFiQGFJcPl+ZCtfXEh/,iv:slepCGZ3cJl6Xjc5wkjZ1O4FjoCmm3zZQwu1ZoUSLxs=,tag:RrPdWJxy0hb9gUF+kH3QXA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZWmZ1RXFmMUZ5TE5JS2pq
            NzNRSFEvb1dJeUY2M1l6Y255WmlxVWcram5JCkJEbUlPVDlDQ2VwTk1mVXh0b1BL
            MVU1cENDOU9sNHFTbVExMGpBVHlBL28KLS0tICtKSHluWDBzOHg0K01McjlNRDEv
            Q0tNbWJ5Q1hJanBLS1Q3dHlwelpUQ3cK2k455iJEfa8MLG138TuVLLAnJ038sBCV
            mo1AZs56OpKiEDgPsw5m4oVvaMAWr2xI6XZNAAEapI83sYboTbDzHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T01:50:07Z"
    mac: ENC[AES256_GCM,data:m/UFU4XNQje/tAh1asAlESdp5vuUJDfi7aIvhTFkmyEBKInq38zqQiwqJDYYRGmKM83zIFJDi95JD6GN5Hqc8+XdfSNsXTMtugluTveQs0INfmZbobRMyMhNXeSdstOkuBKRC4HUxbauuWzv2Pc3KBw67c/FiUbvECxaQwLVxdo=,iv:K1yMEe1TI3qXWRm+PQyIkIviYmRuv5QCIalFUU9gt2E=,tag:MNgxgT883+LkCziwKUUpTA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
