apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:3DHwvDcy5yxUS66kuFD0Qy/jamB2JNtQRxiDTK+tgeuwsh/ZnrHRrDLT1VoMwvFF2lDgvyWojfV4EtU0d7Utk4rsgQ0o5XIhh5XFeBPsKA6ofr/xzyAMhexOpeu7g30YCM9nhXFwPHkSf/pqQdg8Ec8+OBZQnCp2kSZslxs/5VPJD/Na5J7YMrkh4Kr/uPovR/SvvstjkM9M9OzqbtHWucA2EcEfeX89bK5J3EMSkUfPU+f5rBtHGMVH/95G/EGuoeCHxtDWQ8eWGaCowIiP0vCzb6VHCcbYR4+Qq3yYRY1+X25FidrB/oKLrJP+xxXZ8tioRnQOtf4gSbiFuoCxSBdE3+x2a/9nFH8KeZVTIaN/KzAZChj7Vu66pWFx9no4,iv:5+Lk+hJTYUmmMiY9RvAUYtB3dHNshsriu75RWdGi04Y=,tag:lZazgJXdhRMxTQNgdvjoEA==,type:str]
    identity.pub: ENC[AES256_GCM,data:se6D4vympCkhdFRuTXZACKJa9zcNGmlqooWT4QE8WAF4mKmOEkeIMXwItDmoDjEUIEvMXgEBEapGeui4uPAlG0IqQgXFpQ+Cjr7Xd8be85V5bsZ5FZyXe+JRk2n1zY7hGzamNyOuUGzPq75TVB0Mb2v113Oxl0p9j44HNJNuRj/Iq6xCucZTKX1S6sG/zySNMs5siNcURN5lT/WL+98fHFAjZmQ7UjQR+XeAk3ytmWsfPn/+3XvqjLCXNplBu2NDd72IeiftTubOnLYvMg==,iv:YrJJti6BJXNW+rc37VJ/12526AoISjL0GWqmPmfONiM=,tag:T8YTuol4SE9I8T/EedFVog==,type:str]
    known_hosts: ENC[AES256_GCM,data:iMH4phv2TZibn8fjCvMoazAvCFx9Ks6Ks3xe8YwZ1+sXIe4I3dNZJdbPLp1BCfo8cjsrD7nH7gCcldYQ/3+B5O7CihGDpJhMXrRnhDcOSRiOv5ZhHVrccvwcC6a1br+9N2Pq228oUzLHADQ/GeRWpywIStgysdJJ56HtM5WeWia2eCkxUsw3nsSq0x7c2XluaKJc3O7c59kNAqUaWr8ERbqmtdeG0j5LQ7lZ,iv:wd7GFPGtmuySnda9IRB3h4GDydh1rWFCxy500GM/PR4=,tag:5E0Ssd5yWKOyRECJCUFdGQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwUlNNL3lZQUQ5Tjg1Kzdn
            RFJtdXEvYnBPRk93STJNbzdHejVTb2R3VnlJClcycGRDTU55WlFRbm5kcFlPenJ3
            N0lUYUZkS045dXVQMGYraEtGelkwdlUKLS0tIFVSL1BIM0xJcmc1VXp0YStMM2Fk
            WDJVZFlsU3NkOW91VkRzK2ZuazlyUUkKCCr9xkZbWNIcqYgGR2Yro4L0dvuO1WPM
            co6RqWGPrcGcNWICQpfs8inSyiE7JQGznm5+41dmtRyeqKfjgKCxZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T06:39:49Z"
    mac: ENC[AES256_GCM,data:DXuJvkKoN98K+6/wR4VIJ2fcR3pdOkjBzg4/Rwt7lcoRB8w4XIuKA3gJllwoGCxWaBij4+bCM59KfGUq+6PHfcdUcusMRINB9QFZtFoDnT80Uf4D/jx/J+X78B5Xwi/KTHJpLx5ZE1dQ6XbjOkRsaXCmrySLj04OqmCSTHo86ZQ=,iv:4tJh9wbvgN8Mv9dSGP9JHGqJZG1jqMbJiE9RNfMRH34=,tag:k44xfjwXq6qvfd+HegAcew==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
