apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:o4Maln46vFcd9BvCqac1jQYTic44BrE+EuLi+dQf1VPYC5KsSKufUXU8DgtJqxIP5Reklu0lSKXFBtTVN8TDFkjlooNltKWKNc3Pla6Rd/NR4w/KIZrc7yY1tfhIU7teOvFfJ8cch3yQKSOf+0bvKox5hyqfFW9KNB/tUmFwlxa4in1vdmOh8ZNkwIo+/tuLaEs2KRsEHacugAA56puig8x5awg7QjWEgwwBpgzws5RjtmmhexBhjbGHupeGCKww8dy5F8+o/8DncOO6H0RfkwoUZ6npknMVzjQWrcR4SZj7hOXUKG0fjrSKqqw5hUyCX/CwX4LB09g/QevRqU5ufseYET52awLEaCwJcvC7h6NX5mjjqf7a6tyewkpWvZSt,iv:oEqXh4i1iEXsgUxj+kkHF1e9mCcNhrNhLNYe2WGcrrY=,tag:8h/JDLdlInRTDR4alYOrNw==,type:str]
    identity.pub: ENC[AES256_GCM,data:1jjeTCqHo2PwurUjrfqpK49a12j/Chl0MOKvtbvBJXO0ZAkLt+MwQkNaqkyTgDGgFcUzaHTDcr+AX2jwd7H7+K3MMnJ1rbjaqESF3cp69UxSrxlT8kEmH0C9gO4EBIEF/fYzK7n5SDQYTXzgp2mngqVd6fwYQCMpUfq5nE3m9OoEnKRTfhRJ6vlBROV2HAkf+0+pXtxlrpPHRSsYtsdBzSKl2PjV5u02eX4F2zDcd+xnuPukergGmO2yU0Zq8DH+k11VLzXNB+Yoj38WCg==,iv:pp5JY09Bj6g3/u91kbR/dM+rXoNfgjeHu+rlPJf1wiA=,tag:gnQCHTutPylWlL3XRNtd7A==,type:str]
    known_hosts: ENC[AES256_GCM,data:xPdcZ1CdmemU/4CiYWkW7/nfS4zvjToczJgpAlynhncMPadZJdm73Cl9ZgARbUHtWp999d3NtIR6jUnVG93KoQ720k7TdCzbz1c7RuBvqxM3yLypJz6HtNDQYLmBy7Lgt5Ss3VUENJ45wjLG/wQLAYOkIC2x/0UlhyJQQk9ijvlUohr66g2mf5d2w8oLeeWPp6f22u1YUGchTfytql19cahzaDxXRUrEOj4Y,iv:qFrHtv34uhe4l827Uo6nqbbbuP96isB2uh4m+8YPXZI=,tag:urQ0LjMJMLySQD6T2jEuWA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvR2pZQU40ZGZCcFNkenBU
            MHg2bkcyb0pjOHFVRDludWxncmllNjhVUHl3CnMxODlaQ0VUUUJ1THVoSHYyckhy
            aDI2aCt0a205ZGdJWkJueHF0QllQSUEKLS0tIEZ4aTZ0b2d4dWk2QWxRamNUUklU
            WlZPemhqNGFGM1dJK2lpNmdzK200a00KcsFfkirSeWsY8uM4Q3UOwOzpgpieCvkO
            3iGXSOvcYPkh558BvHz/CEKNBeAql4GlC35ROpzx6zfqb3YOiaa3Wg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T18:38:10Z"
    mac: ENC[AES256_GCM,data:Cj433Bfz4Zet4GD/eEBl/p2ongi1yjKcQdTFRXaC16TKzG9Jyc+8HhGRcHvKk8tbTTbBa34TGzGjTGw2wFrDKO3LcDbjY/yJU14qykm4e2DHn5WtAvyDkuexsWV+Ssk1SeoUT7O+fROFVw9Y6VAVRuCQiYjd+4/qolu9AwbDyno=,iv:4h7o1d6CWV6H0jR9Xd3ZRXu6rcQEsHz3BOyN2yLHdb8=,tag:yh3TbCS+qXhMdoD6fZzu0w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
