apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:w4FmikjYpI3vhu3qrACcl1HmFpZLglaw+xMvsxQd93GwqGGpE9LC2Xv3sNFgXa9aZmdyJAdq9i5LpgcO8pBwl8wtllsFffkmthdU821iGBTKqA/VJc7niAIbYZWStl1D4gP6dFtT6YfmetH4pVg5xjPrVbE7jrtm5+QBem44Aicow/lj+L2bDeWGEuIvlX1vKqYk2itw/6KbN74Gby6k2FD5dkCX+WCciH+KlgbR5OMLMpNzNOnesMm+j6e2pOOu0TjahwNuViJ3LCsTtnrxogJFKUjRj/R5EmO/CyBzTwCE7U9ojm9b06FHJkA6+sumVzog8DKfgwtk7K/1SB9D26PL64mK+mnRxt4otHT2ffDcYeBfHUoxkAzeCab8jujG,iv:JalayFtbkKFwDmgoQKF8sv8kpg2GtAbtG6+Z88G1b+8=,tag:nEflRzyZCHAWa6mRzTubRw==,type:str]
    identity.pub: ENC[AES256_GCM,data:QzRIiUMSF7FUhLrAjU7/maYMqs8/0JMD9gs53vgx1TU/k9WzXX2DunYkb7IgzHUMphoBJ7x/rLp+QKHiKIcZ2cT3kPQ9Oxxp1w9ZGOlCx4RP63YvIgYORNyAeS0+tEV+NKEPWpsGskr6SJmMSK2c0N7u8mmq2jpx17/aKpkxFNCzQRJhrXO8i4ygrsO4LVi1H8++P3dhqYlxdI9fxiqSUQAH1CFHcPC35371QMbwnOdZO4ni2SfckBFcbS8MXBQW4GsGFwQd19/c6AkAdg==,iv:+AGxGjZJmatzJ4EhBdnArF5ror1Uy1snpUJ5xVhRwFk=,tag:eXweBHgo/YY00geeZSZADA==,type:str]
    known_hosts: ENC[AES256_GCM,data:FGv4mc9AeoHytVYaq1XnPKvicF6/Cq86FAy8q3idxoHFcvQkfvjWpdVsKeBdzSTAqlwN375wgShC1/Id8a0eYiMGXyMhNbsmfKPZM01w0rxPtfqAWPg9gDil+7H5Ix2s35hJ5FY+DOXY9j4MOB3n3ynzqYpJvTfrNk2j884Sc3yZUId/AVDu19GknW0LiBUXrGScroUdkUmxZwStrFH3u1qmrZYHMrcsXoz5,iv:gr39ubspvLa0plhfmOUMFoTOXt0aJCNbgn7wjlAmzCE=,tag:UxOpNGaNgrLkHJ2y+ozTSA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpcklHNXRHWG1kTU5FMEQz
            Q0dBNE1NMm9DS2plcDRFRTJmRVFnKzVkUUFjCkw2Ty8vcm9rVVVmNXp5MzlOMFpJ
            cjNBOXN2LzJONmF2SDUxUzBLcTdSSG8KLS0tIDRLeEhHbFI3dTNrbW96d0tkdGJY
            RXkwMlVidEN6RDJHS1RWcDRYOXYyS0UKEEm5wzmHeyMehIXCiG7hg7lfTubzNm1O
            D+kGISmdc38tXLqslo+hFEPdiZZ+Is9uG+t6+WHskXgQeNFNPb/u0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T01:33:09Z"
    mac: ENC[AES256_GCM,data:Rkv8YaJOQvVwDTZjz5IwxbNTgcP1XnUTkZFuQ+ducf9CltSDENdnRkchKTjMXkoT4eBvDAGNBM2CzXkRd7+ZP8A8sMhpgEBUCfvFYXrmdoRp6dVVZoGVYzKiaOaOZb6yqogdIX1RIaOtS5b9iZ6onTo+pTVqL0xgafdBRPuNoWw=,iv:QGr5NbtaAoo3eKLfpsamLi19S4899qvTqkzKmHkEtdo=,tag:QUw5UTmNPowzy1MyviHAYg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
