apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudflared/ks.yaml
  - cloudflareddns/ks.yaml
  - nginx-external/ks.yaml
  - nginx-internal/ks.yaml
  - wg-easy/ks.yaml
