apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: headlamp
spec:
  interval: 2m
  chart:
    spec:
      chart: headlamp
      version: 0.39.0
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: flux-system
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    extraVolumes:
      - name: headlamp-sa-token
        secret:
          secretName: headlamp-token
          items:
            - key: headlamp-token
              path: headlamp-token   # this will appear as /var/run/secrets/headlamp-sa/token
    extraVolumeMounts:
      - name: headlamp-sa-token
        mountPath: /var/run/secrets/headlamp-sa
        readOnly: true
    env:
      - name: HEADLAMP_KUBERNETES_TOKEN
        valueFrom:
          secretKeyRef:
            name: headlamp-token
            key: headlamp-token
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: le-prod
        cert-manager.io/private-key-rotation-policy: Always
        # Adds auth
        nginx.ingress.kubernetes.io/auth-method: 'GET'
        nginx.ingress.kubernetes.io/auth-url: 'http://${AUTHELIA_INTERNAL_DNS}/api/verify'
        nginx.ingress.kubernetes.io/auth-signin: 'https://auth.${DOMAIN_0}?rm=$request_method'
        nginx.ingress.kubernetes.io/auth-response-headers: 'Remote-User,Remote-Name,Remote-Groups,Remote-Email'
        # Add auth header
        nginx.ingress.kubernetes.io/configuration-snippet: 'more_set_headers "Authorization: Bearer ${HEADLAMP_TOKEN}";'
        # Homepage integration
        gethomepage.dev/description: Headlamp is a user-friendly Kubernetes UI focused on extensibility.
        gethomepage.dev/enabled: "true"
        gethomepage.dev/group: Infrastructure
        gethomepage.dev/href: https://headlamp.${DOMAIN_0}/
        gethomepage.dev/icon: https://raw.githubusercontent.com/kubernetes-sigs/headlamp/refs/heads/main/frontend/public/android-chrome-512x512.png
        gethomepage.dev/name: Headlamp
        gethomepage.dev/pod-selector: app.kubernetes.io/instance=headlamp
      ingressClassName: "external"
      hosts:
        - host: headlamp.${DOMAIN_0}
          paths:
            - path: /
              type: ImplementationSpecific
      tls:
        - secretName: flux-system-headlamp
          hosts:
            - headlamp.${DOMAIN_0}