apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: statech-industry
  namespace: mc-statech-industry
spec:
  interval: 2m
  timeout: 10m
  chart:
    spec:
      chart: minecraft-java
      version: 34.1.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    global:
      stopAll: true
    credentials:
      home-s3:
        name: home-s3
        type: s3
        url: ${S3_URL}
        bucket: statech-industry
        encrKey: ${BACKUP_ENCRYPTION_KEY}
        accessKey: ${S3_ACCESS_KEY}
        secretKey: ${S3_SECRET_KEY}
    service:
      main:
        enabled: true
        type: LoadBalancer
        annotations:
          mc-router.itzg.me/externalServerName: "statech-industry.${DOMAIN_0}"
      rcon:
        enabled: true
        type: LoadBalancer
    persistence:
      data:
        volsync:
          - credentials: home-s3
            name: home-s3
            type: restic
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: 35 5 * * *
      backups:
        type: nfs
        path: ${NFS_BULK_DATA}/Backups/Minecraft/statech-industry
        server: ${TRUENAS_IP}
    workload:
      main:
        podSpec:
          containers:
            main:
              imageSelector: j17Image
              env:
                OPS: Hydranoid620,b227
                WHITELIST: Hydranoid620,b227
                ENABLE_COMMAND_BLOCK: true
                VERSION: 1.19.2
                TYPE: CURSEFORGE
                CF_SERVER_MOD: https://mediafilez.forgecdn.net/files/4708/101/StaTech+1.1.11+Server+Files.zip
                MAX_PLAYERS: 2
                MOTD: Welcome to StaTech Industry!
                PVP: true
                MEMORY: 4G
                RCON_PASSWORD: ${MC_RCON_PASSWORD}
                FTB_LEGACYJAVAFIXER: false
                USE_MODPACK_START_SCRIPT: true
                SEED: "-5088804881017501598"
                FORCE_REDOWNLOAD: false
                USE_FLARE_FLAGS: false
                USE_AIKAR_FLAGS: true
                USE_SIMD_FLAGS: true
                ALLOW_FLIGHT: true
            mcbackup:
              enabled: true
              env:
                BACKUP_INTERVAL: "1h"
                INITIAL_DELAY: "2m"
                LINK_LATEST: "false"
                PAUSE_IF_NO_PLAYERS: "false"
                PLAYERS_ONLINE_CHECK_INTERVAL: "5m"
                PRUNE_BACKUPS_DAYS: "2"
                TAR_COMPRESS_METHOD: "zstd"
    resources:
      requests:
        cpu: 100m
        memory: 8Gi
      limits:
        cpu: null
        memory: 10Gi
