apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mc-test
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/testing/mc-test/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
  dependsOn:
    - name: minecraft-router
