apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lvm-disk-watcher
  namespace: lvm-disk-watcher
spec:
  interval: 5m
  releaseName: lvm-disk-watcher
  chart:
    spec:
      chart: lvm-disk-watcher
      version: 3.11.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    configmap:
      disk-config:
        enabled: true
        data:
          disk-config: |
            k8s-control-1: sda
