apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gpu-hot
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/devices/gpu-hot/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
