apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: monifactory
  namespace: mc-monifactory
spec:
  interval: 2m
  timeout: 10m
  chart:
    spec:
      chart: minecraft-java
      version: 33.9.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    j25Image:
      repository: ghcr.io/itzg/minecraft-server
      tag: 2026.2.1-java25@sha256:44aacf3902c1c2e18dddfe8585dd44badbf56a0a768c773a5e0bcfe4bc1d0443
      pullPolicy: Always
    global:
      stopAll: true
    credentials:
      home-s3:
        name: home-s3
        type: s3
        url: ${S3_URL}
        bucket: mc-monifactory
        encrKey: ${BACKUP_ENCRYPTION_KEY}
        accessKey: ${S3_ACCESS_KEY}
        secretKey: ${S3_SECRET_KEY}
    service:
      main:
        enabled: true
        type: LoadBalancer
        annotations:
          mc-router.itzg.me/externalServerName: "monifactory.${DOMAIN_0}"
      rcon:
        enabled: true
        type: LoadBalancer
    persistence:
      data:
        volsync:
          - credentials: home-s3
            name: home-s3
            type: restic
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: 30 5 * * *
      backups:
        type: nfs
        path: ${NFS_BULK_DATA}/Backups/Minecraft/monifactory
        server: ${TRUENAS_IP}
      mods:
        enabled: true
        type: pvc
        mountPath: /mods
        targetSelectAll: true
        size: 1Gi
      downloads:
        enabled: true
        type: pvc
        mountPath: /downloads
        targetSelectAll: true
        size: 1Gi
    workload:
      main:
        podSpec:
          containers:
            main:
              imageSelector: j25Image
              env:
                OPS: Hydranoid620,b227,BlueMoon_Live
                WHITELIST: Hydranoid620,b227,BlueMoon_Live
                DIFFICULTY: peaceful
                VERSION: 1.20.1
                TYPE: AUTO_CURSEFORGE
                CF_API_KEY: ${CF_API_KEY}
                CF_SLUG: monifactory
                MAX_PLAYERS: 10
                MOTD: Monifactory!
                PVP: true
                MEMORY: "6G"
                JVM_OPTS: "-Xms6G -Xmx6G -XX:+UseCompactObjectHeaders"
                MAX_TICK_TIME: 60000
                RCON_PASSWORD: ${MC_RCON_PASSWORD}
                SEED: "2118187812067679219"
                FORCE_REDOWNLOAD: false
                VIEW_DISTANCE: 12
                SIMULATION_DISTANCE: 12
                USE_AIKAR_FLAGS: false
                USE_FLARE_FLAGS: false
                USE_MEOWICE_FLAGS: false
                USE_MEOWICE_GRAALVM_FLAGS: false
                USE_SIMD_FLAGS: false
                ALLOW_FLIGHT: true
                STOP_SERVER_ANNOUNCE_DELAY: 15
                STOP_DURATION: 40
            mcbackup:
              enabled: true
              env:
                BACKUP_INTERVAL: "4h"
                INITIAL_DELAY: "2m"
                LINK_LATEST: "false"
                PAUSE_IF_NO_PLAYERS: "true"
                PLAYERS_ONLINE_CHECK_INTERVAL: "1m"
                PRUNE_BACKUPS_DAYS: "4"
                TAR_COMPRESS_METHOD: "zstd"
    resources:
      requests:
        cpu: 100m
        memory: 6Gi
      limits:
        cpu: null
        memory: 8Gi
