apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ersatztv
  namespace: ersatztv
spec:
  interval: 2m
  timeout: 10m
  chart:
    spec:
      chart: ersatztv
      version: 9.20.4
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    global:
      stopAll: false
    credentials:
      home-s3:
        name: home-s3
        type: s3
        url: ${S3_URL}
        bucket: ersatztv
        encrKey: ${BACKUP_ENCRYPTION_KEY}
        accessKey: ${S3_ACCESS_KEY}
        secretKey: ${S3_SECRET_KEY}
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${ERSATZTV_IP}
        integrations:
          metallb:
            enabled: true
    persistence:
      config:
        volsync:
          - credentials: home-s3
            name: config
            type: restic
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: 25 6 * * *
      media:
        enabled: true
        type: nfs
        path: ${NFS_BULK_DATA}/Media
        mountPath: /media
        server: ${TRUENAS_IP}
    addons:
      codeserver:
        enabled: true
        service:
          type: LoadBalancer
        # ingress:
        #   enabled: true
        #   ingressClassName: external
        #   hosts:
        #     - host: edit-iptv.${DOMAIN_0}
        #   integrations:
        #     certManager:
        #     enabled: true
        #     certificateIssuer: le-prod
        #   nginx:
        #     enabled: true
        #     auth:
        #       type: authelia
        #       internalHost: ${AUTHELIA_INTERNAL_DNS}
        #       externalHost: ${AUTHELIA_EXTERNAL_DNS}
