apiVersion: v1
kind: Secret
metadata:
    name: testsecret2
    namespace: testing
type: Opaque
data:
    SOMEKEY: ENC[AES256_GCM,data:V5OLD4L48Y809YTjYS/lJGi6bKY=,iv:g8dgs491j7AbDPEphFtMps3ihuzvzqHKBXW2+2qhYpw=,tag:SLF6YYICgIe8Yi8m5sXsPg==,type:str]
    SOMEKEY2: ENC[AES256_GCM,data:Cm4nNasUMgQRJlN//ESN2mgt7n5UnSdA,iv:NDVAmFhmeqKcUdSYa0wItfQvxm/n42S5jSVU5gQA+LA=,tag:eFlLPLv4MtQMWL1Zl1CCsA==,type:str]
    SOMEKEY3: ENC[AES256_GCM,data:EGYn6eNGqktjuxcz32TUGD86sRTEwGGb,iv:R/hI57r+fBsLCBI6Tq0WUAUlXquU2b4iYfEG01makO0=,tag:nefhOhYIlWdWKijN3lUf3w==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsTmNuQ3pFMXFCZmFGcEZ5
            NkcySkQ0TWdUQjhsaFp2a3F5YUFsakVmV1c4CkRUZlE5L1hXbmNiSTE5OXIrY3ky
            UVZnWlhvSTIySXA2SU1BK1dzSEg1eWcKLS0tIE9hUk9SMkViYVlvQ1ZxcXVmYTZM
            QyttYlBSVFdCcEtQUHRsS3FSWXRMSFkKPzTw/JMBjXE7FfKsVvgC+lom6PGX0qCZ
            Ms152+zpE4QUeNEgBHn4Ch1eREu7JfcvpASWzxC26tmgKkl4QqiQDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-02T17:12:36Z"
    mac: ENC[AES256_GCM,data:JBllSkEOvQSxVjoS9nOcsnzKxYuoZsBNy1h4qQ/FlGhOYTbC1kSdxM2xGJ8tMH587gUGcw+2DlWyHAE+chQcrJPw9H3TU3XYTcDfWMY5wfM79wqTH9+h73StmUZGpd6ul8PDLbtP52bcwiKLyQ0j1mnFIXB06nRJNY5NjF+GJLA=,iv:vPHPV7GTCIHnwWppSsL3ICathrjg7tCtsskCL0V35i8=,tag:lwTpw5hDtk6Ss0q3q81vSw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
