apiVersion: v1
kind: Secret
metadata:
    name: testsecret2
    namespace: testing
type: Opaque
data:
    SOMEKEY: ENC[AES256_GCM,data:u7h/hJzfi3rwKeP4qstrbaxmrVs=,iv:TehB1Im+mIc2M1ILgJJuHHcmWocr8rE9pAEgttMLOTM=,tag:zNUy/KfFu9MDbUi1WPZhoQ==,type:str]
    SOMEKEY2: ENC[AES256_GCM,data:q64kRzWVPLruHpdDUKT/t9oQ3tFe85Vr,iv:QaBcgfvRqbENKbiiuynS1D2Q9bcxaW735neOrqvDLeM=,tag:rss3bQ3aGDCtZHaYj1y39w==,type:str]
    SOMEKEY3: ENC[AES256_GCM,data:9j9ilU59rub2lPP2iFIcEdf+Y4+/aBuP,iv:7Ti/YbTLdJQkX9eYWlO5vLTFdSZPviJfIrKhnJJKClY=,tag:0OwbyX9uzWhQvdHLAkGU/Q==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxUXhGNWJUOE9FK2gxV0s5
            bDNqa2sxR2ZwUXhrN0ZXZnkrVXdoZGtSZEZFCkZUWnYrOFVQQjRGb3F4Mmlta2d5
            VndBMVFYVE1CaVhoUzI0bW1PQzF4bG8KLS0tICtPK1lqWFNJZlZaZ2V1Z243RTJM
            STJ5SytvalBYMTMwRmNzZFVlcXVTeU0KB4diuRqJdSCceXSdIQVvl2OBLkP5Rf/D
            iRJ5/5rgreJcyg8YRRptVpQpCOFa9sUUeeVNwPbym+o0/Pj5sj/y+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T02:50:46Z"
    mac: ENC[AES256_GCM,data:2KzelKHFqI0lbxuZeGEs7it1K3V0WLPLbYK9S+TxOtGy5a6COTZbDduOFN1FKEfZIbX1IjOBOn2+IPKhYWL0yHDhCV/lbF/xEu4zaPTM2Njr81MPEtwvGci/KFLGMWDNVCl0YQaGwKcws1jAlh6Tq8dR0tacMfc4CQBVD9Af+l8=,iv:d8TJT3qFMhgaOMUYMS+mzr7eWJzdIaz7L4ItnTNCDx0=,tag:Z5jmYem0BYcB5g5lxOiF0g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
