apiVersion: v1
kind: Secret
metadata:
    name: testsecret2
    namespace: testing
type: Opaque
data:
    SOMEKEY: ENC[AES256_GCM,data:LwfQZOiq52JXYXlXjqGDodOKZ2U=,iv:1ogOL57tbR0R43XDQaRefGRn71AH9rDu9N5TP4QLQ4s=,tag:HJURgIX/W/p0Ss99Yk3Qew==,type:str]
    SOMEKEY2: ENC[AES256_GCM,data:rRUqJq9b/ctwvXrGbcFfrAwvoE3foI3Y,iv:Zds+7R2EBPH7lUY6BE04fEiZxgQvo3us8QGc8tZFzN0=,tag:tFMzZxcQR9jXDQB8TER3lA==,type:str]
    SOMEKEY3: ENC[AES256_GCM,data:vg+5HzlOwp/OJncO7H0Lirehplnz5TR6,iv:eSL/sOgbI6NIPBv6mIuSftGei07SM19LTHemvUD5xhw=,tag:ZagxXGm/fghSlkFT366dmQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVdS9VRXhlUVRESUUwVnFj
            RG9vMXlMb3ZNbEtLVUxXOFVibEF1WEhpWkYwCktEVURFbmJINnpwdFdySnZJdmNB
            TERWb1M0Uzc1d1VLNGlJT1R1SlRpdUEKLS0tIEYrc0VwaVdaQURoak5MZUQ0dVBN
            dDNyenRQNytQY1BDdGFwL1RROEw3czAKEC6+PYq5doQlxCDQJQLieaUGKSxdv8WH
            aID1UVu3Ktn6nEp7ccCCmn4Ji8fCCF3B6tPZOO0kgWGKZ0W9nhGFkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T06:39:49Z"
    mac: ENC[AES256_GCM,data:rLfiRs65eO7kGR0y4QPGGGIeFhQNjKCgC0ntvsnErEcoosSAPMyYcEC/tVWHAVHYEgKibKDD6F7/oYs91YMQbZEwLMOSHH2QKZ39SW8H2J4zMWeZKHUrAk72bFDPn6YalNUC5Mmjt9nfByi48wAl44SyH1+AWR64vjoxQX80M1c=,iv:dxMYawbPgQrZ06umxrC7um5vBoPnyQLDX1dbzqpFC+Q=,tag:c+RxZUlOawg75xwNvWikEA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
