apiVersion: v1
kind: Secret
metadata:
    name: testsecret2
    namespace: testing
type: Opaque
data:
    SOMEKEY: ENC[AES256_GCM,data:WYPM5A36006agzR4x7SJ6Wh0gAM=,iv:XjvY+mIFSXiGpTxYHGFjHIuKoeLk16ITSUf3X3+UwQc=,tag:6dlKW09wbw1UdCNRvV4atA==,type:str]
    SOMEKEY2: ENC[AES256_GCM,data:kPwqG27sXgMiRR6RlWF/PFmtzyvznuzr,iv:c7YI5qcAWA+6kAptdYM2eL3DHmfLFheMyJthXJfoh3M=,tag:Z/pKYeLFCsbngaVhxkgifw==,type:str]
    SOMEKEY3: ENC[AES256_GCM,data:mwntTA8kGabz0FPf2e+yviPOHpRmOE1R,iv:5OXi0uKAwOPkcrwIWqjMYVgGDMoShwTPbdaurskp1QI=,tag:KMlPnyhWqDzj2ILGqF2Uzw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUL2MvT2JESjJZYzM5SEd3
            K2dXVHhwR3JmRTdDVzhXSVZ6WmRlL3pqT0YwCmJvcUp1bUo0b1VtMnNwYzViRCt5
            UVhXNjVxR1V1UU9BTGtqeEhRRk1BYmsKLS0tIDJHekYrOHlyS1dDc0xNaitRNFBL
            b2kyV2dyQkJxWHd1aGFQOU9GWlA2T2sKjHdBHJka75Lk72LtjOcOQqS7/mgn6PNy
            B/PuNwT/hH4omThjEMo84cTlLopS4hsjnp/ElMW/9DhIcFewmc69AQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T21:25:47Z"
    mac: ENC[AES256_GCM,data:OivAGhONmcfpJ6buV0XQ0yTjeU2P+89Rzr9Lg/qPku5/un+8PN4WIDuChOm34Ov0ga+/Mmpyda6WM5KpzAoHjQYLCIuqWvdgUSwclY32ZXJ2MA9ou2xyh2dzshlixqOS4GU8fHBMFeGa7Hk2s2tXACcStMvPcF0l2L2t5qOzvaM=,iv:kXzS63hDypRhZdLYkC5QzRcGNDsJb7P1o5CEkNZoli8=,tag:GKit4rRW9t0z2KmlWjruPA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
