apiVersion: v1
kind: Secret
metadata:
    name: testsecret2
    namespace: testing
type: Opaque
data:
    SOMEKEY: ENC[AES256_GCM,data:4PLQl7tLDQsA/BU3xTzluuBCLwI=,iv:Ij+B/FbNiqA1g6VYocdoClOqrcCKUOdIs9GrsHyL7U0=,tag:rXUg2U7umHbneA+bd9uVZA==,type:str]
    SOMEKEY2: ENC[AES256_GCM,data:kV4Bq/g46RPtLzKeDjD0qxNnD6lgozZC,iv:RLsx9LyuG74gEvDGvODHZopFcfgUDpNzIf2i2N98xsU=,tag:/nTvr0Tp1zH6FSuZf1p1jQ==,type:str]
    SOMEKEY3: ENC[AES256_GCM,data:qfuI2vlP466GtNKuI7oUz8DVmZqNVGuB,iv:QLTxwUvJTEsK8261O9PTqo8vYODNxvHSXYA2DvJ3tcA=,tag:Ain+xY0ohKRETxeUtqJChg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4RWQ1bklwaDRkNlV0Vkp4
            b0tzSE1WdUdGZ240azZRK1hpUEgzVnc2Wm5rCkxZbkZkWjhKZk5UbElIcjJxUTRD
            ZEczMjhsQnNUdDRhL1AwQllwVGEvSFEKLS0tIEMrTjJwaEZ3NkJXeG4wMXdWREZ2
            Zm15TkhhRkwrbUNGTTFxamxBbkphU0UKPe5eVe431gYK6AhUg9M/XL7PiIfVt9id
            jCvNnYstvfNyKbgFp8Q2FbEnu1O5KG6MksfUbx84T8/VFDOFVatWhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T02:31:44Z"
    mac: ENC[AES256_GCM,data:PLWlVtPQ9fnfHqvSb+K+F2LanC5UCQ1Gw6zqXxdrKI4OapwGTqg3xTshZ1xC+utNz7LSABoGcBj6xOiRvF2tF96iwxo8aC4Z2rOviXDYIm4C5gFxJC9CfsAUNxElrgTF51xs3xSlB/OHOc8GYE/1raDulbAag9c93pEhJ4Ueyno=,iv:Qg/1y/RAk3NrTqv/CD/XJpuCpijupPwnV4ljRDc2Mzs=,tag:en5BeodQ0RnErX6jw0oWYw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
