apiVersion: v1
kind: Secret
metadata:
    name: testsecret2
    namespace: testing
type: Opaque
data:
    SOMEKEY: ENC[AES256_GCM,data:mnA57hnmfXgkkTQpBBVrQ7T5oa8=,iv:L2WjoVcwPzuEv2kN1NxHPQ3CaF7o3kFxiL3cof+dJdY=,tag:YhXpqGOve7UCbuATAb6Ajw==,type:str]
    SOMEKEY2: ENC[AES256_GCM,data:BbGrwQN50D9Hh+ci6oj5X0bjMhs+Huu3,iv:KvHYHIpOPlwq2f2fQ4wz+CLKMNA+dJD8qAGquhNxji8=,tag:XcYndwhxaKPUAFJ3xiS8Ag==,type:str]
    SOMEKEY3: ENC[AES256_GCM,data:vVCvZJ/aXn24K7oySXBMyHWI1/mIR0fG,iv:cL6tFhpeTWYwgKmIGrPFEQDvb5Iiep6CtI9wEo3YDgA=,tag:I2G7iBgawpc+V/M9LfdIpw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxNzRNMnpIMlI2eEE1NDRx
            T0d5bEViVUtUVkRwS3dGUzl1RG9RaHJSbncwClE5SThETkdXQnViTThDK2xkU2Zu
            UHo1U1MydDFYV1R2RHU0Q3N4bUFrUjQKLS0tIFBDbXNVTm9xZ0JLc3dLcWx1MVFS
            VDRkOU85SUZHQkh1ZDA0cy9DZ2hIeW8KyZIKDZiKHbYp+sHea/FfIVBDb6G5ySLK
            DfhcFXqM60akRxV88/RrLuJ3wSPSh36hvAcmmi/IlLhopRWzejpO9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T17:08:20Z"
    mac: ENC[AES256_GCM,data:MUWfZLY8TXYuiMtENAyshxN3UnTqaWUEyzALNSyqNe8RNYrM3pLgzEGAAv11U4ZuOHY9UiZm0Yg1ieae4Df6tCKZtdItlmbjDdhjW1EWbASVp0NIefe2oqpAi9YZAcYxyJlMqhvkrwz6+2rEeoncHHtd9a78FEpK0NEChidi1YE=,iv:PtTMnUwJd36oO0i1iDZZbP7pnf4gGv64aA5fSz9DLr0=,tag:wyjjCOg6z8oFWrUTSLaXCQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
