apiVersion: v1
kind: Secret
metadata:
    name: testsecret2
    namespace: testing
type: Opaque
data:
    SOMEKEY: ENC[AES256_GCM,data:wwpH5GPhGLgx9wUb05itsodGc54=,iv:T3HwL8APyL076IkNZe3MMeqkXrAP4rHC4NKBB777vIQ=,tag:BwNO08wWbMmZ4fzl9bbBig==,type:str]
    SOMEKEY2: ENC[AES256_GCM,data:khmM3jbnR2Q0BZAoWWZYbhdTqxtOUele,iv:r2q5knw5Xya/TIPNX4+ycfMe7tIgVXbdU6ZEcnkGIBo=,tag:uXBovM4qkajAsOA/wgqhnQ==,type:str]
    SOMEKEY3: ENC[AES256_GCM,data:Ymmtk+1Uk1ULUUBdC/LhwnODUkrqhHfN,iv:CMY6tYZl1+9RaazrdKDoSwZRoCwhXptq8Eeq3VmX2Ug=,tag:+sr4Ej3yiQRt4Fe1kFhcHQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvSUJkZTFnbGR2cG1acVdV
            bE5JdVhjeld2enhPTGtFU001TmNuaWtQdFFNCnpBaFQxdTJvVDE2RFMrYVJBU1lY
            NzI3TmthTDNtMmhURTNlNWFUS2d3Sk0KLS0tIEI0cW9nNEtYUG5sOUhuNTVjMk85
            Tk9SMFVTS0JLMS9aZzd0SlRQQUtkU00Kyw8JXTMxBVuzP95KcvvXB8jYr9T4dQz2
            wglezXGvkXVj+W4AsZjPGec0HfF4mqyRglLDocIeUTFR6J6HAoK6SA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-28T14:28:39Z"
    mac: ENC[AES256_GCM,data:gZlrdr8rQK2lEMPTfr4ckJc+mIBilaCn8G5Zhu0EayZSgoxLeXPmfWg6VxWOyjfRH031GwNDOTGRqqgIqW/OjOUu2QBoswE7NcmH/v9QgYR3wYJ9sayIBu2wU/Gfpg7F1S/9c1f0bh5gu5UBKe8LACM0SbewSS7ECx0mrZY7nt8=,iv:4GhIaSYepwv3lNzwnLVnlhYC62KutmhW8D1Z8eXoP4w=,tag:lI6aCGWEyQjliFGFXiHoUQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
