apiVersion: v1
kind: Secret
metadata:
    name: testsecret2
    namespace: testing
type: Opaque
data:
    SOMEKEY: ENC[AES256_GCM,data:O8CRBZeSltmZvE0PChu84GXVytg=,iv:ReD0xo66iv9bXuVqVRjYTaYL0j1RFfDiiC2mRbyjek4=,tag:sN7te5dlIlr7o6trfaiaXw==,type:str]
    SOMEKEY2: ENC[AES256_GCM,data:zxSwnOjwuCl3R8WCOqQiyyAmWl8sxTsj,iv:VIZwt8w9bZ7hHxpYSzI+XqyiNHHSsTy+xVunbs11UE8=,tag:YFeYeUYyjDJA8yaKjxw2IQ==,type:str]
    SOMEKEY3: ENC[AES256_GCM,data:oMin2Aho9toC2xnxcQ0uyTQsPTPv8APt,iv:b5xDZb0G6BDtuMtmYqYvVUuSKKNfsyEnYU0xeH0q4B8=,tag:6ck1uOo6OdN9TjDmzEI9pQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMazBLOG1yaHF3R0h6ak9s
            bDRIb2kvUVNRdTRDOXNaZWMrUzdTT3ExNFQ4ClA1MTg4TkJyekxiUVNjS1NsNlBT
            Zk93RDJ2R2lObHpyNmRDdkV2dHYxMzgKLS0tIGtjd2xvM3FIdld3dnVZd0J0K2Jk
            WHZvQnFVNVJ1NW9SNTEwcHZMU0tZSFEKPqqBnBIigtR9m6Xq6T2Sut5YBt3sbDX1
            buEhWtkzbNXbmN97Fmo8O+Nzrt0YeYGLLmNgokGIymgYkfljm2LB3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T20:01:30Z"
    mac: ENC[AES256_GCM,data:os8wJVKuzuY8PloN6enmUIY+9UKoUQ2X9gaoBhZEu1KUtwrACR9nT62+kttJBHyXX5s2xDeb5p+Beai7p+bNpROXmVmpKtD/2G7qNojXMWL3wlwBONdmkFW/5Pj/fWQhZXzdViVcDVINgySEb3op3yzahj9JEKigNhKNfHGV6Do=,iv:+tQtTmBW/rwoliAma6Qmp82xuczjmUUmVJ9iq5l+7GY=,tag:RN4q3FkL+rsH/Z1cUBVvzg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
