apiVersion: v1
kind: Secret
metadata:
    name: testsecret2
    namespace: testing
type: Opaque
data:
    SOMEKEY: ENC[AES256_GCM,data:S+tlckswzcO3xCY5CrQ8xqqUsso=,iv:79SZEsdXV+6QbTGMipd7nXHhnaqQlWCspfBIp1Op6cI=,tag:hNk8uo6pXfqp/c1Q6rxh/A==,type:str]
    SOMEKEY2: ENC[AES256_GCM,data:CaUXnbBE2K9pjI7SyjtwlVs2q9PNdpl9,iv:Yq/kpPWTnSD0o9SqD7B3yhaj5GGyCs8PnK1aVwzSJgU=,tag:1G9yQxNf8cWS+6/EZi9Wyg==,type:str]
    SOMEKEY3: ENC[AES256_GCM,data:lW86jL5OMbLD6Un7lHnKcaNV6hTJOVCb,iv:/v68cQ3FrbSP/JpIzu2IQCMJpVMNvyfTKyN9agxhFJk=,tag:VODUNye8pTHuR/+wTDIf/w==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRUXI5ZWJtNTRsYk1EMlpN
            MURlUXRrTzErS3A0SVg1dnFJRGtEVFlmZVRRCjNNUWdJcFhzd2JRTUFVelZLU01G
            dVBrK092bEUzUUo3NXlZUTlhc3p6dDQKLS0tIERhSnBra094WDF6Z2FTamN2ajVr
            dm8xSVhqa1JSZEhlSnRQV1dvZ3R0MDgKj2HwJ+etJ2j5fPHXRDhLXRIfqTNx63mM
            /lnD3QAhyOhnLB6nYePnBPfzEZkto4UtsA3iB8vjySQRfN1Z9rG13Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T03:45:56Z"
    mac: ENC[AES256_GCM,data:fvmodovZbn+4jui2aTt1IysAGCy8JadurJP5s/1aSZ6A8BaK8jiMhhYv+/LW1S5/hMil277FeNHUtxXgI6eugNSGhWQUZOYlbZp1ydmLU7gCGSCsCz3ghewfx4p0aa0x24zTJ7qpy/iW7qUml+VIzkq+Dsctv+cBTqGH38MB1Dk=,iv:DePSvVHBMosUHvRQydSmpgHLcq3seTX1VR/ck7k6vwU=,tag:/7co7BDlF/hZstDaq1yMtg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
