apiVersion: v1
kind: Secret
metadata:
    name: testsecret2
    namespace: testing
type: Opaque
data:
    SOMEKEY: ENC[AES256_GCM,data:9lmVI8zh306+MjRYl511Shv2Asc=,iv:fcbZsjNt/8eddSVUrtznj64Vr9hTOHqsPbuuBjIwsRQ=,tag:756LlSK9uGAzAhG8rReEYg==,type:str]
    SOMEKEY2: ENC[AES256_GCM,data:jqkieAgkbjHCEdob09XMD1YslXmO0hhw,iv:PTReZkbE/WnrwL3KfmIUFeYk+4sbKpCahh1w+S7g6aM=,tag:yeuOzNJAkywInriRdYgknA==,type:str]
    SOMEKEY3: ENC[AES256_GCM,data:3nlalg/a5jGRPPGzfhQHnEiZ2Owncvf2,iv:iRQ8gA92Tjnoi0wUu+dI9JJ5QQlmOw1HOzs1JWhRImc=,tag:glc/inVOJ9eZx4o82PbzEw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkOHlwWmlkM0hPQ2lqUko4
            Z2lDMnB6aUNqM29wNnhYYTdpcUM2VGtHcEUwClJoZXR1ZnZVUE1qZ2ZqYmFJMVBj
            MExvNVgrYW12VHllNUZ3bnAvYU0vZDAKLS0tIHk1MzBEOFVVK1ZXQzAxNGlDNS9Q
            MzdRbEl1d0hodk5ITzU1aDNHSUdVbjgKSkXSbdbIF0y0bdQKT7hbrQaYbdTrVBfU
            YflTYESpAsalOB+dYzMHlzJs+U8S+strUmmV+v6QS9aWNGyFgZVdRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-28T13:55:22Z"
    mac: ENC[AES256_GCM,data:+tcTlLJWWqmGhSxZ+Nb2g5WxCoaROm71bWZcBn8qvMmb6KXjiSC23t641POCrSiIPgV3B7EU9xe2RzddWoBs6+XlkGge3YSwdnIUm3V+hN8BdPiIRxT0mbC5Pncpg8Ok7OOtdNb8S+KwJZnIC7pR9xW8v4e3dajaPR/P8dYtHyo=,iv:6hWvt2vkwWZgXxo+MI3/R4ZP5Cc1rWSj5It9ySSxHzo=,tag:ZdNAdRQoYDDxnzAWLfy5Gg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
