apiVersion: v1
kind: Secret
metadata:
    name: testsecret2
    namespace: testing
type: Opaque
data:
    SOMEKEY: ENC[AES256_GCM,data:SyvXrzc39idsF9vMqDmbJvmqYiY=,iv:mKdFDDAQEVBf4OK3iwUYCC9AibtDVu2RoYllfY2Qxug=,tag:b3exQBrRsmT6Hm4J9Sdwlw==,type:str]
    SOMEKEY2: ENC[AES256_GCM,data:1UhosQ8oL1RIegpRjZEVBKooGq08BXni,iv:fa9OHJK8bVz9RKWauCvkJAXH0FpYgMkVW3Onnjp/+y0=,tag:pJZO8ScAQXVcOpb0ipVWtA==,type:str]
    SOMEKEY3: ENC[AES256_GCM,data:iJJQCtA3bZm6Gn7fTMJTyj52Xcdb6xW+,iv:ETP06QnjcrB7y8DxFMu31xJrSF0KALAeTWGBb/uWbfg=,tag:29PYzmlEtGWLYayYz47HKQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAycTBuWDBGQWRnVXFHSVZM
            Slg1NzhCUElZS2tLZGs2eENrdFVEUWZKeXcwCnBDeUVDVjd4Q2NDVFYwSTFiTFIz
            RFk0MG5YQXNIcGowanVMNHovTXE4OVEKLS0tIG1tbGsvdEFjM2xRTEpERVFJOWdt
            MDVYeWFzRXFoaEs0NllST2RiQUtONFUK1avhE55v5U1i6lkPmCj0dpzd0b4wb4uO
            1iOVYK7VkNlAIt98XeXWbBsxeNVa+jTy+mYiy5Ws7L2fCmfB6Xuk3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T02:22:06Z"
    mac: ENC[AES256_GCM,data:PNNWw0RTIAkv7yKvyn67WkERTmzjgy1ELgrf0HyPJhwVur0Bt8yPoFL7+vceTfBRQRgAyemkgS2h4i2lrChbDcR2hc7MrLLZWiDvczpIXAd35uhg/y+sJwRNv+tRtLrHO/hZGJ/2ZgNR0XKMSyetN2S56bpzTlFbCTAgckw5Wl8=,iv:E4EmFjJHYAi1YeErX8IARXgjBSf8uoj6RDAHuY4HoLI=,tag:wR8Um5bKmmdD+KWFK2jzCw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
