apiVersion: v1
kind: Secret
metadata:
    name: testsecret2
    namespace: testing
type: Opaque
data:
    SOMEKEY: ENC[AES256_GCM,data:aigCoZnfmO0LHOy+40yfJMCTBsA=,iv:qZ+c3qQ6mlytnYnTcgBtilshugwpvLocZPbslsV/sEw=,tag:g1JhfYaUU8DXEbJQZsiCaA==,type:str]
    SOMEKEY2: ENC[AES256_GCM,data:CeQR8WUJhpf7Nu526teR0C97CJmFZFxI,iv:77Rnlunu53oFGPzabTcVOQ4Y+GUCbz2QQVQ2xoU93SA=,tag:i1DhkKvUvIEwOyc9GkUCmw==,type:str]
    SOMEKEY3: ENC[AES256_GCM,data:isr+3ffCEsF/D07vMnENkH6bbTtXb6fP,iv:O9YJdwfLcngUKBLLnas5r690vViaJ5mViAS7xKq7VqU=,tag:hk1SW+xD/PMe40+HXUfmQw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGb3hhSEo1NG4yMGs4bUhw
            QnA2bTNHR2VvSWNlOXVmNUZZRDFXdnJrWVZJCjNyd2xrclA1RFNzazR2dFhOcnhL
            aXprZGYwYVFMaE9ydnUybXRTd0kvdG8KLS0tIDlaTmZJRWZSbWVNSGVwYU8vcU9a
            U2s5VGk4TUpwRWlvRFVMeG90RGZzUjQKX2suxXt+Ueh4sFmGW6vy5RN5atmaxfJb
            MhzxEfE4Ge1tlwfhW0jdtEFA4jXCTojeAE9kwONj5SSojWZEUHEpXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T06:17:40Z"
    mac: ENC[AES256_GCM,data:beGsJXGj3wP5RMmFGJORRj3U67z1k5BkAbRtH5pDuiMu4JxoOGSa4vLOyh9+71JsV8eQBVEIfdJSxpdoWud2kBQ+ji6x/3DdFpmA6YnWD0G5PYY2MM/8myszgLhbnE+1ngB7tcbayMF2shBIsC6eppj/i8Pg8W+AA+grewpFeNM=,iv:q04GShtVXuLks6/Wuup7Em5tf1WxbW1nhoqNf8/WfiU=,tag:i6c3/+9OwyzesRDCPRetMg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
