apiVersion: v1
kind: Secret
metadata:
    name: testsecret2
    namespace: testing
type: Opaque
data:
    SOMEKEY: ENC[AES256_GCM,data:wmMMzjJUxVmttFFUiFXvfz15RY8=,iv:JqW35wygoll07FfJPGBiwKt07oxqJ0poB6i4Ocborys=,tag:JpSyelOCckOLSrreJPXK3g==,type:str]
    SOMEKEY2: ENC[AES256_GCM,data:Sqy26doFOCnQFZsVBr0FOYsPzFlUJ3Mu,iv:1ckdBwhM+Mdvuz3kM5PRWJpb4Y3FVBI6/sldBRSMt5U=,tag:n95X0mjlMKAS9baoDvrQgw==,type:str]
    SOMEKEY3: ENC[AES256_GCM,data:8DjE5jgG9xmB/dXdgBsUl7dOdK+5W8R7,iv:xpPcX82uMLC8lbveSW3bNQTHLq2t8Im7zw0cxnKzCGM=,tag:XGSh8sP6Y7fYzqqGB/tbOQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvV3ozdEVsTUZEN0JHR1Bp
            Mm1oVGt0ZXdwR1VyNkpXd2NzZjV3R0txQ0RrCldSQmp6YThvNmdqZWFRK2kzZ3Nj
            MmJQN3lXczZPVFNPb3ovSHdydWNPWG8KLS0tIHF0eWpoVWhqSWFPZ1BWb0t3ZmNN
            M0FtUlRVZ3VXeDV6Tkh1U3hybVRFcmsKGbk2ElHJ0AURf8gZTpSrjPeYJzlhSLRp
            sM+Cvf17xqUJ9rdlxbw+GvyIK08xze0UU1C58R5eR785AWCeEvFTAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T21:48:45Z"
    mac: ENC[AES256_GCM,data:SB9d8G5CbEjiAzBKE88/2uR/cQe9D7649Apj4OYAd/SU9FXdaMbXUD0ac6PbE8beHkc1SRZtBithiuyj89OeRM/gx5j3fmHg1ii2uIcEdj9N1eIsjPDj7AR0OXxv4oMWGH2NFQMPaP+78fnqPW3XfAOzfho+A3iy4vZblh4mS/s=,iv:wXDSdKTnV4SfAiAi6RmkDvlsHM+twirUg8Z7Dh8Jk4Q=,tag:hC5u9ji45lyTc/O4PgFZxw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
