apiVersion: v1
kind: Secret
metadata:
    name: testsecret2
    namespace: testing
type: Opaque
data:
    SOMEKEY: ENC[AES256_GCM,data:BeejGyKjO36QlVc9AL+4Jn3lbx0=,iv:kJNW6+p4GdKsnoMdNJ0uKwpOK22G+yBM3mrd+o562BI=,tag:GeHF900NFjQCsZgP0VLk4g==,type:str]
    SOMEKEY2: ENC[AES256_GCM,data:ucioQLWfZ7E7gka1tjy44Ek2THjvpwMZ,iv:ln6ZPzH1gSEaeQzsuO/3dbk/IimTqqzpeYJZh71HfzQ=,tag:1hLsz23Feohi6gHoDDhzuQ==,type:str]
    SOMEKEY3: ENC[AES256_GCM,data:4Xi/x6oSdtpKnD0OHgBFv7eOvDbCJdBh,iv:vKqXAlKGMBigzgdWCeZ7whIl3yX97OOm/DLRh2cpH0s=,tag:dRf/Oo1kr77ZIb45Rmku8Q==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIM25tMnZMbFg2a2NZVVVL
            UzlhMzJ1ZmxQTnlNR09udzJyNG5Fd2s0cEdnClE1eGVjZFdVVVNwR0tHTmFDSHBm
            R2JBTG5mWVFWQUZDeFRXMFlza0tveGsKLS0tIHl6cjRwRkNvcWg0QlJlQ1JyYlBC
            MVp3cythenNFbjVsaGhoamg0NWp1VVUKN0F2jfhQ4P6OO9HXqs5gQAuH8QNvzgb+
            RNU36gnj9v8gjd+NnZZj/SEJ9Yq0wKvL714ws4J9B0wP0GhdSuhPzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T06:30:17Z"
    mac: ENC[AES256_GCM,data:7FZSrnBQ7negIv4DoMxgYNT9rWATA7YDWE9t8iPj3tDPm1nNUosC1HieesK+ttkLs+Hez2vOKqJ7OPZRs+cLBNH7Sxqv5qxASJU+Fe4Rjm7CXAT5DQh85VZcBq8U8/Lsm8vQuLi8i4QWrAf0Znj7giR1OXr6BgLunK/CuO6Jt0A=,iv:cDqfe2z/ZndrwdfcOFTI067gj2+GwBbDn/uFj8yEwNI=,tag:iEy3c982TkcCvRGH1xC5Zg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
