apiVersion: v1
kind: Secret
metadata:
    name: testsecret2
    namespace: testing
type: Opaque
data:
    SOMEKEY: ENC[AES256_GCM,data:NsufBGWCPhkbd2A5cb9aK2pc0Zc=,iv:qoKEL/pyiq+qOdXmpASGe0Hsw/39RyyammXZtgXsV30=,tag:TVWTn0nTJT+QbrAj/xgdVA==,type:str]
    SOMEKEY2: ENC[AES256_GCM,data:GH1F420vtF/CEQc+8ZyDGLLhJifMsH0E,iv:MFH60330MgZVt5ri/XNbvi7GemtfOSJXlGy647pGemg=,tag:xK/oq1F0xV3kHcjDaOsE+w==,type:str]
    SOMEKEY3: ENC[AES256_GCM,data:V0Y6aCo44M1mQstU5bE6URbP08ESI4AS,iv:e2mZU3pU4pHK/dM+bGVdqyLXdTPVK6pSIJa0ajJZZQ4=,tag:+QUf0l8OQFyoVbON5Cq61A==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRWWV3c2JUUFhJMklldmJv
            NU5paWtLTXR5ZEQxSlMyMFdHT0MxWHFpTFJBClZFenFWM0dXTkVnbHhnVGVuNTFH
            a2daeTh2SGNva1NnUUY2VEJCVHNXa2sKLS0tIGxUOXE1K3hzQ0RQVjVMamlWQmVl
            TURScjNtSGtaTkNwZmI1SUNoUm15a1EKlghjw44bE5jwC3tdG1nWKNF3sT0/+1WO
            yaIoQV7ozT2NtoAtuPWLGSCs1CS60GFuUaUp4PDF6mpuOI4so88NJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-02T20:23:16Z"
    mac: ENC[AES256_GCM,data:n6KSvIudmrrqwO3rSUiYrrgnEaSwOsV62kwNQadg7m7zqF9ch3aGKTwMKLhwvRinA21VnhNAbqLq+8D/pXVkfUfTq93AQpy7bLLQlnCxKlYQSx5jZlxgJtaKCHvRPwEA+w6KDGB3JIgjQwpXghfwyBYyBTZ3Ym9UojhVkqfDZ8s=,iv:sw4BpfmO0JPBheRkR4m1Y/Oy7Zz9/0WZ/eg3c7O1LaE=,tag:d3H9MSinEebuak5C7RNvdg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
