apiVersion: v1
kind: Secret
metadata:
    name: testsecret2
    namespace: testing
type: Opaque
data:
    SOMEKEY: ENC[AES256_GCM,data:Q/2bb6MX5KOgPEEQrdqiYKhvEQ0=,iv:1hVYylvumtHcn+uiyGG6xrhDOhYaIfDiLC50GsHkowY=,tag:Pm36l59kW6WWnPT0gET3QQ==,type:str]
    SOMEKEY2: ENC[AES256_GCM,data:iyKsVz9YykVwtYb43Y5b+8ukqR6TIdpl,iv:LqLAZ8sBNqtJzYGYuFkuC6jI5BSActA9TmGJbwoOJ+A=,tag:MY7QR49D8hd+AtDcQcMEkA==,type:str]
    SOMEKEY3: ENC[AES256_GCM,data:KAtXISla4UNmzu5O0qQNA39kbZ72uVTs,iv:tM+zcwc/n2I9WgrOxPt4oisjmZr4VQmkJcuKj0aOrIc=,tag:y4FBU1SiYW+LfzO5A23fMA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3RDJoaEVYL1JmZDdMTnFz
            U0hSaEw5Qk5LR2ZVeXFhN2ZYWDA1cVRtbDFFCnpTb21mbzRhUE4yNjcwNUd6My9w
            dzRGZ1I5bHAxQS9DV1Jpd3kvbGdNdjQKLS0tIFFoQ04wQTVyWDNQWVVoSkhYNGdN
            UW5OSFZnSEYwUlJFLzFjT21seUlncEUKcH+8jueivcb5es/w2B28opbhlpBZGl9b
            BFfzVUVQGZwPm9tfrX8YxXxc3p7CtnltNHKZVwVREr78NGp9LJ+Fmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-02T17:43:21Z"
    mac: ENC[AES256_GCM,data:bMheLL1qST0VuD80FlBg/aBrSCCZEDCnCM4G3t+Nd8U1cC4KxYtyUlPCF+/u/XhMIvXzVQwHWIaBW1Z56mwBFj8NJSwMZbWTxpO9Lfi+uN4b469iZHcPocF4Ow9KOcs9gQLr9ZTtaCyrgwYKvDE9YLCxntpNCUuic3O1xtM6o0I=,iv:awkrIa2hqbBlr85Lqp9ZahzbCnh+DfpXeJla1zXiSvs=,tag:+iT+JQdsoAJjRWn5zvMLBw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
