apiVersion: v1
kind: Secret
metadata:
    name: testsecret2
    namespace: testing
type: Opaque
data:
    SOMEKEY: ENC[AES256_GCM,data:nEj+OWtq6lhArlrWAoIhlQr0Xvg=,iv:7u2geMKD+vP6GZm/yNhc6R2gF6hLWUtPeQ06DCcOad8=,tag:xrWYrmQh5GTmvzbmAZZQPQ==,type:str]
    SOMEKEY2: ENC[AES256_GCM,data:YVVdla1pjRBETOEw00FKrjnqI9yRplDI,iv:wFWPaGHpFj+AgfLkRa/k+bbneAWMkL44g24Rf29e08k=,tag:v8TAO8fUMkwnxPHyXB1Tzw==,type:str]
    SOMEKEY3: ENC[AES256_GCM,data:wU7SMgKPYamORhLycmqcjufeRUzETwqm,iv:f5zLOEDY6+XIEZOKwuv/Vbhz2KXuNo+caEl+KG6Cs54=,tag:+ue1nUGJ14nhpQx3aaXafg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0eDhsZXJJOWZFQjZtUmky
            N1pKR1NaWDQzR3YwbzBVNG1VMVpoODJEOEdjCkxkQkNaTUVJV3Qwam5TUGdGUFZP
            emRQdWFBLzAzaWZWRXl3QlI1K3ZnT0kKLS0tIEllSzEzcUZQc0pBMW9oUmFUTit3
            SXpnRWk5ak1VMHBZS1ByRjg1OVMydjQKngQoWvan+thc80z2OSfb/s8icm7IMlbq
            7oRMqi7Fouo76LVJ8Xlt6D+4tQX9y8n2z0RPW1kFU1q+r/RjFbfI0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T21:44:33Z"
    mac: ENC[AES256_GCM,data:MDH5Qu4y7vjwxzN1H/ZYOnFtst8XbWcH5akK5K1yNHPGgX9VMszsis4t4i8tv0Z71gl9bqnyCzdAKh8JPXHZDRnp3mYhwtdiSWs4EIzYCd0YvKQBiSfUgas8IK9IFhZwXhtHnDrcyjG/9I4mov3oDPJoOYoGPdMGpBjyf8Kws2E=,iv:5Yp3GnAQDMM0NRAU+ia4UPJ5Qhe+sIL/Q9MTHvN3Kww=,tag:TCjsKm2kV8q+4fSW0VHiKw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
