apiVersion: v1
kind: Secret
metadata:
    name: testsecret2
    namespace: testing
type: Opaque
data:
    SOMEKEY: ENC[AES256_GCM,data:r8Fd2PL/zSmfi6Y9j8GN2+jMG0E=,iv:l3sCcc5XG6hNcgxjOGrtQv1lvi0w2bqTqq5cXaWVPIA=,tag:XGXiGgYNPAZcEkzoPB7RvQ==,type:str]
    SOMEKEY2: ENC[AES256_GCM,data:vXupA+FJJw8M3bU3wvmZ8rflFA9mWL4y,iv:Sy5DG545DuByu0fC3YJTOREmWme/HhQy4s5a1qcJ2vs=,tag:ru0ui489Oy9BHkDiETIq2w==,type:str]
    SOMEKEY3: ENC[AES256_GCM,data:2o4SvNTVk4W7rn4OyyZ7NIzKYK9WVzEk,iv:HWNWODDbHmB+nEnmqU1fCVn3iaqDuyjf8qIpCVteWlM=,tag:x39y++yMPkuhOx+jWdykQg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuU2ZzblNXSHJFaGlFd05x
            YVBLV1NMUXVjdGgwTVRzVXgyR0tNbWZMN3k4CksyS2NoV2JMRDVoVGVIZkJjRXk4
            allMbm9jMkE0VDRmVFdPS1Y2b2lXb3cKLS0tIExqTWlMUzhrY1VLTHVlU0dsZVdl
            OVErWW5hZTliOUlZZTBNNndvdzVydUkKZVYc/ZPYsTIeXROtvSaG7on4x5VHDkBH
            Nuc5GYAGtFM/yZ00I3QJp/oDjV4JugAvlvvHUUdlWO5PbnhetTHVMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T00:51:29Z"
    mac: ENC[AES256_GCM,data:cpRC1aiVdw/tleadpdZC3GHaf5aNu8cm6Rj/ylYPBlosKiAM6FWdxyc+R6QlhCGJlk3kyTS2TXgTTfJNdSKKYHtnsF7nBnC4ottBP92MOF6BeG2ZAnKv3jHNAHiHkOQAB/InIXuc/JAbzJBsZBrsne2ABn1aFHrxyLwFkSoDpfs=,iv:2WgiPYchj81yJSzW29APPbnHFvsHboMEZvuQvcXTgRY=,tag:6AuIYKo3jTkK9TK++tDQCg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
