apiVersion: v1
kind: Secret
metadata:
    name: testsecret2
    namespace: testing
type: Opaque
data:
    SOMEKEY: ENC[AES256_GCM,data:Mo8mDWBYmGogBpR1ZlhyGhSJI4g=,iv:0qOPAbHbVIJv+9Rz7f/rtkd+BJRSTTK41JnSsJNDa5c=,tag:5iTZlPSygqXTkJdmmk5O4g==,type:str]
    SOMEKEY2: ENC[AES256_GCM,data:HMJ1sR8sGE72Qi/9byZk0vKfnLBzkCho,iv:eplZWDNaHYOdSMrjCnnnw+7O12LMMFQcWH/6Zet1mb8=,tag:Bmfc5DgyQ1m4AZx7X+49yw==,type:str]
    SOMEKEY3: ENC[AES256_GCM,data:e85pZSqmnKvjR4XrH8Lw9PVrIJf+fUdz,iv:alvIRbXjygpMWbVVBlqjf+izDD2rCQaLQS7NIT5gnqY=,tag:yt/GI9GyT6r3dcYpAq6vYA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ZDNOaTJCek5rSk9vMmhN
            d3lDQVZIOStzNHAvMW5IaWwzdXJQNWJ4VzFFCnJ0bnd4OE1vN2lHRGtJcjJaMEcz
            elYwS1p6VFlEVGl2STVHQTRORTBwV00KLS0tIFB0M1ljbXNOdWZBUVlLSGRwMFYr
            Q0Njdnp5SzdTc1k0Yy9nZTc0S3VOK0EK8I9ZnIurTF//OQOW8o+lOZzjlwRzUjLm
            Ue5KZSf4XFLXu9zzTiaEa5oPxsAfWdjiZVwGwUWv/OKvNGZOystdmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T03:10:12Z"
    mac: ENC[AES256_GCM,data:SjkUhXDGlzOdpYv/dojkUZG61L/dyDQqDdjq9ag6puta1iabxYj+nk763crmMdyVblXh29WZEWokGEo/P4TPfrwbmZf9ujc38l8W2bXV9Ro6JVHGyhlzn/JhzGyQ0BM1/ieY3dxnhuy+DV0Nl1kCUJ0Na2/2WUE7MZXFCAlJJ/A=,iv:ubIxcQflrcdGPSvDgGxXbAKtSjx2wODRRfs3Jgmz5bA=,tag:fiOwHJeMU+hfYGOUqBAsrQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
