apiVersion: v1
kind: Secret
metadata:
    name: testsecret2
    namespace: testing
type: Opaque
data:
    SOMEKEY: ENC[AES256_GCM,data:zdi5KHQCJ9djvYcIF1lQbY1T2fA=,iv:iV2VRyUV6sNSzr/2fdZbGDiN2hC8X8i8AOfqsCD9Nt4=,tag:gx8GguOO3HQM6PRyYlwG9w==,type:str]
    SOMEKEY2: ENC[AES256_GCM,data:CftafPpUXPLLgnSnZuootf76u9PdaX1i,iv:FnW2Ycwzy7NoPEuC9Y5ju3TkTwpfw1jrBWmffVGfYVY=,tag:HP42IXetusGjD1GzBOmUvg==,type:str]
    SOMEKEY3: ENC[AES256_GCM,data:vzHVSeMMBIvv/jhdf1HwsUGHHDA7z787,iv:hpJCbnFQh4wmay96ruCdM4Oy/0I8WqX99a5yB4QtYSM=,tag:vxpPOsyGV508lUFtaFHkRw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3WWNpZDl0NmtSM0Erb0Nq
            eGljTHpIYlR3N04xRVo1Njc3NXNnRUx3a3hNCmpGQmRXbk5pYjZCYis5cUZsMnBY
            V3VoQjRzekExRENaNXJ2WXJEZmlLczQKLS0tIDUySGJLNkVFZEc3M2EyZEFRblJm
            MGU0V2hkNjBLVWZqb09CZ3ZpSjk4VmsKlSPJV8lfJWeUC1Es0ITo68mdLnPT4ghs
            8wkri41uKxx+AFfEj1jo9mTQoTFlWxNRd+ehOtQLY6NYxOIxplhrvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T03:38:05Z"
    mac: ENC[AES256_GCM,data:CrxwV1Z/N2rAbgNbDzB7zeFriEadwa3ki1LLT1RL+p7QF/HMhFFxxXAfSR0BP8W33jrwb7SXpygQ2pZRbTr1cTz1xe0nAD18c/dQXg/ZZQkR4zptiKDgTO2Ffi86b8Yf4y8ZO37utMw5yc34grHixP0XAitB8oKaGU3Nek9tfio=,iv:NkQssW6/vNjhnCbKhEulTf6RPGBRRZfoyD6dldg49Ng=,tag:2jOgU+xAKO/qCKdalc6Lpg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
