apiVersion: v1
kind: Secret
metadata:
    name: testsecret2
    namespace: testing
type: Opaque
data:
    SOMEKEY: ENC[AES256_GCM,data:vjFnSdcRCtSInELHVzP91Lwr+S8=,iv:NHia+QGHWmpSeVpvKhrCiAFbYZyYqo44cXpB8FfdUTc=,tag:uj+s3Oy0oF3VCEXcFwDHlw==,type:str]
    SOMEKEY2: ENC[AES256_GCM,data:N86REZsqCJ7RwjfIhlANyWi4nk6NavIc,iv:e9Nmyyvwcnzm0CIasRM2tNdLRaq0WWYPRsPRxSyI+rQ=,tag:BGv8eBi+1KYZCSHTRaKAJA==,type:str]
    SOMEKEY3: ENC[AES256_GCM,data:N+SEFMcIWyjF5m+zYPJYLWKe1mOG6usQ,iv:sejRhYzP1RnSAi45ZCJFj3NHxwLNzrdOqy7SEz7AAEE=,tag:Wo88cB1y3AFaMChrICay6A==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0SVZuV3FVUXpHbWpLRkNk
            ajBzWGcrSXI4ZnZ4S2NkRlE1NXVCRHlrcHkwCkxySC9rRERGQ1BCWkRadEZEM1Ro
            RjJjUmlCOEkxNnJEVGdtbzAzQXpCTEEKLS0tIEpLRmc1OTlqbGdyOUxwRHRhVjFa
            eDYzTmhuTGRKRG9HLytMSWxXV2x6ME0K+VjLEWlteYxKouz3F36QixPPNwdrJiMD
            Ke4I2bf9aYmqsG3rT/I5n0x3ucG4gaBouyM0UMIVsa38ur5g7fsP5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T18:57:52Z"
    mac: ENC[AES256_GCM,data:s07dxgQb4D00AiSK3pZfrz9sqekESzWJxttnvKXpcfMdEPAdw+LpmFAMtmBVe0NG9FMnK416BYkuHQYQFeLPg9u8RqG81dzesd3vOWi2TE3K5QNwAodMDzdpaha/nE7UNq2YQ42vTO6GwCECxKaof5tj5cpdWaPsktKSUIofhGs=,iv:0Rn1HV2v2L4u0h8pXRRZgKhi6YlJoskKTpjXU7x6f6w=,tag:eyIAJ3TjWvsY58i5ZgEPoQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
