apiVersion: v1
kind: Secret
metadata:
    name: testsecret2
    namespace: testing
type: Opaque
data:
    SOMEKEY: ENC[AES256_GCM,data:nITMduVOnRaiwA11Dp5KOs8tz5I=,iv:hoV2/sR/dpfOwabMLWvkvLRQyz+XZSq0xHo8zRHjE+k=,tag:fzPIyxZ45TnwrL/c6Sarqg==,type:str]
    SOMEKEY2: ENC[AES256_GCM,data:36K01Vf1oNiEDLKDMLW2UqO20UVL4I1i,iv:thEb4xTs1uommYDtmL2vekwF4NU4SD+Qq+Ed6xIHCSQ=,tag:nHZkIzJZdjlPlen3unn1Sw==,type:str]
    SOMEKEY3: ENC[AES256_GCM,data:hit5uGERzhbbdYK3DJO7CRMqLrpIlIGA,iv:jJo7okAWQ44L0na4JcUaQvzC/kf6nj0IoyDYr91yuFM=,tag:78UR6L2gQh9x95dCFkVHCw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsY1NSUWxRekt2UFlSZXY0
            TVhiVXQ0YnY4dXpzY3E2MnNZbS9XUGM3ODFJCjVWMG5vRWI2WVFocE81aVJyZzJs
            UkpSMnZobEh4U0FsUTVRdzhqSitUbXcKLS0tIFEzbHh2c2M1TGROVFg1alNKM0pq
            bkhpcUgyVWVGTTBrR0FDTVBqWUpXM1UKVyHT2P1xgyj1725gJa12LQUL3vhB7nEM
            S9ep1LoRxtvBzRW6AjjpNbPD4cuXnE4wNCC/sumT8dyy5RqtIil5Qw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T03:23:23Z"
    mac: ENC[AES256_GCM,data:Cg1Fticw1YxJUtA7xKVySivg+KliGGuIU2kZT/usahUeEDU1t4LFTHJBi5orcg3YmWlaeCVwtxuRVfLi62bdwGspLuzn8IJSWA+7ro4XLmxinCPGA5KAu5FZcCpYlUiMsS51u/08fuAWkUpta0OnMHiVXDVeu8yemF9GWF3T2k8=,iv:YbBY7khh9yr0QKZ+klyl1sAxQbSbkMbfWZlembay3AQ=,tag:7LbJCZtjtmq8+ITNbNJ9Cw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
