apiVersion: v1
kind: Secret
metadata:
    name: testsecret2
    namespace: testing
type: Opaque
data:
    SOMEKEY: ENC[AES256_GCM,data:pPK7zLCmTfEeH+4E1dW4nKyeaFk=,iv:46bWEYsG2MNaPRFzk4ZERPTdjHMHdqDg9TCepN931R0=,tag:t41+RbHeW1TzEthu1QdBRQ==,type:str]
    SOMEKEY2: ENC[AES256_GCM,data:POLfyvMmjJAPW9oLxE55bNgYvlm9b9IT,iv:06o/6yeVEwmmHtVMjh5HNWVVH9qifsb76xy1QwF9Y8w=,tag:4deG9hPsSC8nZ/MRUEKYww==,type:str]
    SOMEKEY3: ENC[AES256_GCM,data:v/WPzhF90zB+OSqvSfZKmehP2glMrbG2,iv:/4Sclyp9eRgEHwdo3aGMvOMMskGzD8HnHJ3GTlcEhZM=,tag:1npKHabhKP7WsXbj/Lx7qA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6R3l1MGpyK29aL1kzYm1a
            Rmd1dGVNSW15UHNZWk53UUpKak5PbVFWR0F3Cm5uMGlYUHBpSkxQWDRIMWkxbytm
            RUpveDhYaVRGOExNUEovWGFvajNsQ0EKLS0tIHlhby9ERjZGRUc5Y0dpWTlZanF3
            QVV3TEZVVFZ2QjBCa2RGamJ3Q1RMdVEKqBzV5vbazR425dtgI7JHAMn0RthwA2qd
            5bFBafuUKgxR6BiSdyXZqfuVGliI4xdnXRK3LS9Juyztz87nyTpGPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-28T17:35:22Z"
    mac: ENC[AES256_GCM,data:aK7OWj7PNoYmgd8DR+yxn30Uw01IpDqbLqlE0HHUaI0X7Gce7A5hZ58LM5+97Hj27V7KnaV/aKE+6XDgsUOXrEEPDYXWPK3VTqT9/i73V9eO1/WucUJME3v+lKMAqFs9ZLnWm3M89qZBYOnYzgxhitSJQqs+yYeX7ATXjgnIr3Q=,iv:WRd4DczM4XsHZNJsTJlzSjJE1sfdZ5UIS5+xfqux8Sw=,tag:ID047tODCZty37hLVsaiQw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
