apiVersion: v1
kind: Secret
metadata:
    name: testsecret2
    namespace: testing
type: Opaque
data:
    SOMEKEY: ENC[AES256_GCM,data:bGsJmbYtT+ia60aofSaBiQCntCU=,iv:9/wbyu0OSlpT7Ps1aMjQAgQMnIo63b1Atu6LO/2Lqf4=,tag:eXd77xre0RVWuh2HG7SF+w==,type:str]
    SOMEKEY2: ENC[AES256_GCM,data:QdYdkO05upmxxMHEDWglPAaIku4x5+WY,iv:pfuDgwqAxeE+QXOxAm2R4efsJ3C283sPt8ngCuA8WJQ=,tag:ZuZmmKKDq5BouwgLVq9R6A==,type:str]
    SOMEKEY3: ENC[AES256_GCM,data:Jg1zlFGRjZRcAYT1vfH7PvGNSOGBP7M0,iv:2nVa/YFKRNwsLdklo3FeyFZ7yuuBIepryLMmQX52Mlk=,tag:kUH8q+p/EC6PoZ2FiAKtzQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDditJQTVFTjlqMm52U3py
            QkVjZHRTMW44R0wzSWhYcXFCL0xucUJZSEU4CnJTOG1Pa29pUEplUFdYb3Uwelp4
            dVlHdDEzQjR5SWpFY0lwS1M3bDVhOWsKLS0tIEIvcnpQNmFsYmtYUENVSWc2S29W
            Yk9HNEFJbnIxTE5XSGZlT2FFRXJoTTgKt2K75x2ik27amVlHjLnL+zz8YYJ++omz
            DRneRFS9g/XsVHD3PJxn9l5ca1Xf6kXyXmzJGuEhJfMmqnuxjfInqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-09T18:04:56Z"
    mac: ENC[AES256_GCM,data:26xHr+TOL16X4GJkeXim1w2NKXhE/VC8RgLHXDxrcNl9iJMm9iNZ8Qa20izM/rph1ReTjTUoIYoEgNF18ESXG5rCEKW4HXNeSqRcKDJCGRJVOAxgKqcWPcRjaB0i9pNPtDKoN5A9py1H+3YhBnXIoqmlut7260ozFwWkJEQtfQk=,iv:FvvFnheFrxJ0NRn4MJJdBrdNb2DAhDj5fOabuVUJbgI=,tag:D8EuFwiWu5mYjmCKRORFtA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
