apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - blocky/ks.yaml
  - clusterissuer/ks.yaml
  - metallb-config/ks.yaml
  - system-upgrade-controller-plans/ks.yaml
  - mend-renovate/ks.yaml
  - scrutiny/ks.yaml
  - lldap/ks.yaml
  - authelia/ks.yaml
