apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mc-test
  namespace: mc-test
spec:
  interval: 2m
  timeout: 10m
  chart:
    spec:
      chart: minecraft-java
      version: 34.0.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    j21graalvmImage:
      repository: ghcr.io/itzg/minecraft-server
      tag: 2026.1.0-java21-graalvm@sha256:edd7b66781574ebb67c66f96635d7d1aa733f2886f6589fa4c4c1d8fdca96aac
      pullPolicy: Always
    mcBackupImage:
      repository: docker.io/itzg/mc-backup
      tag: latest@sha256:11d38fb3f08e677f98d1d95c032a50c37a1737c2893564fc12492abae082555e
      pullPolicy: Always
    global:
      stopAll: false
    service:
      main:
        enabled: true
        type: LoadBalancer
        annotations:
          mc-router.itzg.me/externalServerName: "mc-test.${DOMAIN_0}"
      rcon:
        enabled: true
        type: LoadBalancer
    mcbackup:
      zstd_params:
        - --long=25
        - --single-thread
      # comma separated list
      excludes:
        - "*.jar"
        - "cache"
        - "logs"
        - "*.tmp"
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: mc-test.${DOMAIN_0}
        integrations:
          homepage:
            enabled: true
            name: mc-test
            description: " "
            group: Games
            icon: minecraft.png
            href: " "
            widget:
              enabled: true
              type: minecraft
              url: udp://mc-test-minecraft-java.mc-test.svc.cluster.local:25565
    persistence:
      backups:
        enabled: true
        targetSelector:
          main:
            mcbackup:
              mountPath: /backups
        type: nfs
        path: /mnt/DSU/Backups/Minecraft/mc-test
        server: ${TRUENAS_IP}
      data:
        targetSelector:
          main:
            main:
              mountPath: /data
            mcbackup:
              mountPath: /data
              readOnly: true
      mods:
        enabled: true
        type: pvc
        mountPath: /mods
        targetSelectAll: true
        size: 5Gi
      rs-config-patch:
        enabled: true
        type: configmap
        objectName: rs-config-patch
        targetSelector:
          main:
            main:
              mountPath: /patches
              readOnly: true
    configmap:
      rs-config-patch:
        enabled: true
        data:
          rs-config-patch.json: |
            {
              "file": "/data/config/refinedstorage-common.toml",
              "ops": [
                {
                  "$set": {
                    "path": "$.controller.energyCapacity",
                    "value": 99999
                  }
                }
              ]
            }
    resources:
      limits:
        cpu: null
        memory: null
      requests:
        cpu: 100m
        memory: 1Gi
    workload:
      main:
        podSpec:
          containers:
            main:
              imageSelector: j21graalvmImage
              env:
                OPS: Hydranoid620
                WHITELIST: Hydranoid620
                DIFFICULTY: easy
                ENABLE_COMMAND_BLOCK: true
                VERSION: 1.21.1
                TYPE: FTBA
                FTB_MODPACK_ID: 129
                FTB_MODPACK_VERSION_ID: 100131
                FTB_FORCE_REINSTALL: false
                MAX_PLAYERS: 1
                MOTD: mc-test
                PVP: true
                MEMORY: "6G"
                # JVM_XX_OPTS: -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:MaxRAMPercentage=50 -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1  -XX:+AlwaysPreTouch
                MAX_TICK_TIME: 60000
                RCON_PASSWORD: ${MC_RCON_PASSWORD}
                USE_MODPACK_START_SCRIPT: true
                SEED: "-6792938523469477000"
                FORCE_REDOWNLOAD: false
                VIEW_DISTANCE: 10
                USE_AIKAR_FLAGS: false
                USE_FLARE_FLAGS: false
                USE_MEOWICE_FLAGS: true
                USE_MEOWICE_GRAALVM_FLAGS: true
                USE_SIMD_FLAGS: false
                ALLOW_FLIGHT: true
                PATCH_DEFINITIONS: "/patches"
            mcbackup:
              enabled: true
              imageSelector: mcBackupImage
              probes:
                liveness:
                  enabled: false
                readiness:
                  enabled: false
                startup:
                  enabled: false
              env:
                BACKUP_METHOD: "tar"
                DEST_DIR: "{{.Values.persistence.backups.targetSelector.main.mcbackup.mountPath }}"
                SRC_DIR: "{{.Values.persistence.data.mountPath }}"
                SERVER_PORT: "{{ .Values.service.main.ports.main.port }}"
                RCON_HOST: '{{ printf "%s-rcon" (include "tc.v1.common.lib.chart.names.fullname" $) }}'
                RCON_PORT: "{{ .Values.service.rcon.ports.rcon.port }}"
                RCON_PASSWORD: "{{ .Values.workload.main.podSpec.containers.main.env.RCON_PASSWORD }}"
                SERVER_HOST: '{{ include "tc.v1.common.lib.chart.names.fullname" $ }}'
                ZSTD_PARAMETERS: '{{ join " " .Values.mcbackup.zstd_params }}'
                EXCLUDES: '{{ join "," .Values.mcbackup.excludes }}'
                BACKUP_INTERVAL: "4h"
                INITIAL_DELAY: "2m"
                LINK_LATEST: "false"
                PAUSE_IF_NO_PLAYERS: "false"
                PLAYERS_ONLINE_CHECK_INTERVAL: "5m"
                PRUNE_BACKUPS_DAYS: "4"
                TAR_COMPRESS_METHOD: "zstd"
    addons:
      codeserver:
        enabled: false
        ingress:
          enabled: true
          ingressClassName: external
          hosts:
            - host: mc-test-config.${DOMAIN_0}
          integrations:
            certManager:
              enabled: true
              certificateIssuer: le-prod
            nginx:
              enabled: true
              auth:
                type: authelia
                internalHost: ${AUTHELIA_INTERNAL_DNS}
                externalHost: ${AUTHELIA_EXTERNAL_DNS}
