apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: stepify
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/testing/stepify/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
